#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\RyukReturnSim-utilities.ps1"
Assert-RRSafety -LabConfirmed:$LabConfirmed;$p=Initialize-RREnvironment
$roles=[ordered]@{'BAK01-CANARY'='backup server';'APP01-CANARY'='application server';'FS01-CANARY'='file server';'WS01-CANARY'='workstation';'WS02-CANARY'='workstation';'DC01-CANARY'='generated pivot DC representation'}
foreach($entry in $roles.GetEnumerator()){$null=New-RRHostTree -Name $entry.Key -Role $entry.Value}
$ryuk=Join-Path $p.Payloads 'fx16_multi_for_crypt_x86.exe';$console=Join-Path $p.Payloads 'wbadmin.msc.exe'
New-RRDecoy -Path $ryuk -Role 'Ryuk ransomware stand-in' -PublishedSha256 'f7998c8b083b31e8b0e8eaf197f6db65b100d44d94700e0780e81c7d54eefcf5'
New-RRDecoy -Path $console -Role 'wbadmin console telemetry stand-in'
Invoke-RRDecoy -FilePath $console -Reported 'wbadmin.msc opened on the backup server before ransomware execution' -Parent 'RDP session from compromised DC' -Label 'NO-BACKUP-ACTION'
$commands=@('net1 stop samss /y','net1 stop veeamcatalogsvc /y','net1 stop veeamcloudsvc /y','net1 stop veeamdeploysvc /y','net.exe stop samss /y','net.exe stop veeamcatalogsvc /y','net.exe stop veeamcloudsvc /y','net.exe stop veeamdeploysvc /y','taskkill /IM sqlbrowser.exe /F','taskkill /IM sqlceip.exe /F','taskkill /IM sqlservr.exe /F','taskkill /IM sqlwriter.exe /F','taskkill /IM veeam.backup.agent.configurationservice.exe /F','taskkill /IM veeam.backup.brokerservice.exe /F','taskkill /IM veeam.backup.catalogdataservice.exe /F','taskkill /IM veeam.backup.cloudservice.exe /F','taskkill /IM veeam.backup.externalinfrastructure.dbprovider.exe /F','taskkill /IM veeam.backup.manager.exe /F','taskkill /IM veeam.backup.mountservice.exe /F','taskkill /IM veeam.backup.service.exe /F','taskkill /IM veeam.backup.uiserver.exe /F','taskkill /IM veeam.backup.wmiserver.exe /F','taskkill /IM veeamdeploymentsvc.exe /F','taskkill /IM veeamfilesysvsssvc.exe /F','taskkill /IM veeam.guest.interaction.proxy.exe /F','taskkill /IM veeamnfssvc.exe /F','taskkill /IM veeamtransportsvc.exe /F','taskmgr.exe /4','wmiprvse.exe -Embedding','wmiprvse.exe -secured -Embedding','icacls "C:\*" /grant Everyone:F /T /C /Q','icacls "D:\*" /grant Everyone:F /T /C /Q')
foreach($command in $commands){Invoke-RRDecoy -FilePath $ryuk -Reported $command -Parent 'fx16_multi_for_crypt_x86.exe' -Label 'NO-IMPACT-COMMAND'}
Write-RRJson -Path(Join-Path $p.Evidence 'pre-impact-commands.json')-Object([ordered]@{reportedCommands=$commands;wbadminConsoleOpened=$false;servicesStopped=0;processesTerminated=0;aclChanges=0;drivesTraversed=0})-Purpose impact
$records=New-Object System.Collections.Generic.List[object]
foreach($entry in $roles.GetEnumerator()){$root=Join-Path $p.Hosts $entry.Key;Write-RRFile -Path(Join-Path $root 'C$\Finance\RyukReadMe.txt')-Content "INERT RYUK NOTE CANARY for $($entry.Key). Reported demand: more than 600 BTC / $6M; no payment instructions or original note included." -Purpose ransom-note-canary;Write-RRFile -Path(Join-Path $root 'C$\Finance\forecast.xlsx.RYUK-CANARY')-Content "INERT ENCRYPTION MARKER for generated host $($entry.Key). No file was encrypted." -Purpose encryption-canary;$records.Add([ordered]@{hostname=$entry.Key;role=$entry.Value;generatedTree=$root;markers=2;userFilesRead=0;userFilesChanged=0;filesEncrypted=0})}
Write-RRJson -Path(Join-Path $p.Evidence 'impact-summary.json')-Object([ordered]@{reportedDurationMinutes=1740;reportedOrder=@('backup server first','servers and workstations','domain-wide completion');reportedDemand='more than 600 bitcoin, valued at over $6 million at the time';generatedHosts=$records;rdpSessions=0;smbSessions=0;remoteFilesWritten=0;servicesStopped=0;processesTerminated=0;aclChanges=0;userFilesChanged=0;filesEncrypted=0;generatedCanaryMarkers=12})-Purpose impact
Invoke-RRLoopback -Port 3389 -Target 'backup server, servers, and workstations from pivot DC' -Role 'Ryuk RDP marker'
Invoke-RRLoopback -Port 445 -Target 'enterprise targets' -Role 'Ryuk SMB transfer marker'
Add-RRTimeline 1735 lateral-movement 'Backup system targeted about one hour after first movement; wbadmin console represented' @{rdpSessions=0;wbadminConsoleOpened=$false}
Add-RRTimeline 1739 impact 'Ryuk executable transferred to generated backup server' @{smbSessions=0;remoteFilesWritten=0}
Add-RRTimeline 1740 impact 'Ryuk executed one minute after reported transfer and domain-wide 29-hour completion represented' @{filesEncrypted=0;userFilesChanged=0;generatedCanaryMarkers=12}
Write-RRJson -Path(Join-Path $p.Evidence 'phase3-negative.json')-Object([ordered]@{wbadminConsoleOpened=$false;backupConfigurationChanged=0;rdpSessions=0;smbSessions=0;remoteFilesWritten=0;servicesStopped=0;processesTerminated=0;aclChanges=0;drivesTraversed=0;userFilesRead=0;userFilesChanged=0;filesEncrypted=0;securityControlsChanged=0;logsCleared=0;shadowCopiesDeleted=0;externalConnections=0;bytesTransferred=0})-Purpose safety
