#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:ToolkitId='023-Sliver_PoshC2_SystemBC_Batch_Toolkit';$script:ToolkitUrl='https://thedfirreport.com/2024/08/12/threat-actors-toolkit-leveraging-sliver-poshc2-batch-scripts/'
function Get-ToolkitPaths{$r=Join-Path $env:PUBLIC 'SliverPoshC2ToolkitSim';[ordered]@{Root=$r;Directory1=Join-Path $r 'open-directory-94.198.53.143';Directory2=Join-Path $r 'open-directory-185.234.216.64';Batch=Join-Path $r 'recovered-batch-canaries';Binaries=Join-Path $r 'recovered-binary-decoys';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\capability-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.SliverPoshC2ToolkitSim.owner'}}
function Assert-ToolkitSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-ToolkitManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-ToolkitPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:ToolkitId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-ToolkitEnvironment{$p=Get-ToolkitPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:ToolkitId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Directory1,$p.Directory2,$p.Batch,$p.Binaries,$p.Evidence)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:ToolkitId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-ToolkitManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return $p}
function Write-ToolkitFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-ToolkitManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-ToolkitDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-ToolkitManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;match=$false}}
function Invoke-ToolkitDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$s=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','TOOLKIT-CANARY',$s);$x=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -NoNewWindow;$null=$x.ExitCode;Add-ToolkitManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');escaped=$true}}
function Invoke-ToolkitLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-ToolkitManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-ToolkitTimeline{param([string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-ToolkitPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-ToolkitSummary{param($Paths);Write-ToolkitFile $Paths.Summary "SliverPoshC2ToolkitSim complete.`nSource: $script:ToolkitUrl`nThis is an open-directory capability reconstruction, not an invented victim intrusion timeline.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo live malware, IOC connection, account/RDP/share change, tunnel, service/process impairment, security modification, backup/shadow deletion, log clearing, or remote-access software installation occurred." 'operator summary'}
