#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:WinContiId='064-Bazar_Cobalt_WinSCP_Conti_32h';$script:WinContiUrl='https://thedfirreport.com/2021/09/13/bazarloader-to-conti-ransomware-in-32-hours/';$script:WinContiAnchor=(Get-Date).ToUniversalTime().AddHours(-32)
function Get-WinContiPaths{$r=Join-Path $env:PUBLIC 'WinContiSim';[ordered]@{Root=$r;Lures=Join-Path $r 'lure-canaries';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Discovery=Join-Path $r 'generated-discovery';Staging=Join-Path $r 'generated-staging';Impact=Join-Path $r 'impact-canaries';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.WinContiSim.owner'}}
function Assert-WinContiSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-WinContiManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-WinContiPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:WinContiId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-WinContiEnvironment{$p=Get-WinContiPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:WinContiId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lures,$p.Payloads,$p.Hosts,$p.Discovery,$p.Staging,$p.Impact,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:WinContiId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-WinContiManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedDcCanaryOnly=$true};$p}
function Write-WinContiFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-WinContiManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-WinContiDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-WinContiManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-WinContiDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='rundll32.exe');$args=@('/d','/v:off','/c','echo','WIN-CONTI-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-WinContiManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-WinContiLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-WinContiManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-WinContiTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-WinContiPaths;[ordered]@{timestampUtc=$script:WinContiAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-WinContiSummary{param($Paths);Write-WinContiFile $Paths.Summary "WinContiSim complete.`nSource: $script:WinContiUrl`nThe 32-hour Bazar/WMIC/WinSCP/Conti chronology is preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo phishing/script, malware, pass-the-hash/authentication, injection, LSASS/credential access, scan/discovery/AD query, SMB/WMI/service/RDP remote action, WinSCP install, real collection/exfiltration, TOR access, ransomware, share mount, or encryption occurred." 'operator summary'}
