#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BeeMeterSim-utilities.ps1";Assert-BeeMeterSafety -LabConfirmed:$LabConfirmed;$p=Initialize-BeeMeterEnvironment
$imaging=Join-Path $p.Payloads 'ImagingDevices.exe';New-BeeMeterDecoy $imaging 'WmiPrvSE-spawned Meterpreter injection stand-in';Invoke-BeeMeterDecoy $imaging 'WmiPrvSE.exe -> ImagingDevices.exe; Meterpreter injected at hour 12' 'WmiPrvSE.exe';Invoke-BeeMeterLoopback 443 'ec2-3-16-159-37.us-east-2.compute.amazonaws.com / 3.16.159.37:80/443 Meterpreter' 'Meterpreter marker'
$cmd=Join-Path $p.Payloads 'svchost.exe';New-BeeMeterDecoy $cmd 'Migrated Meterpreter and Cobalt process stand-in';foreach($c in @('nltest /dclist:LAB.DOMAIN','net view /all','net group "Domain Computers" /domain','net group "domain Admins" /domain','whoami','whoami /groups','echo %USERDOMAIN%','ping -n 1 LAB-DC01','systeminfo','tasklist')){Invoke-BeeMeterDecoy $cmd $c 'ImagingDevices.exe';Add-BeeMeterManifest discovery-command 'generated-commandline-only' represented @{reportedCommandLine=$c;executedDiscovery=$false}}
$uac=@{attempts=@(@{method='WSReset DelegateExecute';result='failed'},@{method='slui registry hijack';result='failed'},@{method='WSReset DelegateExecute';reportedResult='success'});registryChanges=0;highIntegrityProcesses=0;UACBypassed=$false;getsystemInvoked=$false;SYSTEMContextObtained=$false;namedPipeCommands=@('echo wafrms > \\.\pipe\wafrms','echo dec8f35bcbf > \\.\pipe\7fd13a');namedPipesCreated=0};Write-BeeMeterFile(Join-Path $p.Evidence 'uac-getsystem-negative-record.json')($uac|ConvertTo-Json -Depth 7)'privilege safety record'
Write-BeeMeterFile(Join-Path $p.Payloads 'n23.dll')'INERT COBALT STRIKE DLL-NAME CANARY. Not a PE file.''Cobalt canary';Invoke-BeeMeterDecoy $cmd 'elevated Meterpreter getsystem -> rundll32 n23.dll,AddProgram' 'svchost.exe';foreach($t in @('cevogesu.com / 172.93.201.12:443','titojukus.com / 23.106.215.100:443')){Invoke-BeeMeterLoopback 443 $t 'Cobalt Strike marker'}
$proc=Join-Path $p.Payloads 'procdump64.exe';New-BeeMeterDecoy $proc 'ProcDump LSASS stand-in';Invoke-BeeMeterDecoy $proc 'procdump64.exe -accepteula -ma lsass.exe C:\ProgramData\lsass.dmp' 'svchost.exe';foreach($n in @('lsass.dmp','sam.hive','security.save','system.save')){Write-BeeMeterFile(Join-Path $p.Staging $n)"GENERATED CREDENTIAL-ARTIFACT CANARY $n. Contains no process memory, hive, credentials, or secrets."'credential canary'}
Write-BeeMeterFile(Join-Path $p.Evidence 'credential-injection-negative-record.json')(@{reportedInjectionTargets=@('ImagingDevices.exe','svchost.exe','winlogon.exe');processesInjected=0;LSASSOpened=$false;LSASSBytesRead=0;registryHivesRead=0;credentialsCollected=0;realDumpsCreated=0}|ConvertTo-Json)'credential safety record';Write-BeeMeterFile(Join-Path $p.Evidence 'named-pipes-metadata.json')(@{cobalt=@('postex_002d','postex_67cc','postex_731d','postex_a4c1','postex_c69e','postex_b6fd','postex_5a0d','postex_d43a','postex_a820');meterpreter=@('4ae13d6c2cd672ae\pipe\spoolss','0029482318be6784','uwjjqz','vllyad');created=0}|ConvertTo-Json)'pipe metadata'
Add-BeeMeterTimeline 12 execution 'WmiPrvSE launches ImagingDevices and Meterpreter injection represented' @{processesInjected=0;technique='T1055'};Add-BeeMeterTimeline 12.62 defense-evasion 'Meterpreter migrates to svchost and attempts WSReset/slui UAC bypasses' @{UACBypassed=$false;technique='T1548.002'};Add-BeeMeterTimeline 13 privilege-escalation 'Final WSReset and getsystem success represented without elevation' @{SYSTEMContextObtained=$false};Add-BeeMeterTimeline 13.1 execution 'SYSTEM-context Meterpreter launches Cobalt Strike DLL' @{beaconExecuted=$false};Add-BeeMeterTimeline 14 credential-access 'ProcDump LSASS and SAM/SECURITY/SYSTEM hive saves represented with generated canaries' @{credentialsCollected=0;techniques=@('T1003.001','T1003.002')}
