#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BeeMeterSim-utilities.ps1";Assert-BeeMeterSafety -LabConfirmed:$LabConfirmed;$p=Initialize-BeeMeterEnvironment
$tool=Join-Path $p.Payloads 'af.exe';New-BeeMeterDecoy $tool 'AdFind stand-in';foreach($c in @('af.exe -f "(objectcategory=person)" > ad_users.txt','af.exe -f "objectcategory=computer" > ad_computers.txt','Invoke-ShareFinder | Out-File sh.txt')){Invoke-BeeMeterDecoy $tool $c 'rundll32.exe'};Write-BeeMeterFile(Join-Path $p.Staging 'ad_users.txt')"GENERATED AD USERS`nLAB-USER01`nNo directory query occurred."'generated AD canary';Write-BeeMeterFile(Join-Path $p.Staging 'ad_computers.txt')"GENERATED AD COMPUTERS`nLAB-DC01`nLAB-WS02`nNo directory query occurred."'generated AD canary';Write-BeeMeterFile(Join-Path $p.Staging 'sh.txt')"GENERATED SHARES`n\\LAB-FILE01\Files`nNo share was queried."'generated ShareFinder canary'
Add-BeeMeterJsonLine(Join-Path $p.Logs 'Netlogon-and-Security.jsonl')@{protocol='Netlogon';methods=@('NetrServerReqChallenge','NetrServerAuthenticate2','NetrServerPasswordSet2');source='BEACHHEAD';target='LAB-DC01';requestsSent=0;synthetic=$true}'ZeroLogon network canary';Add-BeeMeterJsonLine(Join-Path $p.Logs 'Netlogon-and-Security.jsonl')@{eventId=4742;subject='BEACHHEAD$';targetComputer='LAB-DC01$';passwordChanged=$false;synthetic=$true}'4742 event canary'
$zero=@{cve='CVE-2020-1472';reportedExploitResult='success';exploitAttempted=$false;NetlogonRequests=0;domainControllerPasswordReset=$false;allZeroCredentialSet=$false;event4742WrittenToRealLog=$false;passTheHashAttempted=$false;credentialsUsed=$false;domainAdminContextObtained=$false;authenticationFailuresCaused=0;domainControllerResponsive=$true};Write-BeeMeterFile(Join-Path $p.Evidence 'zerologon-pth-impact-negative-record.json')($zero|ConvertTo-Json -Depth 6)'ZeroLogon safety record'
Write-BeeMeterFile(Join-Path $p.Payloads 'remote-n23.dll')'INERT COBALT DLL-NAME CANARY. Not a PE file.''remote payload canary';Invoke-BeeMeterDecoy $tool 'SMB copy n23.dll to LAB-WS02 and LAB-DC02 C$\ProgramData; service runs rundll32 n23.dll,AddProgram' 'beacon.exe';foreach($port in @(445,135)){Invoke-BeeMeterLoopback $port "LAB-WS02/LAB-DC02 SMB and service-control marker" 'lateral marker'}
Write-BeeMeterFile(Join-Path $p.Evidence 'remote-cleanup-negative-record.json')(@{remoteHostsTouched=0;SMBCopies=0;remoteServicesCreated=0;remoteProcesses=0;filesDeleted=0;directoryQueries=0;sharesQueried=0}|ConvertTo-Json)'remote safety record';Write-BeeMeterFile(Join-Path $p.Hosts 'LAB-DC01-authentication-impact.canary')'REPORTED IMPACT CANARY: primary DC authentication was broken after ZeroLogon. No authentication or DC state changed in this exercise.''impact canary'
Add-BeeMeterTimeline 18 discovery 'AdFind user/computer enumeration and Invoke-ShareFinder sh.txt represented' @{directoryQueries=0;sharesQueried=0;techniques=@('T1087.002','T1135')};Add-BeeMeterTimeline 19 privilege-escalation 'Successful ZeroLogon and Event 4742 represented without exploit or password change' @{exploitAttempted=$false;passwordsChanged=0;technique='T1068'};Add-BeeMeterTimeline 19.05 credential-access 'Pass-the-hash into Domain Admin user context represented' @{hashesUsed=0;technique='T1550.002'};Add-BeeMeterTimeline 19.1 lateral-movement 'SMB n23.dll copies and remote service execution on workstation/DC represented' @{remoteHostsTouched=0;techniques=@('T1021.002','T1569.002','T1570')};Add-BeeMeterTimeline 19.2 impact 'Primary DC authentication failure reported before eviction' @{authenticationFailuresCaused=0;domainControllerResponsive=$true}
