#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:BeeMeterId='042-BumbleBee_Meterpreter_CobaltStrike_ZeroLogon_19h';$script:BeeMeterUrl='https://thedfirreport.com/2022/11/14/bumblebee-zeros-in-on-meterpreter/';$script:BeeMeterAnchor=(Get-Date).ToUniversalTime().AddHours(-19)
function Get-BeeMeterPaths{$r=Join-Path $env:PUBLIC 'BeeMeterSim';[ordered]@{Root=$r;Lure=Join-Path $r 'contact-form-lure';Beach=Join-Path $r 'BEACHHEAD';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Logs=Join-Path $r 'generated-event-logs';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.BeeMeterSim.owner'}}
function Assert-BeeMeterSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-BeeMeterManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-BeeMeterPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:BeeMeterId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-BeeMeterEnvironment{$p=Get-BeeMeterPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:BeeMeterId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beach,$p.Payloads,$p.Staging,$p.Hosts,$p.Evidence,$p.Logs)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:BeeMeterId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-BeeMeterManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-BeeMeterFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-BeeMeterManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Add-BeeMeterJsonLine{param([string]$Path,[hashtable]$Record,[string]$Purpose='generated event');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};$Record|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $Path -Encoding UTF8;Add-BeeMeterManifest generated-event $Path appended @{purpose=$Purpose;synthetic=$true}}
function New-BeeMeterDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-BeeMeterManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-BeeMeterDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='explorer.exe');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','BEE-METER-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-BeeMeterManifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-BeeMeterLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-BeeMeterManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-BeeMeterTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-BeeMeterPaths;[ordered]@{timestampUtc=$script:BeeMeterAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-BeeMeterSummary{param($Paths);Write-BeeMeterFile $Paths.Summary "BeeMeterSim complete.`nSource: $script:BeeMeterUrl`nObserved hands-on sequence represented: 19 hours.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malware, ISO mount, injection, UAC bypass, getsystem, credential or hive access, exploit, account/password change, pass-the-hash, remote service/share action, authentication impairment, IOC contact, or file deletion occurred." 'operator summary'}
