#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:BlueSkyId='030-MSSQL_BruteForce_CobaltStrike_Tor2Mine_BlueSky'
$script:BlueSkyUrl='https://thedfirreport.com/2023/12/04/sql-brute-force-leads-to-bluesky-ransomware/'
$script:BlueSkyAnchor=(Get-Date).ToUniversalTime().AddMinutes(-32)
function Get-BlueSkyPaths{$r=Join-Path $env:PUBLIC 'BlueSkySQLSim';[ordered]@{Root=$r;Sql=Join-Path $r 'mssql-beachhead';Events=Join-Path $r 'event-replicas';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Impact=Join-Path $r 'impact-canaries';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.BlueSkySQLSim.owner'}}
function Assert-BlueSkySafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-BlueSkyManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-BlueSkyPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:BlueSkyId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8}
function Initialize-BlueSkyEnvironment{$p=Get-BlueSkyPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:BlueSkyId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Sql,$p.Events,$p.Payloads,$p.Hosts,$p.Impact,$p.Evidence)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:BlueSkyId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-BlueSkyManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-BlueSkyFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-BlueSkyManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-BlueSkyDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-BlueSkyManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;hashMatch=$false}}
function Invoke-BlueSkyDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','BLUESKY-SQL-CANARY',$safe);$proc=Start-Process $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-BlueSkyManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-BlueSkyLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-BlueSkyManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-BlueSkyTimeline{param([int]$OffsetMinutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-BlueSkyPaths;[ordered]@{timestampUtc=$script:BlueSkyAnchor.AddMinutes($OffsetMinutes).ToString('o');offsetMinutes=$OffsetMinutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-BlueSkySummary{param($Paths);Write-BlueSkyFile $Paths.Summary "BlueSkySQLSim complete.`nSource: $script:BlueSkyUrl`nSimulated time to ransomware: 32 minutes.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo SQL account was attacked, xp_cmdshell enabled, malware run, process injected, LSASS accessed, AV changed, service/task created, host scanned, remote system touched, file encrypted, or data exfiltrated." 'operator summary'}
