#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BlueSkySQLSim-utilities.ps1";Assert-BlueSkySafety -LabConfirmed:$LabConfirmed;$p=Initialize-BlueSkyEnvironment
$authPath=Join-Path $p.Events 'mssql-18456-application.jsonl';$records=New-Object System.Collections.Generic.List[string];for($i=1;$i-le10000;$i++){$records.Add(([ordered]@{timestampUtc=$script:BlueSkyAnchor.AddMilliseconds($i*45).ToString('o');eventId=18456;account='sa';result='failure';reason='password mismatch';synthetic=$true}|ConvertTo-Json -Compress))};$records.Add(([ordered]@{timestampUtc=$script:BlueSkyAnchor.AddMinutes(1).ToString('o');eventId=18454;account='sa';result='success';synthetic=$true;realAuthentication=$false}|ConvertTo-Json -Compress));Write-BlueSkyFile $authPath ($records-join"`n")'10,000 failure and one success replicas'
$sqlservr=Join-Path $p.Sql 'sqlservr.exe';New-BlueSkyDecoy $sqlservr 'MSSQL parent process stand-in';Invoke-BlueSkyDecoy $sqlservr 'sqlservr.exe -> xp_cmdshell -> cmd.exe -> powershell.exe -EncodedCommand [REDACTED-CANARY]'
$sql=[ordered]@{target='generated MSSQL beachhead';account='sa';failedAttempts=10000;successfulReplica=1;realLogin=$false;xpCmdShellEnabled=$false;configurationChanged=$false;osCommandExecuted=$false};Write-BlueSkyFile(Join-Path $p.Evidence 'mssql-access-negative-record.json')($sql|ConvertTo-Json)'MSSQL evidence'
$cs=[ordered]@{c2='5.188.86.237:443';sleep=120000;jitter=12;licenseId=1580103824;get='/functionalStatus/2JYbAmfY5gYNj7UrgAte5p1jXx2V';post='/rest/2/meetings2JYbAmfY5gYNj7UrgAte5p1jXx2V';spawnto='auditpol.exe';allocator='NtMapViewOfSection';minimumAllocation=40263;startRwx=$true;injectionTarget='winlogon.exe';injectionPerformed=$false};Write-BlueSkyFile(Join-Path $p.Evidence 'cobalt-strike-config.json')($cs|ConvertTo-Json -Depth 6)'Cobalt configuration';Invoke-BlueSkyLoopback 443 '5.188.86.237 Cobalt Strike' 'HTTPS marker'
Write-BlueSkyFile(Join-Path $p.Events 'sysmon-event-8.json')([ordered]@{eventId=8;source='PowerShell/Cobalt canary';target='winlogon.exe';api='CreateRemoteThread';generatedRecordOnly=$true;processOpened=$false;threadCreated=$false}|ConvertTo-Json)'injection event replica'
Add-BlueSkyTimeline 0 initial-access 'Ten thousand MSSQL sa authentication failures represented' @{realAttempts=0;technique='T1110'};Add-BlueSkyTimeline 1 execution 'Synthetic successful login and xp_cmdshell process chain represented' @{xpCmdShellEnabled=$false;techniques=@('T1078','T1059.003','T1059.001')};Add-BlueSkyTimeline 3 command-and-control 'Cobalt beacon and winlogon injection represented' @{injection=$false;remoteContact=$false;techniques=@('T1071.001','T1055','T1027')}
