#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BlueSkySQLSim-utilities.ps1";Assert-BlueSkySafety -LabConfirmed:$LabConfirmed;$p=Initialize-BlueSkyEnvironment
Write-BlueSkyFile(Join-Path $p.Payloads 'checking.ps1')"# INERT Tor2Mine checking.ps1 canary`n# No download, AV, service, task, registry, miner, or credential logic."'Tor2Mine script canary';Write-BlueSkyFile(Join-Path $p.Payloads 'del.ps1')"# INERT del.ps1 canary`n# Does not terminate Process Explorer, Task Manager, Process Monitor, or Daphne."'defense-evasion canary';Write-BlueSkyFile(Join-Path $p.Payloads 'WinRing0x64.sys')'INERT DRIVER-NAME CANARY. Not a driver and never loaded.''driver canary'
$java=Join-Path $p.Payloads 'C\ProgramData\Oracle\Java\java.exe';New-BlueSkyDecoy $java 'Tor2Mine java.exe miner filename canary' '74b6d14e35ff51fe47e169e76b4732b9f157cd7e537a2ca587c58dbdb15c624f';Invoke-BlueSkyDecoy $java 'checking.ps1 PrivTrue -> java.exe and WinRing0x64.sys (represented only)'
$tasks=@('\Microsoft\Windows\MUI\LPupdate','\Microsoft\Windows\RamDiagnostic\Error Diagnostic','\Microsoft\Windows\.NET Framework\.NET Framework Cache Optimization Files-S-3-5-21-2236678156-433529325-2142214268-1138','\Microsoft\Windows\.NET Framework\.NET Framework Cache Optimization Files-S-3-5-21-2236678155-433529325-2142214968-1138','\Microsoft\Windows\.NET Framework\.NET Framework Cache Optimization','\Microsoft\Windows\Registry\RegBackup','\Microsoft\Windows\DiskCleanup\SlientDefragDisks','\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.50319 Critical','\Microsoft\Windows\EDP\EDP App Update Cache','\Microsoft\Windows\EDP\EDP App Lock Task','\Microsoft\Windows\UPnP\UPnPClient Task','\Microsoft\Windows\UPnP\UPnPHost','\Microsoft\Windows\Shell\WinShell','\Microsoft\Windows\Shell\WindowsShellUpdate','\Microsoft\Windows\Bluetooth\UpdateDeviceTask','\Microsoft\Windows\.NET Framework\.NET Framework Cache Optimization')
Write-BlueSkyFile(Join-Path $p.Evidence 'tor2mine-task-records.json')([ordered]@{reportedTaskCount=16;names=$tasks;createdCount=0;servicesCreated=0;registryChanges=0}|ConvertTo-Json -Depth 5)'task negative records'
$unsafe=[ordered]@{tor2MineC2='83.97.20.81:443';ja3='c12f54a3f91dc7bafd92cb59fe009a35';ja3s='ec74a5c51106f0419184d0dd08fb05bc';kallenObserved=$false;minerExecuted=$false;driverLoaded=$false;defenderChanged=$false;otherAvStopped=$false;utilitiesTerminated=$false;lsassGrantedAccessReported='0x1010';lsassAccessed=$false;invokePowerDumpRun=$false;smbScan=$false;svcctlCalled=$false;remoteServicesCreated=0;domainControllersTouched=0};Write-BlueSkyFile(Join-Path $p.Evidence 'tor2mine-lateral-negative-record.json')($unsafe|ConvertTo-Json -Depth 6)'unsafe-action refusal evidence';Invoke-BlueSkyLoopback 443 '83.97.20.81 Tor2Mine' 'TLS marker';Invoke-BlueSkyLoopback 445 'generated SMB scan and remote-service targets' 'SMB marker'
Add-BlueSkyTimeline 6 execution 'Tor2Mine privilege branch, miner, driver, and 16 tasks represented' @{tasksCreated=0;minerRun=$false;techniques=@('T1053.005','T1543.003','T1036.004','T1112')};Add-BlueSkyTimeline 9 defense-evasion 'AV impairment and utility termination represented as negative records' @{securityControlsChanged=$false;technique='T1562.001'};Add-BlueSkyTimeline 12 credential-access 'LSASS 0x1010 and Invoke-PowerDump evidence represented without process access' @{credentialsAccessed=$false;technique='T1003.001'};Add-BlueSkyTimeline 15 lateral-movement 'SMBExec discovery and remote-service movement toward DCs and shares represented' @{remoteConnections=0;techniques=@('T1135','T1021.002','T1569.002')}
