#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:LBId='091-RDP_Hakops15_LockBit_SingleHost';$script:LBUrl='https://thedfirreport.com/2020/06/10/lockbit-ransomware-why-you-no-spread/';$script:LBAnchor=(Get-Date).ToUniversalTime().AddMinutes(-60)
function Get-LBPaths{$r=Join-Path $env:PUBLIC 'LockBitSingleSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Host=Join-Path $r 'generated-host';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.LockBitSingleSim.owner'}}
function Assert-LBSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw 'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-LBManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-LBPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:LBId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-LBEnvironment{$p=Get-LBPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:LBId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Evidence,$p.Host)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:LBId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};foreach($d in @('C$\Desktop','C$\Finance')){New-Item(Join-Path $p.Host $d)-ItemType Directory -Force|Out-Null};Add-LBManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-LBFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-LBManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Write-LBJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-LBFile $Path ($Object|ConvertTo-Json -Depth 12) $Purpose}
function New-LBDecoy{param([string]$Path,[string]$Role);New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-LBManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;publishedHash='none'}}
function Invoke-LBDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','LOCKBIT-SINGLE-CANARY');$q=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -WindowStyle Hidden;$null=$q.ExitCode;Add-LBManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-LBLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-LBManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-LBTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-LBPaths;[ordered]@{timestampUtc=$script:LBAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-LBSummary{param($p);Write-LBFile $p.Summary "LockBitSingleSim complete.`nSource: $script:LBUrl`nA generated 60-minute axis preserves the published 15-minute account switch and event order; no duration is published.`nNo authentication, RDP, keylogging, FTP, defense change, recovery deletion, scan, SMB, registry change, spread, or encryption occurred.`nArtifacts remain; cleanup is separate." summary}
