#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:QuantumFastId='051-IcedID_Cobalt_RDP_WMI_PsExec_Quantum_3h44m';$script:QuantumFastUrl='https://thedfirreport.com/2022/04/25/quantum-ransomware/';$script:QuantumFastAnchor=(Get-Date).ToUniversalTime().AddMinutes(-224)
function Get-QuantumFastPaths{$r=Join-Path $env:PUBLIC 'QuantumFastSim';[ordered]@{Root=$r;Lure=Join-Path $r 'iso-lure';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.QuantumFastSim.owner'}}
function Assert-QuantumFastSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-QuantumFastManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-QuantumFastPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:QuantumFastId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-QuantumFastEnvironment{$p=Get-QuantumFastPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:QuantumFastId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Payloads,$p.Staging,$p.Hosts,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:QuantumFastId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-QuantumFastManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-QuantumFastFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-QuantumFastManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-QuantumFastDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-QuantumFastManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-QuantumFastDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='explorer.exe');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','QUANTUM-FAST-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-QuantumFastManifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-QuantumFastLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-QuantumFastManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-QuantumFastTimeline{param([double]$OffsetMinutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-QuantumFastPaths;[ordered]@{timestampUtc=$script:QuantumFastAnchor.AddMinutes($OffsetMinutes).ToString('o');offsetMinutes=$OffsetMinutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-QuantumFastSummary{param($Paths);Write-QuantumFastFile $Paths.Summary "QuantumFastSim complete.`nSource: $script:QuantumFastUrl`nThe 224-minute time-to-ransom sequence is preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo ISO mount, malware, task, injection, credential/LSASS access, directory query/archive, authentication, WMI/RDP/SMB/PsExec remote action, ransomware execution, file encryption, shadow/log/security change, IOC contact, or exfiltration occurred." 'operator summary'}
