#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:ShId='099-ShaiHulud_AICodingAssistant_SupplyChain';$script:ShUrl='https://cloud.google.com/security/resources/ai-risk-and-resilience-2026';$script:ShAnchor=(Get-Date).ToUniversalTime().AddMinutes(-120)
function Get-ShPaths{$r=Join-Path $env:PUBLIC 'ShaiHuludSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Repos=Join-Path $r 'generated-repos';Creds=Join-Path $r 'generated-credentials';Registry=Join-Path $r 'generated-registry';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.ShaiHuludSim.owner'}}
function Assert-ShSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated, disposable lab VM.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-ShManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-ShPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:ShId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-ShEnvironment{$p=Get-ShPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:ShId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Evidence,$p.Repos,$p.Creds,$p.Registry)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:ShId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};Add-ShManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-ShFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-ShManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Write-ShJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-ShFile $Path ($Object|ConvertTo-Json -Depth 15) $Purpose}
function New-ShDecoy{param([string]$Path,[string]$Role);New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-ShManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Invoke-ShDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','SHAIHULUD-LAB-CANARY');$q=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -NoNewWindow;$null=$q.ExitCode;Add-ShManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-ShLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-ShManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-ShTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-ShPaths;[ordered]@{timestampUtc=$script:ShAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-ShSummary{param($p);Write-ShFile $p.Summary "ShaiHuludSim complete.`nSource: $script:ShUrl (Mandiant AI Risk and Resilience 2026, Case Study 1: 'Weaponizing active developer AI sessions to deploy the Shai-Hulud worm').`nRepresents an AI-supply-chain intrusion: a hijacked active AI coding-assistant session, an AI-recommended poisoned dependency, an infostealer delivered via a poisoned PyPI package, GitHub OAuth token harvesting, the self-propagating Shai-Hulud worm across generated internal repositories, repository-secret theft, source-code exfiltration, and a poisoned internal-namespace package causing a downstream secondary infection.`nNo real package was installed, no real token/secret/source was read or collected, no repository was contacted, and nothing was exfiltrated. Every credential value is a [NOT COLLECTED] canary and every network action is 127.0.0.1 with zero bytes.`nArtifacts remain for investigation; cleanup is separate." summary}
