#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BeeRound2Sim-utilities.ps1";Assert-BeeRound2Safety -LabConfirmed:$LabConfirmed;$p=Initialize-BeeRound2Environment
$imaging=Join-Path $p.Payloads 'ImagingDevices.exe';$wabmig=Join-Path $p.Payloads 'wabmig.exe';New-BeeRound2Decoy $imaging 'WmiPrvSE-spawned Meterpreter stand-in';New-BeeRound2Decoy $wabmig 'Meterpreter and Cobalt host stand-in';Invoke-BeeRound2Decoy $imaging 'WmiPrvSE.exe -> ImagingDevices.exe; BumbleBee CreateRemoteThread Meterpreter injection' 'WmiPrvSE.exe';Invoke-BeeRound2Decoy $wabmig 'WmiPrvSE.exe -> wabmig.exe; Meterpreter and Cobalt injection' 'WmiPrvSE.exe';foreach($t in @('3.85.198.66:443 Meterpreter','50.16.62.87:443 Meterpreter','fuvataren.com / 45.153.243.142:443 Cobalt Strike')){Invoke-BeeRound2Loopback 443 $t 'C2 marker'}
$commands=@('ipconfig /all','ping -n 1 LAB.DOMAIN','nltest /dclist:','nltest /domain_trusts','net group "domain admins" /domain','net user /dom','tasklist /v /s LAB-WS02');foreach($c in $commands){Invoke-BeeRound2Decoy $wabmig $c 'Meterpreter/Cobalt';Add-BeeRound2Manifest discovery-command 'generated-commandline-only' represented @{reportedCommandLine=$c;executedDiscovery=$false}}
Write-BeeRound2File(Join-Path $p.Payloads 'af.exe')'INERT ADFIND-NAME CANARY. Not a PE file.''AdFind canary';foreach($c in @('af.exe -f objectcategory=person','af.exe -f objectcategory=computer','af.exe -f objectcategory=organizationalUnit','af.exe -sc trustdmp','af.exe -subnets -f objectCategory=subnet','af.exe -f objectcategory=group')){Invoke-BeeRound2Decoy $wabmig $c 'Cobalt'};foreach($n in @('ad_users.txt','ad_computers.txt','ad_ous.txt','trustdmp.txt','subnets.txt','ad_group.txt')){Write-BeeRound2File(Join-Path $p.Staging $n)"GENERATED ADFIND OUTPUT $n. No directory query occurred."'generated discovery canary'}
$procdump=Join-Path $p.Payloads 'procdump64.exe';New-BeeRound2Decoy $procdump 'Remote ProcDump stand-in';Invoke-BeeRound2Decoy $procdump 'remote service: procdump64.exe -accepteula -ma lsass.exe C:\ProgramData\lsass.dmp' 'services.exe';Write-BeeRound2File(Join-Path $p.Staging 'lsass.dmp')'GENERATED DUMP-NAME CANARY. Contains no memory, credentials, or secrets.''credential canary';Write-BeeRound2File(Join-Path $p.Staging 'lsass.zip')'INERT ZIP-NAME CANARY. No archive was created.''archive canary'
$negative=@{reportedInjectionTargets=@('ImagingDevices.exe','wabmig.exe','rundll32.exe');processesInjected=0;namedPipesReported=@('postex_515f','postex_7c7b');namedPipesCreated=0;remoteServicesCreated=0;LSASSAccessed=$false;credentialsCollected=0;SMBCopies=0;archivesCreated=0;bytesExfiltrated=0};Write-BeeRound2File(Join-Path $p.Evidence 'injection-credential-negative-record.json')($negative|ConvertTo-Json -Depth 6)'credential safety record'
Add-BeeRound2Timeline .25 execution 'WMI-spawned ImagingDevices/wabmig Meterpreter injections represented' @{processesInjected=0;techniques=@('T1055','T1036')};Add-BeeRound2Timeline 6 execution 'Cobalt beacon joins wabmig and repeats discovery including net user /dom' @{beaconExecuted=$false};Add-BeeRound2Timeline 6.5 credential-access 'Remote service ProcDump LSASS, C$ copy, and 7-Zip staging represented' @{remoteHostsTouched=0;credentialsCollected=0;archivesCreated=0;techniques=@('T1003.001','T1560.001')};Add-BeeRound2Timeline 7 discovery 'Renamed AdFind user/computer/OU/trust/subnet/group enumeration represented' @{directoryQueries=0}
