#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:BeeRound2Id='044-BumbleBee_Meterpreter_Cobalt_RDP_PreRansomware';$script:BeeRound2Url='https://thedfirreport.com/2022/09/26/bumblebee-round-two/';$script:BeeRound2Anchor=(Get-Date).ToUniversalTime().AddHours(-12)
function Get-BeeRound2Paths{$r=Join-Path $env:PUBLIC 'BeeRound2Sim';[ordered]@{Root=$r;Lure=Join-Path $r 'iso-lure';Beach=Join-Path $r 'BEACHHEAD';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.BeeRound2Sim.owner'}}
function Assert-BeeRound2Safety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-BeeRound2Manifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-BeeRound2Paths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:BeeRound2Id;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-BeeRound2Environment{$p=Get-BeeRound2Paths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:BeeRound2Id){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beach,$p.Payloads,$p.Staging,$p.Hosts,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:BeeRound2Id -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-BeeRound2Manifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-BeeRound2File{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-BeeRound2Manifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-BeeRound2Decoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-BeeRound2Manifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-BeeRound2Decoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='explorer.exe');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','BEE-ROUND2-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-BeeRound2Manifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-BeeRound2Loopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-BeeRound2Manifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-BeeRound2Timeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-BeeRound2Paths;[ordered]@{timestampUtc=$script:BeeRound2Anchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-BeeRound2Summary{param($Paths);Write-BeeRound2File $Paths.Summary "BeeRound2Sim complete.`nSource: $script:BeeRound2Url`nThe source does not publish an exact total intrusion duration; relative event spacing is preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo ISO mount, malware, injection, credential access, account/service change, remote action, real collection/archive/exfiltration, backup or mail access, IOC contact, or impact occurred." 'operator summary'}
