Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:EggId='019-Egg_Cellent_Resume_MoreEggs_Pyramid';$script:EggUrl='https://thedfirreport.com/2024/12/02/the-curious-case-of-an-egg-cellent-resume/';$script:EggAnchor=(Get-Date).ToUniversalTime()
function Get-EggPaths{$r=Join-Path $env:PUBLIC 'EggCellentResumeSim';[ordered]@{Root=$r;Evidence=Join-Path $r 'evidence';Beachhead=Join-Path $r 'hosts\WORKSTATION01';Backup=Join-Path $r 'hosts\BACKUP01';Management=Join-Path $r 'hosts\MGMT01';ProgramData=Join-Path $r 'hosts\WORKSTATION01\ProgramData';User=Join-Path $r 'hosts\WORKSTATION01\Users\Recruiter';SyntheticShares=Join-Path $r 'synthetic-shares';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\campaign-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.EggCellentResumeSim.owner'}}
function Get-EggTime{$i=$script:EggAnchor.AddHours(-60);[ordered]@{Initial=$i;Discovery=$i.AddMinutes(10);MoreEggs=$i.AddMinutes(3);Cobalt=$i.AddHours(36);Veeam=$i.AddHours(39);Cloudflared=$i.AddHours(42);NetScan=$i.AddHours(44);Eviction=$i.AddHours(60)}}
function Assert-EggSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-EggManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-EggPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:EggId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 8 -Compress|Add-Content $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-EggEnvironment{$p=Get-EggPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:EggId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Evidence,$p.Beachhead,$p.Backup,$p.Management,$p.ProgramData,$p.User,$p.SyntheticShares)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:EggId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-EggManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return $p}
function Write-EggFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact',[datetime]$Timestamp=$script:EggAnchor);$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;$i=Get-Item $Path -Force;$i.CreationTimeUtc=$Timestamp.ToUniversalTime();$i.LastWriteTimeUtc=$Timestamp.ToUniversalTime().AddMinutes(1);Add-EggManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-EggDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-EggManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;hashMatchExpected=$false}}
function Invoke-EggDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$s=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','EGG-CANARY',$s);$p=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -NoNewWindow;$null=$p.ExitCode;Add-EggManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');escaped=$true}}
function Invoke-EggLoopback{param([int]$Port,[string]$ReportedTarget);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-EggManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;remote=$false;proxy=$false}}
function Add-EggTimeline{param([datetime]$Timestamp,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-EggPaths;[ordered]@{timestampUtc=$Timestamp.ToUniversalTime().ToString('o');phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 7 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-EggSummary{param($Paths);Write-EggFile $Paths.Summary "EggCellentResumeSim complete.`nSource: $script:EggUrl`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo live malware, IOC, credential source, LSASS, shadow, account, domain, service, tunnel, or remote system was accessed." 'operator summary'}
