function Invoke-EggCobaltPyramidDiscovery{param($Paths);$t=Get-EggTime
$ocx=Join-Path $Paths.ProgramData '31765.ocx';New-EggDecoy $ocx 'Cobalt Strike OCX filename canary' '408f1f982bef7ab5a79057eec4079e5e8d87a0ee83361c79469018b791c03e8f';Invoke-EggDecoy $ocx 'regsvr32.exe /s /n /i C:\ProgramData\31765.ocx';Invoke-EggLoopback 443 'shehasgone.com / 144.208.127.15 Cobalt Strike'
Write-EggFile(Join-Path $Paths.Evidence 'cobalt-strike.json')(@{server='shehasgone.com';ip='144.208.127.15';uri='/wp-includes/lu.png';license=2073085114;hostHeader='bing.com';namedPipes=@('\postex_18ab','\postex_77cb');pipesCreated=$false;beaconIncluded=$false}|ConvertTo-Json -Depth 5) 'partial Cobalt profile and pipe metadata' $t.Cobalt
foreach($c in @('vssadmin list shadows','vssadmin create shadow /for=C:','cmd /c vssadmin create shadow /for=C:','query session','nslookup','ping -n 1 LAB.INVALID','net usre CANARY /dom','net user CANARY /dom')){Invoke-EggDecoy(Join-Path $env:SystemRoot 'System32\cmd.exe')$c}
Write-EggFile(Join-Path $Paths.Evidence 'shadow-copy-canary.json')(@{reportedCommands=@('vssadmin list shadows','vssadmin create shadow /for=C:');shadowCreated=$false;shadowAccessed=$false;samAccessed=$false}|ConvertTo-Json) 'non-executed shadow-copy metadata' $t.Cobalt
Write-EggFile(Join-Path $Paths.ProgramData 'shares.txt')'\\FILE01\Finance`n\\BACKUP01\Backups`nGenerated shares only' 'SharpShares output canary' $t.Cobalt;Write-EggFile(Join-Path $Paths.ProgramData 'seatinfo.txt')'Seatbelt generated discovery output; no system/credential/browser collection' 'Seatbelt output canary' $t.Cobalt;Write-EggFile(Join-Path $Paths.User 'AppData\Local\Microsoft\CLR_v4.0\UsageLogs\rundll32.exe.log')'EventID 153 modules: Seatbelt, SharpShares (synthetic)' 'CLR usage-log canary' $t.Cobalt
foreach($c in @('adfind.exe -f "(objectcategory=person)"','adfind.exe -f "objectcategory=computer"','adfind.exe -subnets -f "(objectCategory=subnet)"')){Invoke-EggDecoy(Join-Path $env:SystemRoot 'System32\cmd.exe')$c}
$net=Join-Path $Paths.ProgramData 'scaner\scaner\netscan.exe';New-EggDecoy $net 'SoftPerfect NetScan name canary' 'a8a7fdbbc688029c0d97bf836da9ece926a85e78986d0e1ebd9b3467b3a72258';Invoke-EggDecoy $net 'netscan.exe 127.0.0.1 (reported ping sweep and saved victim scans)';foreach($p in @(88,135,139,389,445,3389)){Invoke-EggLoopback $p 'synthetic network scan'}
$ssh=Join-Path $Paths.ProgramData 'SSH';Write-EggFile(Join-Path $ssh 'python-3.10.4-embed-amd64.zip')'PK EGG PYRAMID CANARY; no Python or exploit code' 'masqueraded Python/Pyramid archive' $t.Cobalt;1..24|%{Write-EggFile(Join-Path $ssh("pyramid-canary-{0:d3}.py"-f$_))'# inert extraction-sprawl canary' 'Python file-creation evidence' $t.Cobalt};Write-EggFile(Join-Path $ssh 'cradle.py')'# Pyramid configuration is stored in evidence JSON; no imports or networking' 'inert Pyramid cradle' $t.Cobalt
Write-EggFile(Join-Path $Paths.Evidence 'pyramid-config.json')(@{server='172.96.139.82';port=80;user='fLCi6UsgLYKdj7Fi';password='Q6V26bKG68nLJ4T3UXkEFLJYsHvKgLVi';encryption='chacha20';encryptionPass='TestPass1';iv='12345678';uri='/login/';module='base-bof_nanodump.py';actual='127.0.0.1';connected=$false}|ConvertTo-Json -Depth 5) 'published Pyramid configuration metadata' $t.Cobalt;Invoke-EggLoopback 80 '172.96.139.82 Pyramid C2'
Add-EggTimeline $t.Cobalt 'C2/Credential Access/Discovery' 'Cobalt Strike, shadow-copy attempts, CLR discovery modules, NetScan, and Pyramid extraction sprawl were reproduced as canaries.' @{shadowCreated=$false;domainQueried=$false;remoteC2=$false;pythonExecuted=$false}}
