#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:IceColdId='026-OneNote_IcedID_CobaltStrike_AnyDesk_Nokoyawa';$script:IceColdUrl='https://thedfirreport.com/2024/04/01/from-onenote-to-ransomnote-an-ice-cold-intrusion/';$script:IceColdAnchor=(Get-Date).ToUniversalTime().AddHours(-812)
function Get-IceColdPaths{$r=Join-Path $env:PUBLIC 'OneNoteIceColdSim';[ordered]@{Root=$r;Lure=Join-Path $r 'email-onenote-lure';Beachhead=Join-Path $r 'beachhead';Evidence=Join-Path $r 'evidence';Hosts=Join-Path $r 'generated-hosts';Shares=Join-Path $r 'generated-shares';Exfil=Join-Path $r 'filezilla-staging';Impact=Join-Path $r 'impact-canary';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.OneNoteIceColdSim.owner'}}
function Assert-IceColdSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-IceColdManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-IceColdPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:IceColdId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8}
function Initialize-IceColdEnvironment{$p=Get-IceColdPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:IceColdId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beachhead,$p.Evidence,$p.Hosts,$p.Shares,$p.Exfil,$p.Impact)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:IceColdId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-IceColdManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-IceColdFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-IceColdManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-IceColdDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-IceColdManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;match=$false}}
function Invoke-IceColdDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$s=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','ICE-COLD-CANARY',$s);$x=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$x.ExitCode;Add-IceColdManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');escaped=$true}}
function Invoke-IceColdLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-IceColdManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-IceColdTimeline{param([int]$OffsetMinutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-IceColdPaths;[ordered]@{timestampUtc=$script:IceColdAnchor.AddMinutes($OffsetMinutes).ToString('o');offsetMinutes=$OffsetMinutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-IceColdSummary{param($Paths);Write-IceColdFile $Paths.Summary "OneNoteIceColdSim complete.`nSource: $script:IceColdUrl`nSimulated dwell: 812 hours over just more than 34 days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo live malware, real IOC connection, LSASS/credential access, remote movement, RMM installation, user-data collection, exfiltration, software removal, shadow deletion, or encryption occurred." 'operator summary'}
