#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:H17Id='088-Nonstandard_RDP_Scanner_Harma_17m';$script:H17Url='https://thedfirreport.com/2020/07/13/ransomware-again-but-we-changed-the-rdp-port/';$script:H17Anchor=(Get-Date).ToUniversalTime().AddMinutes(-17)
function Get-H17Paths{$root=Join-Path $env:PUBLIC 'Harma17Sim';[ordered]@{Root=$root;Payloads=Join-Path $root 'payload-canaries';Evidence=Join-Path $root 'evidence';Hosts=Join-Path $root 'generated-hosts';Manifest=Join-Path $root 'artifact-manifest.jsonl';Timeline=Join-Path $root 'evidence\exercise-timeline.jsonl';Summary=Join-Path $root 'operator-summary.txt';Owner=Join-Path $root '.Harma17Sim.owner'}}
function Assert-H17Safety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$system=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$system.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-H17Manifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-H17Paths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:H17Id;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-H17Environment{$p=Get-H17Paths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:H17Id){throw 'Refusing unowned root'}};foreach($directory in @($p.Root,$p.Payloads,$p.Evidence,$p.Hosts)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:H17Id -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-H17Manifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-H17File{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$directory=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $directory)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-H17Manifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Write-H17Json{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-H17File -Path $Path -Content($Object|ConvertTo-Json -Depth 12)-Purpose $Purpose}
function New-H17Decoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-H17Manifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-H17Decoy{param([string]$FilePath,[string]$Reported,[string]$Parent,[string]$Label='HARMA-17-CANARY');$arguments=@('/d','/v:off','/c','echo',$Label);$process=Start-Process -FilePath $FilePath -ArgumentList $arguments -PassThru -Wait -WindowStyle Hidden;$null=$process.ExitCode;Add-H17Manifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($arguments-join' ');reportedOnly=$true}}
function Invoke-H17Loopback{param([int]$Port,[string]$Target,[string]$Role);$client=New-Object Net.Sockets.TcpClient;try{$pending=$client.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$pending.AsyncWaitHandle.WaitOne(500)}catch{}finally{$client.Dispose()};Add-H17Manifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-H17Timeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-H17Paths;[ordered]@{timestampUtc=$script:H17Anchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function New-H17HostTree{param([string]$Name,[string]$Role);$p=Get-H17Paths;$hostRoot=Join-Path $p.Hosts $Name;foreach($directory in @('C$\Desktop','C$\Finance','C$\ProgramData')){New-Item -Path(Join-Path $hostRoot $directory)-ItemType Directory -Force|Out-Null};Write-H17Json -Path(Join-Path $hostRoot 'host-profile.json')-Object([ordered]@{hostname=$Name;role=$Role;generated=$true;remoteSystem=$false})-Purpose generated-host;Write-H17File -Path(Join-Path $hostRoot 'C$\Finance\ledger.xlsx.canary')-Content "INERT GENERATED DATA FOR $Name. This is not user data." -Purpose generated-canary-data;$hostRoot}
function Write-H17Summary{param($Paths);Write-H17File -Path $Paths.Summary -Content "Harma17Sim complete.`nSource: $script:H17Url`nInternal case: 1001`nThe report's exact 17-minute UTC sequence is preserved.`nArtifacts remain; cleanup is separate.`nNo authentication, RDP, network scanning, Task Manager inspection, remote movement, startup persistence, malware, DC action, or encryption occurred." -Purpose summary}
