#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:ProxyEncryptId='060-ProxyShell_Plink_FRP_BitLocker_DiskCryptor_42h';$script:ProxyEncryptUrl='https://thedfirreport.com/2021/11/15/exchange-exploit-leads-to-domain-wide-ransomware/';$script:ProxyEncryptAnchor=(Get-Date).ToUniversalTime().AddHours(-42)
function Get-ProxyEncryptPaths{$r=Join-Path $env:PUBLIC 'ProxyEncryptSim';[ordered]@{Root=$r;Exchange=Join-Path $r 'generated-exchange-host';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Staging=Join-Path $r 'staging-canaries';Impact=Join-Path $r 'impact-canaries';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.ProxyEncryptSim.owner'}}
function Assert-ProxyEncryptSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-ProxyEncryptManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-ProxyEncryptPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:ProxyEncryptId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-ProxyEncryptEnvironment{$p=Get-ProxyEncryptPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:ProxyEncryptId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Exchange,$p.Payloads,$p.Hosts,$p.Staging,$p.Impact,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:ProxyEncryptId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-ProxyEncryptManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedDcCanaryOnly=$true};$p}
function Write-ProxyEncryptFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-ProxyEncryptManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-ProxyEncryptDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-ProxyEncryptManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-ProxyEncryptDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='w3wp.exe');$args=@('/d','/v:off','/c','echo','PROXY-ENCRYPT-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-ProxyEncryptManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-ProxyEncryptLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-ProxyEncryptManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-ProxyEncryptTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-ProxyEncryptPaths;[ordered]@{timestampUtc=$script:ProxyEncryptAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-ProxyEncryptSummary{param($Paths);Write-ProxyEncryptFile $Paths.Summary "ProxyEncryptSim complete.`nSource: $script:ProxyEncryptUrl`nThe three-day/42-hour ProxyShell-to-impact chronology and generated DC evidence lane are preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo Exchange cmdlet/mailbox operation, web shell, account/group change, task/service, remote action, scan, RDP/WMI, credential/LSASS access, collection/exfiltration, security/log impairment, registry/firewall/feature/TPM/boot change, reboot, malware, driver, BitLocker, DiskCryptor, deletion, or encryption occurred." 'operator summary'}
