#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:DDId='087-Dridex_Empire_AdFind_PsExec_Domain'
$script:DDUrl='https://thedfirreport.com/2020/08/03/dridex-from-word-to-domain-dominance/'
$script:DDAnchor=(Get-Date).ToUniversalTime().AddMinutes(-480)
function Get-DDPaths{$root=Join-Path $env:PUBLIC 'DridexDomainSim';[ordered]@{Root=$root;Payloads=Join-Path $root 'payload-canaries';Evidence=Join-Path $root 'evidence';Hosts=Join-Path $root 'generated-hosts';Staging=Join-Path $root 'staging';Manifest=Join-Path $root 'artifact-manifest.jsonl';Timeline=Join-Path $root 'evidence\exercise-timeline.jsonl';Summary=Join-Path $root 'operator-summary.txt';Owner=Join-Path $root '.DridexDomainSim.owner'}}
function Assert-DDSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$system=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$system.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-DDManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-DDPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:DDId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-DDEnvironment{$p=Get-DDPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:DDId){throw 'Refusing unowned root'}};foreach($directory in @($p.Root,$p.Payloads,$p.Evidence,$p.Hosts,$p.Staging)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:DDId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-DDManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-DDFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$directory=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $directory)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-DDManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Write-DDJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-DDFile -Path $Path -Content($Object|ConvertTo-Json -Depth 12)-Purpose $Purpose}
function New-DDDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-DDManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-DDDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent,[string]$Label='DRIDEX-DOMAIN-CANARY');$arguments=@('/d','/v:off','/c','echo',$Label);$process=Start-Process -FilePath $FilePath -ArgumentList $arguments -PassThru -Wait -NoNewWindow;$null=$process.ExitCode;Add-DDManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($arguments-join' ');reportedOnly=$true}}
function Invoke-DDLoopback{param([int]$Port,[string]$Target,[string]$Role);$client=New-Object Net.Sockets.TcpClient;try{$pending=$client.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$pending.AsyncWaitHandle.WaitOne(500)}catch{}finally{$client.Dispose()};Add-DDManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-DDTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-DDPaths;[ordered]@{timestampUtc=$script:DDAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function New-DDHostTree{param([string]$Name,[string]$Role);$p=Get-DDPaths;$hostRoot=Join-Path $p.Hosts $Name;foreach($directory in @('C$\Users\Public','C$\Windows','ADMIN$')){New-Item -Path(Join-Path $hostRoot $directory)-ItemType Directory -Force|Out-Null};Write-DDJson -Path(Join-Path $hostRoot 'host-profile.json')-Object([ordered]@{hostname=$Name;role=$Role;generated=$true;remoteSystem=$false})-Purpose generated-host;$hostRoot}
function Write-DDSummary{param($Paths);Write-DDFile -Path $Paths.Summary -Content "DridexDomainSim complete.`nSource: $script:DDUrl`nInternal case: 1002`nA generated eight-hour axis preserves sequence because the report provides relative timing but no total duration.`nArtifacts remain; cleanup is separate.`nThe scenario ends with failed credential-dump metadata and continuing Dridex access, matching the report; no ransomware objective is invented.`nNo macro, malware, external connection, download, task/Run-key change, WMI, PsExec/service/SMB action, remote execution, LSASS access, credential collection, or security-control change occurred." -Purpose summary}
