#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\DridexDomainSim-utilities.ps1";Assert-DDSafety -LabConfirmed:$LabConfirmed;$p=Initialize-DDEnvironment
$roles=[ordered]@{'DC01-CANARY'='generated domain-controller representation';'WS01-CANARY'='workstation';'WS02-CANARY'='workstation';'APP01-CANARY'='application server'}
foreach($entry in $roles.GetEnumerator()){$null=New-DDHostTree -Name $entry.Key -Role $entry.Value}
$ufo=Join-Path $p.Payloads 'ufo.exe';$bin=Join-Path $p.Payloads '123.bin';$marple=Join-Path $p.Payloads 'marple.exe';$pse=Join-Path $p.Payloads 'pse.exe';$wmic=Join-Path $p.Payloads 'wmic.exe'
foreach($item in @(@($ufo,'Dridex propagation payload stand-in','5761fd8b454c1121f80019ade53b0815bd0573dac89fe6ecd3198e7d756f1a3a'),@($bin,'open-directory binary stand-in','e88dfd4bef8c502ef2b711fd025aa321244dbca1eab80586b07187b3cf261de3'),@($marple,'open-directory binary stand-in','cb81e371e2a4d3371e051b1f15674ce6cb94e257d28ddc1a5209bb56c71dd27a'),@($pse,'renamed PsExec stand-in',''),@($wmic,'WMI telemetry stand-in',''))){New-DDDecoy -Path $item[0] -Role $item[1] -PublishedSha256 $item[2]}
Write-DDFile -Path(Join-Path $p.Payloads 'module.php')-Content '<?php /* INERT MODULE.PHP-NAME CANARY. No webshell or executable logic. */ ?>' -Purpose payload-canary
Write-DDFile -Path(Join-Path $p.Staging 'a.txt')-Content "DC01-CANARY`nWS01-CANARY`nWS02-CANARY`nAPP01-CANARY" -Purpose synthetic-target-list
Write-DDJson -Path(Join-Path $p.Evidence 'open-directory-inventory.json')-Object([ordered]@{reportedFiles=@('123.bin','a.txt','ufo.exe','marple.exe','module.php');reportedTargetCount='800+ hostnames in a.txt';reportedProperties=@('module.php password-protected webshell','marple/123 invalid debug info and contradictory timestamps','ufo/123 near-identical except timestamps','anti-VM and anti-debugging instructions');retrievedFromInternet=0;webshellCodePresent=$false;syntheticTargets=4})-Purpose collection
Invoke-DDDecoy -FilePath $wmic -Reported 'Empire launched via WMI on all domain-joined systems; some attempts blocked by Defender' -Parent 'Empire shell on entry host' -Label 'NO-WMI'
$pseCommand='pse.exe -accepteula @a.txt -c -f -d -s ufo.exe > log.txt'
Invoke-DDDecoy -FilePath $pse -Reported $pseCommand -Parent 'Empire/Dridex operator on compromised DC' -Label 'NO-PSEXEC'
Write-DDFile -Path(Join-Path $p.Staging 'log.txt')-Content "SYNTHETIC PSEXEC LOG`nStarting PSEXESVC service on WS01-CANARY... NOT PERFORMED`nConnecting with PsExec service... NOT PERFORMED`nCopying ufo.exe... NOT PERFORMED`nStarting ufo.exe... NOT PERFORMED" -Purpose synthetic-psexec-log
Write-DDJson -Path(Join-Path $p.Evidence 'propagation.json')-Object([ordered]@{reportedWmiScope='all domain-joined systems';reportedDefenderBlocks='some machines';reportedPseCommand=$pseCommand;reportedMechanism='PSEXESVC copied via ADMIN$ and executed as SYSTEM';WmiCalls=0;DefenderEventsGenerated=0;securityControlsChanged=0;smbSessions=0;psexecServicesCreated=0;remoteFilesWritten=0;remoteProcesses=0;SystemTokensUsed=0;syntheticLog=(Join-Path $p.Staging 'log.txt')})-Purpose lateral-movement
foreach($target in @('59.148.253.194:443','2.58.16.87:8443')){Invoke-DDLoopback -Port([int]$target.Split(':')[-1])-Target $target -Role 'ufo/Dridex C2 marker'}
Write-DDJson -Path(Join-Path $p.Evidence 'credential-and-objective-outcome.json')-Object([ordered]@{reportedCredentialDumpAttempts='multiple attempts from a DC';reportedResult='failed';lsassHandlesOpened=0;processMemoryReadBytes=0;dumpFilesCreated=0;credentialsOrHashesCollected=0;reportedEmpireConnection='dropped';reportedDridexAccess='continued beaconing from compromised hosts';observedFinalObjective='none';hypothesizedObjective='domain-wide ransomware';ransomwareSimulated=$false})-Purpose outcome
Add-DDTimeline 220 lateral-movement 'Empire WMI attempts across domain-joined systems represented; Defender blocks preserved as metadata' @{WmiCalls=0;securityControlsChanged=0}
Add-DDTimeline 260 lateral-movement 'Renamed PsExec pse.exe, target list, PSEXESVC, and ufo execution represented' @{psexecServicesCreated=0;remoteFilesWritten=0;remoteProcesses=0}
Add-DDTimeline 300 command-and-control 'Additional Dridex beacon endpoints from generated hosts represented' @{externalConnections=0;bytesTransferred=0}
Add-DDTimeline 360 credential-access 'Repeated credential-dump attempts on DC represented as failed' @{lsassHandlesOpened=0;credentialsOrHashesCollected=0}
Add-DDTimeline 480 outcome 'Empire connection dropped; Dridex access persisted; no observed final objective' @{ransomwareSimulated=$false;userFilesChanged=0}
Write-DDJson -Path(Join-Path $p.Evidence 'phase3-negative.json')-Object([ordered]@{WmiCalls=0;smbSessions=0;psexecServicesCreated=0;remoteFilesWritten=0;remoteProcesses=0;SystemTokensUsed=0;securityControlsChanged=0;lsassHandlesOpened=0;processMemoryReadBytes=0;dumpFilesCreated=0;credentialsOrHashesCollected=0;externalConnections=0;bytesTransferred=0;ransomwareSimulated=$false;userFilesChanged=0})-Purpose safety
