#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\NetSupportDomainSim-utilities.ps1";Assert-NSDomainSafety -LabConfirmed:$LabConfirmed;$p=Initialize-NSDomainEnvironment
$cmd=Join-Path $p.Beach 'cmd.exe';if(-not(Test-Path $cmd)){New-NSDomainDecoy $cmd 'hands-on command stand-in'}
$discovery=@('whoami','net user','net user /domain','whoami /all','net group Domain Admins /domain','systeminfo','cmdkey /list','nltest /dclist:LAB','net view LAB.local/SYSVOL','tasklist','find ssh','ping generated DCs','arp -a');foreach($c in $discovery){Invoke-NSDomainDecoy $cmd $c}
Write-NSDomainFile(Join-Path $p.Payloads 'install.bat')'@REM INERT OpenSSH installation/tunnel canary. No commands.''OpenSSH canary';$ssh=[ordered]@{tasks=@('SSH Server','SSH Key Exchange');listenPort=2222;reverseMapping='369:127.0.0.1:2222';reportedVps='185.206.146.129';tasksCreated=0;serverInstalled=$false;keyGenerated=$false;tunnelCreated=$false};Write-NSDomainFile(Join-Path $p.Evidence 'openssh-negative-record.json')($ssh|ConvertTo-Json)'SSH evidence';Invoke-NSDomainLoopback 2222 'local OpenSSH listener' 'SSH marker';Invoke-NSDomainLoopback 22 '185.206.146.129 reverse tunnel' 'SSH marker'
foreach($hostName in @('DC-01','DC-02','FILE-01','BACKUP-01')){New-Item(Join-Path $p.Hosts $hostName)-ItemType Directory -Force|Out-Null};Write-NSDomainFile(Join-Path $p.Payloads 'cache.cab')'INERT CAB-NAME CANARY. Not an archive.''lateral transfer canary';$mswow=Join-Path $p.Payloads 'ProgramData\schcache\mswow86.exe';New-NSDomainDecoy $mswow 'remote NetSupport filename canary' '4d24b359176389301c14a92607b5c26b8490c41e7e3a2abbc87510d1376f4a87';Invoke-NSDomainDecoy $cmd 'wmiexec/atexec -> expand cache.cab -> mswow86.exe -> Wow64 Subsystem task'
$lateral=[ordered]@{firewallRulesCreated=0;atexec=$false;wmiexec=$false;smbWrites=0;cabExpanded=$false;scheduledTasksCreated=0;remoteHostsTouched=0;rdpSessions=0;reportedAttackerHosts=@('DESKTOP-TBDQ6K1','WIN-5ODCFIGQRP3');accountActivationAttempt=$false;sysvolQueried=$false};Write-NSDomainFile(Join-Path $p.Evidence 'lateral-negative-record.json')($lateral|ConvertTo-Json -Depth 5)'lateral movement evidence';foreach($t in @('wsus-isv-local.tech:133 -> 79.137.206.37','wsus-isv-internal.tech:133 -> NXDOMAIN')){Invoke-NSDomainLoopback 133 $t 'NetSupport marker'}
Add-NSDomainTimeline 120 discovery 'Day-five NetSupport hands-on discovery and failed privileged-account activation represented' @{directoryQueries=0};Add-NSDomainTimeline 124 persistence 'OpenSSH listener and reverse-tunnel tasks represented' @{tasksCreated=0;tunnel=$false;techniques=@('T1053.005','T1572','T1090')};Add-NSDomainTimeline 132 lateral-movement 'Impacket, firewall, SMB CAB, WMI, remote NetSupport, and RDP represented' @{remoteConnections=0;techniques=@('T1047','T1021.001','T1021.002','T1570','T1036.004')}
