#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\NetSupportDomainSim-utilities.ps1";Assert-NSDomainSafety -LabConfirmed:$LabConfirmed;$p=Initialize-NSDomainEnvironment
Write-NSDomainFile(Join-Path $p.Lure 'delivery.zip')'INERT EMAIL ZIP CANARY. No archive members.''email lure';Write-NSDomainFile(Join-Path $p.Lure '2326.js')'INERT JAVASCRIPT CANARY. No script statements.''JavaScript lure'
$wscript=Join-Path $p.Beach 'wscript.exe';New-NSDomainDecoy $wscript 'JavaScript/PowerShell ancestry stand-in';Invoke-NSDomainDecoy $wscript '2326.js -> cmd.exe -> encoded PowerShell -> 1otal.com/index/index.php'
$folder=Join-Path $p.Beach 'AppData\Roaming\eHNjqgzZ';foreach($name in @('presentationhost.exe','client32.ini','HTCTL32.DLL','msvcr100.dll','nskbfltr.inf','NSM.ini','NSM.lic','pcicapi.dll','PCICHEK.DLL','PCICL32.DLL','remcmdstub.exe','TCCTL32.DLL')){if($name-like'*.exe'){New-NSDomainDecoy(Join-Path $folder $name)"NetSupport component $name"}else{Write-NSDomainFile(Join-Path $folder $name)"INERT NETSUPPORT COMPONENT CANARY: $name"'NetSupport component canary'}}
$deploy=[ordered]@{antiSandboxNames=@('avast','avg','sample','analysis','malware','sandbox','virus');source='1otal.com/index/index.php';runKey='HKCU\Software\Microsoft\Windows\CurrentVersion\Run\SoftwareUpdater';runKeyWritten=$false;netSupportStarted=$false;filesRemoved=$false};Write-NSDomainFile(Join-Path $p.Evidence 'deployment-negative-record.json')($deploy|ConvertTo-Json -Depth 5)'deployment evidence';foreach($t in @('npinmclaugh11.com:2145 -> 127.0.0.127','npinmclaugh14.com:2145 -> 89.185.85.44')){Invoke-NSDomainLoopback 2145 $t 'NetSupport marker'}
Add-NSDomainTimeline 0 initial-access 'ZIP, 2326.js, encoded PowerShell, and 12 NetSupport components represented' @{malwareExecuted=$false;techniques=@('T1204.002','T1059.007','T1059.001','T1027','T1140')};Add-NSDomainTimeline 1 persistence 'SoftwareUpdater run key and NetSupport C2 represented' @{registryWritten=$false;technique='T1547.001'}
