#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:NSDomainId='031-NetSupport_OpenSSH_Impacket_DomainCompromise';$script:NSDomainUrl='https://thedfirreport.com/2023/10/30/netsupport-intrusion-results-in-domain-compromise/';$script:NSDomainAnchor=(Get-Date).ToUniversalTime().AddDays(-8)
function Get-NSDomainPaths{$r=Join-Path $env:PUBLIC 'NetSupportDomainSim';[ordered]@{Root=$r;Lure=Join-Path $r 'email-lure';Beach=Join-Path $r 'BEACHHOST';Hosts=Join-Path $r 'generated-hosts';Payloads=Join-Path $r 'payload-canaries';Shares=Join-Path $r 'generated-shares';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.NetSupportDomainSim.owner'}}
function Assert-NSDomainSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-NSDomainManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-NSDomainPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:NSDomainId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-NSDomainEnvironment{$p=Get-NSDomainPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:NSDomainId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beach,$p.Hosts,$p.Payloads,$p.Shares,$p.Evidence)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:NSDomainId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-NSDomainManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-NSDomainFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-NSDomainManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-NSDomainDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-NSDomainManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;hashMatch=$false}}
function Invoke-NSDomainDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','NETSUPPORT-DOMAIN-CANARY',$safe);$proc=Start-Process $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-NSDomainManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-NSDomainLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-NSDomainManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-NSDomainTimeline{param([int]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-NSDomainPaths;[ordered]@{timestampUtc=$script:NSDomainAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-NSDomainSummary{param($Paths);Write-NSDomainFile $Paths.Summary "NetSupportDomainSim complete.`nSource: $script:NSDomainUrl`nSimulated dwell: eight days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malware, registry/task/service, SSH, account, firewall/Defender change, remote access, directory/SYSVOL query, NTDS/LSASS access, real document access, or exfiltration occurred." 'operator summary'}
