#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\NetSupportDomainSim-utilities.ps1";Assert-NSDomainSafety -LabConfirmed:$LabConfirmed;$p=Initialize-NSDomainEnvironment
$cmd=Join-Path $p.Beach 'cmd.exe';if(-not(Test-Path $cmd)){New-NSDomainDecoy $cmd 'hands-on command stand-in'}
Write-NSDomainFile(Join-Path $p.Hosts 'DC-01\ntds\ntds.dit.canary')'GENERATED NTDS-NAME CANARY. Contains no directory database, secrets, hashes, or accounts.''NTDS canary';Write-NSDomainFile(Join-Path $p.Hosts 'DC-02\ntdsutil\ntds.dit.canary')'GENERATED NTDS-NAME CANARY. No secrets.''NTDS canary';Write-NSDomainFile(Join-Path $p.Payloads 'ntds.bat')'@REM INERT ntdsutil evidence only.''NTDS batch canary'
$pingcastle=Join-Path $p.Payloads 'PingCastle.exe';New-NSDomainDecoy $pingcastle 'PingCastle filename canary' '768021fc242054decc280675750dec0a9e74e764b8646864c58756fa2386d2a2';$netscan=Join-Path $p.Payloads 'netscan64.exe';New-NSDomainDecoy $netscan 'SoftPerfect Network Scanner filename canary' '5ef9844903e8d596ac03cc000b69bbbe45249eea02d9678b38c07f49e4c1ec46';$mpms=Join-Path $p.Payloads 'mpms.exe';New-NSDomainDecoy $mpms 'renamed ProcDump filename canary';foreach($c in @('ntdsutil IFM create full on DC-01 and DC-02','7-Zip archive ntds and mf.txt','PingCastle --healthcheck --level Full','netscan.exe plus keygen','mpms.exe -accepteula -ma LSASS PID','Get-WinEvent Security EventID 4624 -> mf.txt','Get-MpThreat and Defender disable attempts')){Invoke-NSDomainDecoy $cmd $c}
Write-NSDomainFile(Join-Path $p.Shares 'Secretive\Strategic-Plan.docx')'GENERATED SENSITIVE-DOCUMENT CANARY. No real organizational data.''collection canary';Write-NSDomainFile(Join-Path $p.Hosts 'DC-01\mf.txt')'GENERATED EVENT-4624 MESSAGE CANARY. No real logons, users, or credentials.''event collection canary';Write-NSDomainFile(Join-Path $p.Hosts 'DC-01\staging.7z.canary')'ARCHIVE-NAME CANARY. No compressed NTDS, logs, or documents.''archive canary'
foreach($name in @('pth_addadmin.exe','pth_createuser.exe')){New-NSDomainDecoy(Join-Path $p.Payloads $name)"failed Nim backdoor-account tool $name"};$unsafe=[ordered]@{ntdsAccessed=$false;lsassAccessed=$false;realEventsRead=$false;defenderChanged=$false;pingCastleRun=$false;networkScan=$false;realSharesBrowsed=$false;archiveCreated=$false;exfiltrationObservedByReport='not observed; assessed medium confidence for NTDS';actualBytesTransferred=0;WDAGUtilityAccount2Created=$false;localendCreated=$false;groupsChanged=$false;nimToolResult='reported failed; simulation never invokes'};Write-NSDomainFile(Join-Path $p.Evidence 'credential-collection-negative-record.json')($unsafe|ConvertTo-Json -Depth 5)'unsafe-action refusal evidence'
Add-NSDomainTimeline 168 credential-access 'Day-eight two-DC NTDS, two-host LSASS, PingCastle, and Netscan activity represented' @{credentialAccess=$false;techniques=@('T1003.003','T1003.001')};Add-NSDomainTimeline 172 collection 'Event 4624 and secretive-document staging represented by generated canaries' @{realDataAccessed=$false;archiveCreated=$false;technique='T1560.001'};Add-NSDomainTimeline 176 persistence 'WDAGUtilityAccount2 and failed Nim localend account attempts represented' @{accountsCreated=0;technique='T1136.001'};Add-NSDomainTimeline 192 completion 'Cleanup strings and eviction represented; artifacts intentionally remain' @{exfiltrationBytes=0;cleanupRun=$false}
