#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:IcedAVId='068-IcedID_Cobalt_AV_11Day';$script:IcedAVUrl='https://thedfirreport.com/2021/07/19/icedid-and-cobalt-strike-vs-antivirus/';$script:IcedAVAnchor=(Get-Date).ToUniversalTime().AddDays(-11)
function Get-IcedAVPaths{$r=Join-Path $env:PUBLIC 'IcedAVSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Pipes=Join-Path $r 'named-pipe-markers';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.IcedAVSim.owner'}}
function Assert-IcedAVSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-IcedAVManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-IcedAVPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:IcedAVId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-IcedAVEnvironment{$p=Get-IcedAVPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:IcedAVId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Hosts,$p.Evidence,$p.Pipes)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:IcedAVId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};Add-IcedAVManifest directory $p.Root created-or-reused @{generatedDcCanaryOnly=$true};$p}
function Write-IcedAVFile{param([string]$Path,[string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-IcedAVManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-IcedAVDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-IcedAVManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-IcedAVDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','ICED-AV-CANARY');$q=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$q.ExitCode;Add-IcedAVManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-IcedAVLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-IcedAVManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;proxy=$false;bytesTransferred=0}}
function Add-IcedAVTimeline{param([double]$Hours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-IcedAVPaths;[ordered]@{timestampUtc=$script:IcedAVAnchor.AddHours($Hours).ToString('o');offsetHours=$Hours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-IcedAVSummary{param($p);Write-IcedAVFile $p.Summary "IcedAVSim complete. Case 4485. Eleven-day timeline preserved. Artifacts remain; cleanup is separate. No malware, task, injection, UAC/service/security/credential/remote action, external C2, or impact occurred." summary}
