#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:URId='094-Ursnif_LOLBins_CobaltStrike_TVRat_24h';$script:URUrl='https://thedfirreport.com/2020/04/24/ursnif-via-lolbins/';$script:URAnchor=(Get-Date).ToUniversalTime().AddHours(-26)
function Get-URPaths{$r=Join-Path $env:PUBLIC 'UrsnifLolbinSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Host=Join-Path $r 'generated-host';Registry=Join-Path $r 'generated-registry';Tasks=Join-Path $r 'generated-tasks';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.UrsnifLolbinSim.owner'}}
function Assert-URSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-URManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-URPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:URId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-UREnvironment{$p=Get-URPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:URId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Evidence,$p.Host,$p.Registry,$p.Tasks)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:URId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};Add-URManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-URFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-URManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Write-URJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-URFile $Path ($Object|ConvertTo-Json -Depth 15) $Purpose}
function New-URDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='none');New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-URManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256}}
function Invoke-URDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','URSNIF-LOLBIN-CANARY');$q=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -WindowStyle Hidden;$null=$q.ExitCode;Add-URManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-URLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-URManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-URTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-URPaths;[ordered]@{timestampUtc=$script:URAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-URSummary{param($p);Write-URFile $p.Summary "UrsnifLolbinSim complete.`nSource: $script:URUrl`nA generated 26-hour axis preserves the report's approximate 24-hour delay before VNC and second-stage Cobalt/TVRat activity.`nNo email, download, script interpretation, DLL loading, registry or scheduled-task change, Tor/VNC/TeamViewer access, external connection, or final objective occurred.`nArtifacts remain; cleanup is separate." summary}
