#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\ISOQuantumSim-utilities.ps1";Assert-ISOQuantumSafety -LabConfirmed:$LabConfirmed;$p=Initialize-ISOQuantumEnvironment
$rclone=Join-Path $p.Payloads 'rclone.exe';New-ISOQuantumDecoy $rclone 'Rclone-to-MEGA stand-in';Invoke-ISOQuantumDecoy $rclone 'rclone copy backup share remote:Groups --transfers 12';foreach($n in @('Backup-A.bak','Backup-B.tib','ShareFinder.txt')){Write-ISOQuantumFile(Join-Path $p.Staging $n)"GENERATED COLLECTION CANARY $n. No real organizational data."'collection canary'};Invoke-ISOQuantumLoopback 443 'mega.io Rclone exfiltration' 'HTTPS marker';$exfil=@{realDataRead=$false;clipboardChanged=$false;MegaAccountUsed=$false;bytesTransferred=0;offNetworkOpenSources=@('212.102.59.162','165.231.182.14');attackerHost='HYPERV / 199.101.184.230'};Write-ISOQuantumFile(Join-Path $p.Evidence 'exfiltration-negative-record.json')($exfil|ConvertTo-Json)'exfil negative'
$locker=Join-Path $p.Payloads '64.exe';New-ISOQuantumDecoy $locker 'Quantum locker_64 stand-in';Invoke-ISOQuantumDecoy $locker 'locker_64.exe renamed 64.exe with target list';Write-ISOQuantumFile(Join-Path $p.Payloads 'locker_32.dll')'INERT QUANTUM DLL-NAME CANARY. Not a PE file.''ransomware canary';foreach($n in @('pass.bat','1.bat','2.bat','2.txt')){Write-ISOQuantumFile(Join-Path $p.Payloads $n)"INERT QUANTUM DEPLOYMENT CANARY $n"'deployment canary'}
foreach($hostName in @('DC-01','DC-02','BACKUP-01','SERVER-A','SERVER-B')){foreach($n in @('Finance.xlsx','Operations.docx','Database.bak')){$o=Join-Path $p.Impact "$hostName\$n";Write-ISOQuantumFile $o "GENERATED ORIGINAL $hostName/$n remains intact."'impact original';Write-ISOQuantumFile "$o.Quantum.marker"'QUANTUM MARKER ONLY. Original not encrypted.''impact marker'};Write-ISOQuantumFile(Join-Path $p.Impact "$hostName\README_TO_DECRYPT.html")'<html><body>INERT Quantum ransom-note canary. No payment link.</body></html>''note canary'}
$impact=[ordered]@{targetListExecution=$false;remoteCopies=0;domainPasswordsReset=0;event4724Generated=0;PsexecServicesCreated=0;remoteHostsTouched=0;filesEncrypted=0;QuantumRegistryAssociationCreated=$false;lockerFilesDeleted=$false};Write-ISOQuantumFile(Join-Path $p.Evidence 'quantum-impact-negative-record.json')($impact|ConvertTo-Json)'impact evidence';Invoke-ISOQuantumLoopback 445 'PsExec Quantum deployment via batch files' 'SMB marker'
Add-ISOQuantumTimeline 74 exfiltration 'Rclone backup copies to MEGA represented' @{bytesTransferred=0;realDataRead=$false;technique='T1567.002'};Add-ISOQuantumTimeline 76 impact 'Initial 64.exe and locker_32.dll target-list attempts represented' @{filesEncrypted=0};Add-ISOQuantumTimeline 78 impact 'pass.bat password reset, 1.bat copy, 2.bat PsExec, and Quantum encryption represented with intact canaries' @{passwordsReset=0;remoteHostsTouched=0;filesEncrypted=0;techniques=@('T1531','T1021.002','T1486')}
