#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\ISOQuantumSim-utilities.ps1";Assert-ISOQuantumSafety -LabConfirmed:$LabConfirmed;$p=Initialize-ISOQuantumEnvironment
$cmd=Join-Path $p.Beach 'Nigu.exe';New-ISOQuantumDecoy $cmd 'Cobalt Strike command stand-in';foreach($c in @('regsvr32 beacon DLL','GetSystem named pipe impersonation blocked then successful','CVE-2020-1472 ZeroLogon against DC','winlogon token duplication 0x40','LSASS CreateRemoteThread and ProcDump','Mimikatz variants and DCSync','net/nltest/ipconfig/systeminfo discovery','AdFind renamed find.exe and ADGet','RSAT Get-Help then Get-ADComputer export ADComputers.csv','Get-EventLog Security domain-admin pattern','Invoke-ShareFinder','WMIC remote discovery and beacon launch','RDP proxy via lsass.exe','review Domain Group Policy Objects','install Atera Splashtop AnyDesk hp.msi')){Invoke-ISOQuantumDecoy $cmd $c}
foreach($n in @('rapuab1.dll','beacA.dll','beaconM-1664297797-T0B9Z_32-cr.exe','lsass.dll','AD.bat','ns.bat','dS.bat','localdisk.bat','find.exe','find.bat','ADGet.exe','hp.msi','pon.txt','ShareFinder.txt','ADComputers.csv')){Write-ISOQuantumFile(Join-Path $p.Payloads $n)"INERT REPORTED TOOL-NAME CANARY: $n"'tool canary'}
foreach($h in @('DC-01','DC-02','BACKUP-01','SERVER-A','SERVER-B')){New-Item -Path(Join-Path $p.Hosts $h)-ItemType Directory -Force|Out-Null}
$negative=[ordered]@{servicesCreated=0;namedPipesCreated=0;ZeroLogonAttempted=$false;dcPasswordsChanged=$false;tokensDuplicated=$false;processesInjected=0;lsassAccessed=$false;credentialMaterialRead=0;DCSyncEvents=0;DefenderChanged=$false;GpoOrSysvolChanged=$false;directoryOrEventLogQueries=0;WmiCommands=0;RdpSessions=0;remoteHostsTouched=0;remoteAccessProductsInstalled=0;AnyDeskPasswordSet=$false};Write-ISOQuantumFile(Join-Path $p.Evidence 'domain-compromise-negative-record.json')($negative|ConvertTo-Json)'negative evidence'
foreach($t in @('172.93.181.165 fazehotafa.com Cobalt Strike','45.66.151.109 guteyutu.com Cobalt Strike','111.90.143.191 Cobalt Strike','78.128.112.139 Cobalt Strike','199.127.60.117 attacker-hosted beacon','textbin.net PowerShell hosting','dropmefiles.com and file.io tooling sites','Atera Splashtop AnyDesk service markers')){Invoke-ISOQuantumLoopback 443 $t 'reported network marker'}
Add-ISOQuantumTimeline 16 command-and-control 'First Cobalt Strike DLL and discovery represented' @{beaconExecuted=$false};Add-ISOQuantumTimeline 17 privilege-escalation 'Blocked GetSystem followed by ZeroLogon represented' @{exploitAttempted=$false;dcPasswordChanged=$false;techniques=@('T1068','T1134')};Add-ISOQuantumTimeline 20 lateral-movement 'Remote service, WMI, and remote-access packages represented' @{remoteHostsTouched=0;servicesCreated=0};Add-ISOQuantumTimeline 24 credential-access 'SYSTEM elevation, LSASS dump, clear-text DA credential, and RDP to DC represented' @{credentialsAccessed=$false;rdpSessions=0};Add-ISOQuantumTimeline 35 discovery 'RSAT help, AD computers, ShareFinder, GPO, logon events, and ProcDump represented' @{realQueries=0;GpoChanged=$false};Add-ISOQuantumTimeline 48 credential-access 'Repeated Mimikatz, DCSync, WMIC beacon, and disk discovery represented' @{credentialsAccessed=$false;DCSyncEvents=0};Add-ISOQuantumTimeline 72 persistence 'AnyDesk on backup/server hosts and user alert represented' @{softwareInstalled=0;alertsDisplayed=0}
