#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\ISOQuantumSim-utilities.ps1";Assert-ISOQuantumSafety -LabConfirmed:$LabConfirmed;$p=Initialize-ISOQuantumEnvironment
Write-ISOQuantumFile(Join-Path $p.Lure 'Invoice-09-28#268_PDF.iso')'INERT ISO-NAME CANARY. Not a disk image and never mounted.''ISO lure';Write-ISOQuantumFile(Join-Path $p.Lure 'documents.lnk')'INERT LNK-NAME CANARY. No shell-link data.''LNK lure';Write-ISOQuantumFile(Join-Path $p.Lure 'max\eyewear.bat')'@REM INERT batch canary. No copy or execution.''batch lure';Write-ISOQuantumFile(Join-Path $p.Lure 'max\easygoing.dat')'INERT ICEDID DLL-NAME CANARY. Not a PE file.''IcedID payload'
$loader=Join-Path $p.Beach 'rundll32.exe';New-ISOQuantumDecoy $loader 'IcedID rundll32 process stand-in';Invoke-ISOQuantumDecoy $loader 'documents.lnk -> D:\max\eyewear.bat -> xcopy easygoing.dat %TEMP% -> rundll32 easygoing.dat,#1'
Write-ISOQuantumFile(Join-Path $p.Payloads 'Utucka.dll')'INERT ICEDID PERSISTENCE DLL-NAME CANARY.''IcedID stage';Write-ISOQuantumFile(Join-Path $p.Payloads 'license.dat')'INERT ICEDID LICENSE-NAME CANARY.''IcedID stage';$task=@{name='{3A79715D-4FFB-50BE-8F3A-090CE7FB4097}';interval='PT1H';logonTrigger=$true;command='rundll32 Utucka.dll,#1 --oxoj=CategoryBeyond\license.dat';created=$false};Write-ISOQuantumFile(Join-Path $p.Evidence 'icedid-task-negative-record.json')($task|ConvertTo-Json)'task evidence'
foreach($t in @('alockajilly.com / 64.227.12.180:80 campaign 2220668032','choifejuce.lol and erinindiaka.quest / 5.196.103.145:443','opiransiuera.com / 46.101.19.119:443','zoomersoidfor.com / 178.128.85.30:443','considerf.info / 5.252.177.10:443','antiflamez.bar / 66.63.188.70:443','onlinecloud.cloud / 155.138.159.45:443')){Invoke-ISOQuantumLoopback 443 $t 'IcedID marker'}
Add-ISOQuantumTimeline 0 initial-access 'Malspam ZIP, ISO mount, visible documents LNK, and hidden max directory represented' @{downloads=0;isoMounted=$false;techniques=@('T1566.001','T1553.005','T1204.002')};Add-ISOQuantumTimeline .1 execution 'eyewear.bat copied and loaded easygoing.dat through rundll32' @{malwareExecuted=$false;techniques=@('T1059.003','T1218.011')};Add-ISOQuantumTimeline .2 persistence 'Utucka.dll hourly/logon task represented' @{taskCreated=$false;technique='T1053.005'}
