function Invoke-YouDunC2Toolkit{param($Paths)
Write-YouDunFile(Join-Path $Paths.OpenDirectory '红队版.zip')'PK YOUDUN CANARY: Cobalt Strike/TaoWu/Ladon archive contents replaced by inventory' 'Cobalt Strike kit archive canary';Write-YouDunFile(Join-Path $Paths.Evidence 'cobalt-profile.json')(@{server='116.212.120.32';port=80;x86Get='/IE9CompatViewList.xml';x64Get='/visit.js';post='/submit.php';watermark=987654321;sleep=60000;spawnto='rundll32.exe';injectionApis=@('CreateThread','SetThreadContext','CreateRemoteThread','RtlCreateUserThread');beaconIncluded=$false;actual='127.0.0.1'}|ConvertTo-Json -Depth 6) 'reported Cobalt Strike profile';Invoke-YouDunLoopback 80 '116.212.120.32 Cobalt Strike'
$tools=@('0803.exe','360bowser.exe','add-admin.exe','ATPMiniDump.exe','BrowserGhost.exe','CVE-2020-0796.x64.dll','CVE-2021-1675.x64.dll','CredPhisher.exe','EfsPotato.exe','FakeLogonScreen.exe','InternalMonologue.exe','Ladon.exe','Ladon1.exe','MiniDump.exe','SafetyKatz.exe','Seatbelt.exe','SharpDPAPI.exe','SharpDump.exe','SharpGPOAbuse.exe','SharpHound.exe','SharpMiniDump.exe','SharpShares.exe','SharpZeroLogon.exe','SweetPotato.exe','WeblogicRCE.exe','WMIHACKER.vbs','x64\PrintSpoofer.exe','x86\PrintSpoofer.exe');foreach($n in $tools){Write-YouDunFile(Join-Path $Paths.Toolkit "taowu-cobalt-strike-master\script\$n")"YOUDUN inert toolkit filename: $n" 'TaoWu inventory canary'}
Write-YouDunFile(Join-Path $Paths.Toolkit 'TOOLKIT-INVENTORY.txt')(@'
The full report inventory includes TaoWu, Ladon/Landon, CrossC2-GithubBot, credential,
reconnaissance, privilege-escalation, lateral-movement, logging-evasion, and proxy tools.
All entries here and in IOC-METADATA.json are file-presence metadata only. No component
contains original code and none is invoked for its reported capability.
'@) 'toolkit inventory notice'
Write-YouDunFile(Join-Path $Paths.Evidence 'viper.json')(@{management='fgfg.bcfnwg.cc:60000';actorIp='101.36.124.183';install='f8x -all / -viper';dockerInstalled=$false;viperInstalled=$false;wpcargoCve='CVE-2021-25003';exploitExecuted=$false;payloadUploaded=$false}|ConvertTo-Json -Depth 5) 'Viper/f8x/WPCargo metadata';Invoke-YouDunLoopback 60000 'fgfg.bcfnwg.cc Viper';Write-YouDunFile(Join-Path $Paths.Evidence 'open-directory-services.json')(@{services=@(@{port=8000;name='SimpleHTTP/0.6 Python/3.8.10'},@{port=28888;name='mitmproxy';subject='163.53.216.157'},@{port=55918;name='SSH';fingerprint='1192d660e36e9b6f671a22a1ed1adb50f752ca986885ecfffdbbf3967e8ff9c1'},@{port=60000;name='Viper'});actualConnections='127.0.0.1 only'}|ConvertTo-Json -Depth 6) 'open-directory service fingerprint canary';foreach($p in @(8000,28888,55918,60000)){Invoke-YouDunLoopback $p '163.53.216.157 open-directory infrastructure'}
Add-YouDunTimeline 'Command and Control' 'Cobalt profile, TaoWu/Ladon inventory, Viper, f8x, and open-directory service fingerprints were staged with loopback telemetry.' @{liveFrameworks=$false;docker=$false;remoteInfrastructure=$false}}
