Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:YouDunId='020-You_Dun_Open_Directory_LockBit_Builder';$script:YouDunUrl='https://thedfirreport.com/2024/10/28/inside-the-open-directory-of-the-you-dun-threat-group/';$script:YouDunAnchor=(Get-Date).ToUniversalTime()
function Get-YouDunPaths{$r=Join-Path $env:PUBLIC 'YouDunOpenDirectorySim';[ordered]@{Root=$r;OpenDirectory=Join-Path $r 'open-directory';Evidence=Join-Path $r 'evidence';Targets=Join-Path $r 'generated-target-lists';Toolkit=Join-Path $r 'open-directory\toolkit';Impact=Join-Path $r 'impact-canary';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\capability-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.YouDunOpenDirectorySim.owner'}}
function Assert-YouDunSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-YouDunManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-YouDunPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:YouDunId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 8 -Compress|Add-Content $p.Manifest -Encoding UTF8}
function Initialize-YouDunEnvironment{$p=Get-YouDunPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:YouDunId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.OpenDirectory,$p.Evidence,$p.Targets,$p.Toolkit,$p.Impact)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:YouDunId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-YouDunManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-YouDunFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-YouDunManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-YouDunDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-YouDunManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;match=$false}}
function Invoke-YouDunDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$s=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','YOUDUN-CANARY',$s);$p=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$p.ExitCode;Add-YouDunManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');escaped=$true}}
function Invoke-YouDunLoopback{param([int]$Port,[string]$ReportedTarget);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-YouDunManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;remote=$false;proxy=$false}}
function Add-YouDunTimeline{param([string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-YouDunPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 7 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-YouDunSummary{param($Paths);Write-YouDunFile $Paths.Summary "YouDunOpenDirectorySim complete.`nSource: $script:YouDunUrl`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo real target, IOC, exploit, C2, container, privilege escalation, Telegram service, malware, or user data was touched." 'operator summary'}
