#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\Hive61Sim-utilities.ps1";Assert-Hive61Safety -LabConfirmed:$LabConfirmed;$p=Initialize-Hive61Environment
$cmd=Join-Path $p.Beach 'cmd.exe';if(-not(Test-Path $cmd)){New-Hive61Decoy $cmd 'hands-on command stand-in'};foreach($h in @('DC-01','FILE-01','BACKUP-01','SERVER-01')){New-Item(Join-Path $p.Hosts $h)-ItemType Directory -Force|Out-Null}
foreach($c in @('wmiexec.py -> quser -> BITS Cobalt','remote service PowerShell/MSI Atera/Splashtop','nltest /dclist','nltest /domain_trusts /all_trusts','adcomp.bat Get-ADComputer','netping /24 255 hosts','netscan port 3389','RDP from WIN-RRRU9REOK18')){Invoke-Hive61Decoy $cmd $c}
$m2=Join-Path $p.Payloads 'm2.exe';New-Hive61Decoy $m2 'custom Mimikatz filename canary' '197B8CCDDB54C39049B308A9A5037DC7BF7D3689BDC759504F3C36D483BEB9D3';Invoke-Hive61Decoy $m2 'privilege::debug; sekurlsa::logonpasswords';$cred=[ordered]@{reportedInjectionProcesses=@('svchost.exe','lsass.exe','winlogon.exe','spoolsv.exe');processInjection=$false;lsassAccess=$false;lsassCrash=$false;credentialsCollected=$false;mimikatzExecuted=$false};Write-Hive61File(Join-Path $p.Evidence 'credential-injection-negative-record.json')($cred|ConvertTo-Json)'credential/injection evidence'
foreach($n in @('Finance-Q4.xlsx','Backups-Inventory.docx','Contracts.csv')){Write-Hive61File(Join-Path $p.Shares $n)"GENERATED SHARE CANARY: $n. No customer, credential, financial, or backup data."'share canary'};$rclone=Join-Path $p.Payloads 'rclone.exe';New-Hive61Decoy $rclone 'Rclone filename canary' 'F1C87C2A32B1F0D2210A12EBCB1D3146B54E3BB5DB3FB97DBD81FE123D411632';Invoke-Hive61Decoy $rclone 'rclone SFTP 190.2.146.96:22 manual exfiltration for 90 minutes';Invoke-Hive61Loopback 22 '190.2.146.96 Rclone SFTP' 'SFTP marker'
$lateral=[ordered]@{wmi=$false;remoteServices=0;smbTransfers=0;rdpSessions=0;directoryQueries=0;networkScan=$false;generatedHosts=4;realSharesRead=$false;rcloneConfigured=$false;reportedExfilDurationMinutes=90;reportedTrafficShare='over 90 percent';bytesTransferred=0};Write-Hive61File(Join-Path $p.Evidence 'lateral-exfil-negative-record.json')($lateral|ConvertTo-Json)'lateral/exfil evidence';Invoke-Hive61Loopback 443 '23.108.57.83 sodiwugoc.com Cobalt Strike' 'HTTPS marker'
Add-Hive61Timeline 24 credential-access 'Day-two Mimikatz drops and LSASS activity represented' @{credentialsAccessed=$false;techniques=@('T1003.001','T1055')};Add-Hive61Timeline 48 discovery 'AD extraction, Netping, Netscan, RDP, shares, and backups represented against generated hosts' @{realQueries=0;techniques=@('T1087.002','T1482','T1018','T1021.001','T1135')};Add-Hive61Timeline 59 exfiltration 'Rclone 90-minute SFTP exfiltration represented with zero-byte loopback telemetry' @{bytesTransferred=0;technique='T1048.002'}
