#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:Hive61Id='032-ScreenConnect_Atera_Splashtop_Rclone_Hive_61h';$script:Hive61Url='https://thedfirreport.com/2023/09/25/from-screenconnect-to-hive-ransomware-in-61-hours/';$script:Hive61Anchor=(Get-Date).ToUniversalTime().AddHours(-61)
function Get-Hive61Paths{$r=Join-Path $env:PUBLIC 'Hive61Sim';[ordered]@{Root=$r;Lure=Join-Path $r 'initial-lure';Beach=Join-Path $r 'BEACHHOST';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Shares=Join-Path $r 'generated-shares';Impact=Join-Path $r 'impact-canaries';Evidence=Join-Path $r 'evidence';VirtualSysvol=Join-Path $r 'virtual-sysvol';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.Hive61Sim.owner'}}
function Assert-Hive61Safety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-Hive61Manifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-Hive61Paths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:Hive61Id;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-Hive61Environment{$p=Get-Hive61Paths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:Hive61Id){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beach,$p.Payloads,$p.Hosts,$p.Shares,$p.Impact,$p.Evidence,$p.VirtualSysvol)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:Hive61Id -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-Hive61Manifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return $p}
function Write-Hive61File{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-Hive61Manifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-Hive61Decoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-Hive61Manifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;hashMatch=$false}}
function Invoke-Hive61Decoy{param([string]$FilePath,[string]$ReportedCommandLine);$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','HIVE-61-CANARY',$safe);$proc=Start-Process $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-Hive61Manifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-Hive61Loopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-Hive61Manifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-Hive61Timeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-Hive61Paths;[ordered]@{timestampUtc=$script:Hive61Anchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-Hive61Summary{param($Paths);Write-Hive61File $Paths.Summary "Hive61Sim complete.`nSource: $script:Hive61Url`nSimulated time to ransomware: 61 hours.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo RMM or malware installed, process injected, credential accessed, remote host moved to, data exfiltrated, password changed, shadow/boot setting altered, GPO/SYSVOL changed, or file encrypted." 'operator summary'}
