#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\Hive61Sim-utilities.ps1";Assert-Hive61Safety -LabConfirmed:$LabConfirmed;$p=Initialize-Hive61Environment
$hive=Join-Path $p.Payloads 'windows_x64_encrypt.exe';New-Hive61Decoy $hive 'Hive ransomware filename canary' '14F00D914CCD46553FB30933FBE691E22E5197AD6A32BC076BA19935EBB7E5AA';Invoke-Hive61Decoy $hive 'windows_x64_encrypt.exe -u REDACTED:REDACTED -network-only'
foreach($hostName in @('DC-01','FILE-01','BACKUP-01')){foreach($fileName in @('Accounting.xlsx','Backup-Catalog.json','Legal.docx')){$o=Join-Path $p.Impact "$hostName\$fileName";Write-Hive61File $o "GENERATED ORIGINAL $hostName/$fileName remains intact."'impact original';Write-Hive61File "$o.hive-marker" 'HIVE IMPACT MARKER ONLY. Not encrypted data.''impact marker'};Write-Hive61File(Join-Path $p.Impact "$hostName\HOW_TO_DECRYPT.txt")"HIVE RANSOM-NOTE CANARY`nNo payment, chat credential, or live onion address. No files were encrypted."'ransom-note canary'}
$gpoPath=Join-Path $p.VirtualSysvol 'domain\Policies\{EE3DB3D4-92F9-4A97-8E8F-364A02A6E5D1}\User\Preferences\ScheduledTasks\ScheduledTasks.xml';Write-Hive61File $gpoPath '<ScheduledTasks><Task name="HIVE-CANARY" placement="User configuration" command="INERT-NETLOGON-PATH" enabled="false" /></ScheduledTasks>' 'failed GPO task replica'
$impact=[ordered]@{administratorPasswordChanged=$false;manualHiveExecutions=0;generatedHostsWithMarkers=3;filesEncrypted=0;shadowCopiesDeleted=$false;bootSettingsChanged=$false;realGpoCreated=$false;realSysvolChanged=$false;reportedGpoPlacement='User configuration (incorrect for machine-wide task)';reportedDomainWideResult='failed';realNetlogonUsed=$false};Write-Hive61File(Join-Path $p.Evidence 'hive-impact-negative-record.json')($impact|ConvertTo-Json)'Hive impact evidence';foreach($c in @('WMIC shadowcopy delete','vssadmin delete shadows /all /quiet','bcdedit recoveryenabled No','bcdedit bootstatuspolicy ignoreallfailures','gpme.msc create daily user scheduled task from NETLOGON')){Invoke-Hive61Decoy $hive $c}
Add-Hive61Timeline 60 impact 'Administrator password change and manual Hive deployment represented' @{passwordChanged=$false;filesEncrypted=0};Add-Hive61Timeline 61 impact 'Failed domain-wide GPO task and generated-host impact markers represented' @{gpoCreated=$false;sysvolChanged=$false;shadowCopiesChanged=$false;techniques=@('T1486','T1490','T1053.005')}
