#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:TPId='093-TrickBot_CobaltStrike_PyXie_SharpHound';$script:TPUrl='https://thedfirreport.com/2020/04/30/tricky-pyxie/';$script:TPAnchor=(Get-Date).ToUniversalTime().AddDays(-4)
function Get-TPPaths{$r=Join-Path $env:PUBLIC 'TrickyPyxieSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Host=Join-Path $r 'generated-host';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.TrickyPyxieSim.owner'}}
function Assert-TPSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw 'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-TPManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-TPPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:TPId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-TPEnvironment{$p=Get-TPPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:TPId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Evidence,$p.Host)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:TPId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};Add-TPManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-TPFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-TPManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Write-TPJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-TPFile $Path ($Object|ConvertTo-Json -Depth 15) $Purpose}
function New-TPDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='none');New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-TPManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256}}
function Invoke-TPDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','TRICKY-PYXIE-CANARY');$q=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -WindowStyle Hidden;$null=$q.ExitCode;Add-TPManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-TPLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-TPManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-TPTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-TPPaths;[ordered]@{timestampUtc=$script:TPAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-TPSummary{param($p);Write-TPFile $p.Summary "TrickyPyxieSim complete.`nSource: $script:TPUrl`nA generated four-day axis preserves the reported one-hour discovery delay, three-day TrickBot dormancy, concurrent Cobalt/PyXie arrival, and daily registry-save cadence.`nNo malware, injection, encoded PowerShell, registry/SAM access, directory collection, credential access, external connection, or ransomware action occurred.`nArtifacts remain; cleanup is separate." summary}
