#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:DSId='090-RDP_NS_Dharma_SingleHost';$script:DSUrl='https://thedfirreport.com/2020/06/16/the-little-ransomware-that-couldnt-dharma/';$script:DSAnchor=(Get-Date).ToUniversalTime().AddMinutes(-50)
function Get-DSPaths{$root=Join-Path $env:PUBLIC 'DharmaSingleSim';[ordered]@{Root=$root;Payloads=Join-Path $root 'payload-canaries';Evidence=Join-Path $root 'evidence';Host=Join-Path $root 'generated-host';Manifest=Join-Path $root 'artifact-manifest.jsonl';Timeline=Join-Path $root 'evidence\exercise-timeline.jsonl';Summary=Join-Path $root 'operator-summary.txt';Owner=Join-Path $root '.DharmaSingleSim.owner'}}
function Assert-DSSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw 'Lab gate refused'};$system=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$system.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-DSManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-DSPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:DSId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-DSEnvironment{$p=Get-DSPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:DSId){throw 'Refusing unowned root'}};foreach($directory in @($p.Root,$p.Payloads,$p.Evidence,$p.Host)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:DSId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};foreach($directory in @('C$\Desktop\Oc','C$\Finance','C$\ProgramData')){New-Item -Path(Join-Path $p.Host $directory)-ItemType Directory -Force|Out-Null};Add-DSManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-DSFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$directory=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $directory)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-DSManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Write-DSJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-DSFile -Path $Path -Content($Object|ConvertTo-Json -Depth 12)-Purpose $Purpose}
function New-DSDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-DSManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-DSDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent,[string]$Label='DHARMA-SINGLE-CANARY');$arguments=@('/d','/v:off','/c','echo',$Label);$process=Start-Process -FilePath $FilePath -ArgumentList $arguments -PassThru -Wait -WindowStyle Hidden;$null=$process.ExitCode;Add-DSManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($arguments-join' ');reportedOnly=$true}}
function Invoke-DSLoopback{param([int]$Port,[string]$Target,[string]$Role);$client=New-Object Net.Sockets.TcpClient;try{$pending=$client.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$pending.AsyncWaitHandle.WaitOne(500)}catch{}finally{$client.Dispose()};Add-DSManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-DSTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-DSPaths;[ordered]@{timestampUtc=$script:DSAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-DSSummary{param($Paths);Write-DSFile -Path $Paths.Summary -Content "DharmaSingleSim complete.`nSource: $script:DSUrl`nA generated 50-minute axis preserves the exact 08:58 and 09:36 observations plus subsequent sequence because no completion time is published.`nArtifacts remain; cleanup is separate.`nNo authentication, RDP, scanning, share mount, shadow deletion, log clearing, process termination, startup/registry change, remote movement, or encryption occurred." -Purpose summary}
