#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BumbleRoastSim-utilities.ps1";Assert-BumbleRoastSafety -LabConfirmed:$LabConfirmed;$p=Initialize-BumbleRoastEnvironment
Write-BumbleRoastFile(Join-Path $p.Lure 'BC_invoice_Report_CORP_46.zip')'INERT PASSWORD-PROTECTED-ZIP-NAME CANARY. Not an archive.''phishing canary';Write-BumbleRoastFile(Join-Path $p.Lure 'BC_invoice_Report_CORP_46.iso')'INERT ISO-NAME CANARY. Not a disk image and never mounted.''ISO canary';Write-BumbleRoastFile(Join-Path $p.Lure 'document.lnk')'INERT LNK-NAME CANARY. Not a shortcut.''LNK canary';Write-BumbleRoastFile(Join-Path $p.Lure 'namr.dll')'INERT BUMBLEBEE DLL-NAME CANARY. Not a PE file.''BumbleBee canary'
$loader=Join-Path $p.Payloads 'rundll32.exe';New-BumbleRoastDecoy $loader 'BumbleBee rundll32 stand-in' '2d67a6e6e7f95d3649d4740419f596981a149b500503cbc3fcbeb11684e55218';Invoke-BumbleRoastDecoy $loader 'cmd.exe /c start rundll32 namr.dll,IternalJob' 'document.lnk';foreach($t in @('142.91.3.109:443','45.140.146.30:443')){Invoke-BumbleRoastLoopback 443 $t 'BumbleBee TLS marker'}
$wab=Join-Path $p.Payloads 'wab.exe';New-BumbleRoastDecoy $wab 'WMI-launched Cobalt beacon stand-in' '1cf28902be615c721596a249ca85f479984ad85dc4b19a7ba96147e307e06381';Invoke-BumbleRoastDecoy $wab 'WmiPrvSE.exe -> wab.exe; CreateRemoteThread explorer.exe and rundll32.exe' 'WmiPrvSE.exe';Invoke-BumbleRoastLoopback 443 '45.153.243.142 / fuvataren.com /rs.js and /en' 'Cobalt Strike marker'
$commands=@('whoami','ipconfig /all','tasklist','systeminfo','wmic product get name,version','wmic /node:LAB-WS02.invalid process list brief','net view \\LAB-SRV01.invalid\Files$ /all','dir \\LAB-SRV01.invalid\C$\','tasklist /v /s LAB-WS02.invalid','net use','net group "Domain computers" /dom','net group "Enterprise admins" /domain','net group "domain admins" /domain','net localgroup administrators','nltest /dclist:','nltest /domain_trusts','ping -n 1 LAB-SRV01.invalid','shell whoami /all');foreach($c in $commands){Invoke-BumbleRoastDecoy $wab $c 'wab.exe Cobalt';Add-BumbleRoastManifest discovery-command generated-commandline-only represented @{reportedCommandLine=$c;queriesOrPackets=0}}
$any=Join-Path $p.Payloads 'AnyDesk.exe';New-BumbleRoastDecoy $any 'AnyDesk stand-in';Invoke-BumbleRoastDecoy $any 'RDP using local Administrator; copy (1).exe; install AnyDesk service Event ID 7045' 'explorer.exe';foreach($port in @(3389,445)){Invoke-BumbleRoastLoopback $port "first server pivot, AnyDesk transfer, reported port $port" 'lateral marker'}
$af=Join-Path $p.Payloads 'af.exe';New-BumbleRoastDecoy $af 'AdFind stand-in' 'b1102ed4bca6dae6f2f498ade2f73f76af527fa803f0e0b46e100d4cf5150682';foreach($q in @('af.exe -f objectcategory=person','af.exe -f objectcategory=computer','af.exe -f objectcategory=organizationalUnit','af.exe -sc trustdmp','af.exe -subnets -f objectCategory=subnet','af.exe -f objectcategory=group')){Invoke-BumbleRoastDecoy $af $q 'wab.exe'}
Write-BumbleRoastFile(Join-Path $p.Evidence 'day1-negative-record.json')(@{ISOMounted=$false;LNKExecuted=$false;malwareExecuted=$false;processesInjected=0;directoryQueries=0;RDPSessions=0;SMBCopies=0;AnyDeskInstalled=$false;servicesCreated=0;remoteHostsTouched=0}|ConvertTo-Json)'day-one safety record';Add-BumbleRoastTimeline 0 initial-access 'Password-protected ZIP, ISO, document.lnk, namr.dll, and rundll32 export represented' @{filesExecuted=0;techniques=@('T1566','T1204.002','T1553.005','T1218.011')};Add-BumbleRoastTimeline 3 execution 'BumbleBee drops wab.exe through WMI; Cobalt injects explorer and rundll32 and begins discovery' @{downloads=0;processesInjected=0;techniques=@('T1047','T1055','T1105')};Add-BumbleRoastTimeline 4 lateral-movement 'Local Administrator RDP, AnyDesk transfer/service, and first AdFind run represented' @{remoteHostsTouched=0;softwareInstalled=0;techniques=@('T1021.001','T1570','T1219')}
