#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:BumbleRoastId='046-BumbleBee_Cobalt_VulnRecon_Kerberoast_DA_11Day';$script:BumbleRoastUrl='https://thedfirreport.com/2022/08/08/bumblebee-roasts-its-way-to-domain-admin/';$script:BumbleRoastAnchor=(Get-Date).ToUniversalTime().AddHours(-264)
function Get-BumbleRoastPaths{$r=Join-Path $env:PUBLIC 'BumbleRoastSim';[ordered]@{Root=$r;Lure=Join-Path $r 'iso-lure';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.BumbleRoastSim.owner'}}
function Assert-BumbleRoastSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-BumbleRoastManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-BumbleRoastPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:BumbleRoastId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-BumbleRoastEnvironment{$p=Get-BumbleRoastPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:BumbleRoastId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Payloads,$p.Staging,$p.Hosts,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:BumbleRoastId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-BumbleRoastManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-BumbleRoastFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-BumbleRoastManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-BumbleRoastDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-BumbleRoastManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-BumbleRoastDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='explorer.exe');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','BUMBLE-ROAST-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-BumbleRoastManifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-BumbleRoastLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-BumbleRoastManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-BumbleRoastTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-BumbleRoastPaths;[ordered]@{timestampUtc=$script:BumbleRoastAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-BumbleRoastSummary{param($Paths);Write-BumbleRoastFile $Paths.Summary "BumbleRoastSim complete.`nSource: $script:BumbleRoastUrl`nEleven-day chronology preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo ISO mount, malware, download, injection, credential access, ticket request or cracking, account/service change, remote action, directory/share query, RMM install, file deletion, IOC contact, or impact occurred." 'operator summary'}
