#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:NWId='086-RDP_Cobalt_ProcDump_Mimikatz_NetWalker_1h'
$script:NWUrl='https://thedfirreport.com/2020/08/31/netwalker-ransomware-in-1-hour/'
$script:NWAnchor=(Get-Date).ToUniversalTime().AddMinutes(-60)
function Get-NWPaths{$root=Join-Path $env:PUBLIC 'NetWalkerHourSim';[ordered]@{Root=$root;Payloads=Join-Path $root 'payload-canaries';Evidence=Join-Path $root 'evidence';Hosts=Join-Path $root 'generated-hosts';Staging=Join-Path $root 'staging';Manifest=Join-Path $root 'artifact-manifest.jsonl';Timeline=Join-Path $root 'evidence\exercise-timeline.jsonl';Summary=Join-Path $root 'operator-summary.txt';Owner=Join-Path $root '.NetWalkerHourSim.owner'}}
function Assert-NWSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$system=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$system.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-NWManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-NWPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:NWId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-NWEnvironment{$p=Get-NWPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:NWId){throw 'Refusing unowned root'}};foreach($directory in @($p.Root,$p.Payloads,$p.Evidence,$p.Hosts,$p.Staging)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:NWId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-NWManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-NWFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$directory=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $directory)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-NWManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Write-NWJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-NWFile -Path $Path -Content($Object|ConvertTo-Json -Depth 12)-Purpose $Purpose}
function New-NWDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-NWManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-NWDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent,[string]$Label='NETWALKER-CANARY');$arguments=@('/d','/v:off','/c','echo',$Label);$process=Start-Process -FilePath $FilePath -ArgumentList $arguments -PassThru -Wait -WindowStyle Hidden;$null=$process.ExitCode;Add-NWManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($arguments-join' ');reportedOnly=$true}}
function Invoke-NWLoopback{param([int]$Port,[string]$Target,[string]$Role);$client=New-Object Net.Sockets.TcpClient;try{$pending=$client.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$pending.AsyncWaitHandle.WaitOne(500)}catch{}finally{$client.Dispose()};Add-NWManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-NWTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-NWPaths;[ordered]@{timestampUtc=$script:NWAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function New-NWHostTree{param([string]$Name,[string]$Role);$p=Get-NWPaths;$hostRoot=Join-Path $p.Hosts $Name;foreach($directory in @('C$\Finance','C$\Operations','ADMIN$')){New-Item -Path(Join-Path $hostRoot $directory)-ItemType Directory -Force|Out-Null};Write-NWJson -Path(Join-Path $hostRoot 'host-profile.json')-Object([ordered]@{hostname=$Name;role=$Role;generated=$true;remoteSystem=$false})-Purpose generated-host;Write-NWFile -Path(Join-Path $hostRoot 'C$\Finance\invoice.docx.canary')-Content "INERT GENERATED DATA FOR $Name. This is not user data." -Purpose generated-canary-data;$hostRoot}
function Write-NWSummary{param($Paths);Write-NWFile -Path $Paths.Summary -Content "NetWalkerHourSim complete.`nSource: $script:NWUrl`nInternal case: 1003`nThe report's approximate one-hour axis is preserved, including Cobalt at minute 16, discovery, credential-dump metadata, DC RDP pivot, and PsExec/PowerShell impact.`nArtifacts remain; cleanup is separate.`nNo external login, authentication, malware, LSASS access, credential collection, RDP/SMB/PsExec/PowerShell action, share mount, or encryption occurred." -Purpose summary}
