#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\GootSagaSim-utilities.ps1";Assert-GootSagaSafety -LabConfirmed:$LabConfirmed;$p=Initialize-GootSagaEnvironment
$dllhost=Join-Path $p.Beachhead 'dllhost.exe';New-GootSagaDecoy $dllhost 'Cobalt Strike injection target canary'
foreach($c in @('env:','Get-WmiObject Win32_OperatingSystem','Get-Process','Get-Process | where MainWindowTitle','Get-PSDrive','LDAP 389/3268 group discovery','ping sweep as SYSTEM','Get-DomainFileServer','Get-DomainSearcher','getsystem')){Invoke-GootSagaDecoy $dllhost $c}
$cs=[ordered]@{c2='91.215.85.143:443';ja3='72a589da586844d7f0818ce684948eea';ja3s='f176ba63b4d68e576b5ba345bec2c7b7';watermark=206546002;http=@{sleep=22000;jitter=37;get='/jquery-3.3.1.min.js';post='/jquery-3.3.2.min.js'};smb=@{sleep=10000;port=4444;pipe='\\.\pipe\mojo.5688.8052.1838949397870888770b'};observedPipes=@('\4fcc39','\netsvc\1324','\netsvc\415');injectionPerformed=$false};Write-GootSagaFile(Join-Path $p.Evidence 'cobalt-strike-config.json')($cs|ConvertTo-Json -Depth 7)'Cobalt configuration evidence';Invoke-GootSagaLoopback 443 '91.215.85.143 Cobalt Strike' 'HTTPS marker'
$unsafe=[ordered]@{lsass=@{reportedGrantedAccess='0x1010';accessed=$false;credentialsRead=$false};defender=@{remoteService='CreateWowService';settingsChanged=$false;tasksDeleted=$false;serviceCreated=$false};lateral=@{smbAdminShare=$false;wmiRemoteProcess=$false;remoteService=$false;rdpSettingsChanged=$false;restrictedAdminChanged=$false;firewallChanged=$false};directory=@{ldapQueried=$false;groups=@('Domain Users','Administrators','Remote Desktop Users','Domain Administrators')}};Write-GootSagaFile(Join-Path $p.Evidence 'unsafe-actions-negative-record.json')($unsafe|ConvertTo-Json -Depth 8)'safety refusal evidence'
$serviceStrings=@('psexec_psh -> CreateWowService -> disable Windows Defender Real-Time Monitoring','SMB admin share transfer e544944.exe -> remote service','reg add HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server fDenyTSConnections 0','reg add DisableRestrictedAdmin 0','netsh enable Remote Desktop and Remote Admin firewall profiles')
foreach($c in $serviceStrings){Invoke-GootSagaDecoy $dllhost $c}
Write-GootSagaFile(Join-Path $p.Beachhead 'AppData\Roaming\s5.ps1')"# INERT SystemBC filename canary`n# Reported C2: 91.92.136.20:4001`n# No socket, encryption, SOCKS, persistence, or executable statements."'SystemBC canary'
$systembc=[ordered]@{file='s5.ps1';reportedC2='91.92.136.20:4001';protocol='SOCKS v5';runKey='socks_powershell';tunneledPort=3389;attackerHosts=@('DESKTOP-GRALDC5','HOME-PC');executed=$false;runKeyCreated=$false;tunnelCreated=$false;rdpPerformed=$false};Write-GootSagaFile(Join-Path $p.Evidence 'systembc-negative-record.json')($systembc|ConvertTo-Json -Depth 5)'SystemBC evidence';Invoke-GootSagaLoopback 4001 '91.92.136.20 SystemBC' 'SOCKS marker'
Add-GootSagaTimeline 545 discovery 'Cobalt injection, LDAP/SMB checks, and group discovery represented by local evidence' @{injection=$false;directoryQueries=0;techniques=@('T1055','T1018','T1087.002','T1069.002','T1046')}
Add-GootSagaTimeline 555 lateral-movement 'Remote service, Defender tampering, beacon transfer, and LSASS access represented as negative actions' @{remoteHostsTouched=0;lsassAccess=$false;techniques=@('T1021.002','T1562.001','T1003.001')}
Add-GootSagaTimeline 680 command-and-control 'SystemBC SOCKS/RDP pivot represented with loopback-only telemetry' @{tunnelCreated=$false;remoteRdp=$false;techniques=@('T1090','T1021.001','T1547.001')}
