#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:S5Id='089-RDP_Tor_Meterpreter_Snatch_5h';$script:S5Url='https://thedfirreport.com/2020/06/21/snatch-ransomware/';$script:S5Anchor=(Get-Date).ToUniversalTime().AddMinutes(-280)
function Get-S5Paths{$root=Join-Path $env:PUBLIC 'SnatchFiveSim';[ordered]@{Root=$root;Payloads=Join-Path $root 'payload-canaries';Evidence=Join-Path $root 'evidence';Hosts=Join-Path $root 'generated-hosts';Staging=Join-Path $root 'staging';Manifest=Join-Path $root 'artifact-manifest.jsonl';Timeline=Join-Path $root 'evidence\exercise-timeline.jsonl';Summary=Join-Path $root 'operator-summary.txt';Owner=Join-Path $root '.SnatchFiveSim.owner'}}
function Assert-S5Safety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw 'Lab gate refused'};$system=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$system.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-S5Manifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-S5Paths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:S5Id;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-S5Environment{$p=Get-S5Paths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:S5Id){throw 'Refusing unowned root'}};foreach($directory in @($p.Root,$p.Payloads,$p.Evidence,$p.Hosts,$p.Staging)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:S5Id -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-S5Manifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-S5File{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$directory=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $directory)){New-Item -Path $directory -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-S5Manifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Write-S5Json{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-S5File -Path $Path -Content($Object|ConvertTo-Json -Depth 12)-Purpose $Purpose}
function New-S5Decoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-S5Manifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-S5Decoy{param([string]$FilePath,[string]$Reported,[string]$Parent,[string]$Label='SNATCH-FIVE-CANARY');$arguments=@('/d','/v:off','/c','echo',$Label);$process=Start-Process -FilePath $FilePath -ArgumentList $arguments -PassThru -Wait -WindowStyle Hidden;$null=$process.ExitCode;Add-S5Manifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($arguments-join' ');reportedOnly=$true}}
function Invoke-S5Loopback{param([int]$Port,[string]$Target,[string]$Role);$client=New-Object Net.Sockets.TcpClient;try{$pending=$client.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$pending.AsyncWaitHandle.WaitOne(500)}catch{}finally{$client.Dispose()};Add-S5Manifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-S5Timeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-S5Paths;[ordered]@{timestampUtc=$script:S5Anchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function New-S5HostTree{param([string]$Name,[string]$Role);$p=Get-S5Paths;$root=Join-Path $p.Hosts $Name;foreach($directory in @('C$\Windows\wmis','C$\Finance','C$\ProgramData','ADMIN$')){New-Item -Path(Join-Path $root $directory)-ItemType Directory -Force|Out-Null};Write-S5Json -Path(Join-Path $root 'host-profile.json')-Object([ordered]@{hostname=$Name;role=$Role;generated=$true;remoteSystem=$false})-Purpose generated-host;Write-S5File -Path(Join-Path $root 'C$\Finance\payroll.xlsx.canary')-Content "INERT GENERATED DATA FOR $Name. This is not user data." -Purpose generated-canary-data;$root}
function Write-S5Summary{param($Paths);Write-S5File -Path $Paths.Summary -Content "SnatchFiveSim complete.`nSource: $script:S5Url`nInternal case: report does not publish an internal case number.`nThe 05:15 to approximately 09:55 UTC, under-five-hour sequence is preserved.`nArtifacts remain; cleanup is separate.`nNo authentication, RDP, Tor, tunnel, named pipe, C2, task, NTDS/snapshot action, Defender change, service, boot configuration, shutdown/reboot, remote action, or encryption occurred." -Purpose summary}
