#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\SnatchFiveSim-utilities.ps1";Assert-S5Safety -LabConfirmed:$LabConfirmed;$p=Initialize-S5Environment
$roles=[ordered]@{'BAK01-CANARY'='backup server';'APP01-CANARY'='application server';'FS01-CANARY'='file server';'WS01-CANARY'='workstation';'WS02-CANARY'='workstation';'DC01-CANARY'='generated DC representation'};foreach($entry in $roles.GetEnumerator()){$null=New-S5HostTree -Name $entry.Key -Role $entry.Value}
$safe=Join-Path $p.Payloads 'safe.exe';$shell=Join-Path $p.Payloads 'impact-runner.exe';New-S5Decoy -Path $safe -Role 'Snatch safe.exe stand-in' -PublishedSha256 '3160b4308dd9434ebb99e5747ec90d63722a640d329384b1ed536b59352dace6';New-S5Decoy -Path $shell -Role 'reported impact-command stand-in'
Invoke-S5Decoy -FilePath $safe -Reported 'safe.exe executed manually over RDP, beginning with backup server' -Parent 'RDP user session' -Label 'SYNTHETIC-SNATCH'
$reported=@('Set-MpPreference -DisableRealtimeMonitoring $true','safe.exe creates a service to run itself','bcdedit configures next boot into Safe Mode without networking','shutdown.exe reboots immediately','four dropped batch files execute the ransom sequence')
foreach($command in $reported){Invoke-S5Decoy -FilePath $shell -Reported $command -Parent 'safe.exe' -Label 'NO-IMPACT-COMMAND'}
Write-S5Json -Path(Join-Path $p.Evidence 'safe-behavior.json')-Object([ordered]@{reportedActions=$reported;batchFilesRepresented=6;PowerShellExecuted=$false;DefenderChanged=$false;servicesCreated=0;bootConfigurationChanged=0;shutdownsIssued=0;reboots=0;safeModeBoots=0;networkingDisabled=$false})-Purpose impact
$records=New-Object System.Collections.Generic.List[object];foreach($entry in $roles.GetEnumerator()){$root=Join-Path $p.Hosts $entry.Key;Write-S5File -Path(Join-Path $root 'C$\Finance\SNATCH-README.txt')-Content "INERT SNATCH NOTE CANARY for $($entry.Key). Reported demand: 40k USD, negotiated below 15k; no payment instructions." -Purpose ransom-note-canary;Write-S5File -Path(Join-Path $root 'C$\Finance\payroll.xlsx.SNATCH-CANARY')-Content "INERT ENCRYPTION MARKER for generated host $($entry.Key)." -Purpose encryption-canary;$records.Add([ordered]@{hostname=$entry.Key;role=$entry.Value;generatedTree=$root;markers=2;userFilesRead=0;userFilesChanged=0;filesEncrypted=0})}
Write-S5Json -Path(Join-Path $p.Evidence 'impact-summary.json')-Object([ordered]@{reportedOrder=@('backup server first','each machine manually by RDP','all domain systems including DCs within 15 minutes');reportedDemand='40k USD, negotiated below 15k';generatedHosts=$records;rdpSessions=0;remoteFilesWritten=0;DefenderChanged=$false;bootConfigurationChanged=0;reboots=0;userFilesChanged=0;filesEncrypted=0;generatedCanaryMarkers=12})-Purpose impact
Invoke-S5Loopback -Port 3389 -Target 'backup server and every domain system' -Role 'manual RDP deployment marker'
Add-S5Timeline 265 impact 'About 45 minutes after Ditsnap marker, backup server targeted first' @{rdpSessions=0;DefenderChanged=$false;filesEncrypted=0}
Add-S5Timeline 280 impact 'Within 15 minutes, all generated hosts including DC representation marked' @{reboots=0;filesEncrypted=0;generatedCanaryMarkers=12}
Write-S5Json -Path(Join-Path $p.Evidence 'phase3-negative.json')-Object([ordered]@{rdpSessions=0;remoteFilesWritten=0;PowerShellExecuted=$false;DefenderChanged=$false;servicesCreated=0;bootConfigurationChanged=0;shutdownsIssued=0;reboots=0;safeModeBoots=0;networkingDisabled=$false;userFilesRead=0;userFilesChanged=0;filesEncrypted=0;securityControlsChanged=0;logsCleared=0;shadowCopiesDeleted=0;externalConnections=0})-Purpose safety
