#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:TrickPassId='066-Trickbot_Cobalt_Fake1Password_WDigest';$script:TrickPassUrl='https://thedfirreport.com/2021/08/16/trickbot-leads-up-to-fake-1password-installation/';$script:TrickPassAnchor=(Get-Date).ToUniversalTime().AddHours(-6)
function Get-TrickPassPaths{$r=Join-Path $env:PUBLIC 'TrickPassSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Profile=Join-Path $r 'generated-profile';Hosts=Join-Path $r 'generated-hosts';Pipes=Join-Path $r 'named-pipe-markers';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.TrickPassSim.owner'}}
function Assert-TrickPassSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-TrickPassManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-TrickPassPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:TrickPassId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-TrickPassEnvironment{$p=Get-TrickPassPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:TrickPassId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Profile,$p.Hosts,$p.Pipes,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:TrickPassId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-TrickPassManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedDcCanaryOnly=$true};$p}
function Write-TrickPassFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-TrickPassManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-TrickPassDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-TrickPassManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-TrickPassDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='wermgr.exe');$args=@('/d','/v:off','/c','echo','TRICKPASS-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-TrickPassManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-TrickPassLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-TrickPassManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-TrickPassTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-TrickPassPaths;[ordered]@{timestampUtc=$script:TrickPassAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-TrickPassSummary{param($Paths);Write-TrickPassFile $Paths.Summary "TrickPassSim complete.`nSource: $script:TrickPassUrl`nInternal case: 4778`nThe six-hour axis is generated ordering; only the report's relative facts are treated as observed.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malware, macro, injection, scheduled task, registry change, LSASS access, credentials, AD/WMI query, remote execution, named pipe, shellcode, external C2, exfiltration, or impact occurred." 'operator summary'}
