#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:SMId='095-RDP_XMRig_NSSM_Neshta_Persistence';$script:SMUrl='https://thedfirreport.com/2020/04/20/sqlserver-or-the-miner-in-the-basement/';$script:SMAnchor=(Get-Date).ToUniversalTime().AddMinutes(-90)
function Get-SMPaths{$r=Join-Path $env:PUBLIC 'SqlMinerBasementSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Host=Join-Path $r 'generated-host';Registry=Join-Path $r 'generated-registry';Services=Join-Path $r 'generated-services';Tasks=Join-Path $r 'generated-tasks';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.SqlMinerBasementSim.owner'}}
function Assert-SMSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-SMManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-SMPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:SMId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-SMEnvironment{$p=Get-SMPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:SMId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Evidence,$p.Host,$p.Registry,$p.Services,$p.Tasks)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:SMId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};Add-SMManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-SMFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-SMManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Write-SMJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-SMFile $Path ($Object|ConvertTo-Json -Depth 15) $Purpose}
function New-SMDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='none');New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-SMManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256}}
function Invoke-SMDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','SQL-MINER-CANARY');$q=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -WindowStyle Hidden;$null=$q.ExitCode;Add-SMManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-SMLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-SMManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-SMTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-SMPaths;[ordered]@{timestampUtc=$script:SMAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-SMSummary{param($p);Write-SMFile $p.Summary "SqlMinerBasementSim complete.`nSource: $script:SMUrl`nThe generated 90-minute axis preserves observed order only; the report publishes no intrusion duration.`nNo authentication, RDP, ACL/attribute/hosts/registry change, process kill, service or task registration, executable association hijack, external connection, or cryptocurrency mining occurred.`nArtifacts remain; cleanup is separate." summary}
