#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\EmotetQuantumSim-utilities.ps1";Assert-EmotetQuantumSafety -LabConfirmed:$LabConfirmed;$p=Initialize-EmotetQuantumEnvironment
$beacon=Join-Path $p.Payloads 'sc_https_x64.exe';New-EmotetQuantumDecoy $beacon 'Cobalt Strike executable beacon stand-in';Invoke-EmotetQuantumDecoy $beacon 'Day 3 Cobalt Strike beacon HTTP/HTTPS 45-second sleep 37% jitter' 'Emotet.dll';foreach($t in @('139.60.161.167 / survefuz.com:80','139.60.160.18 / juanjik.com:443')){Invoke-EmotetQuantumLoopback 443 $t 'Cobalt Strike marker'}
$manual=@('whoami /groups','net group /domain','net group "domain computers" /domain','net group /domain "Domain controller"','net group /domain "Domain controllers"','net group "domain admins" /domain','nltest /trusted_domains','tasklist','ping LAB-WS02');foreach($c in $manual){Invoke-EmotetQuantumDecoy $beacon $c 'beacon.exe';Add-EmotetQuantumManifest discovery-command 'generated-commandline-only' represented @{reportedCommandLine=$c;executedDiscovery=$false}}
Write-EmotetQuantumFile(Join-Path $p.Payloads 'Invoke-ShareFinder.ps1')'# INERT ShareFinder-name canary. No PowerView or network code.''share discovery canary';Write-EmotetQuantumFile(Join-Path $p.Staging 'shares.txt')"GENERATED SHARES`n\\LAB-FILE01\Revenue`n\\LAB-FILE01\Insurance`n\\LAB-FILE01\Passwords`nNo share was queried or accessed."'generated ShareFinder output'
Add-EmotetQuantumJsonLine(Join-Path $p.Logs 'Sysmon-ProcessAccess.jsonl')@{eventId=10;targetImage='lsass.exe';grantedAccess=@('0x1010','0x0040');accessAttempted=$false;credentialsRead=$false;synthetic=$true}'LSASS access canary';Write-EmotetQuantumFile(Join-Path $p.Evidence 'credential-injection-negative-record.json')(@{reportedInjectionTargets=@('winlogon.exe','RuntimeBroker.exe','svchost.exe','taskhostw.exe','dllhost.exe');processesInjected=0;LSASSHandlesOpened=0;credentialsCollected=0}|ConvertTo-Json)'credential safety record'
Write-EmotetQuantumFile(Join-Path $p.Payloads 'remote-beacon.ps1')'# INERT failed remote PowerShell beacon canary.''remote beacon canary';Invoke-EmotetQuantumDecoy $beacon 'remote service executes PowerShell beacon on LAB-WS02; C2 connection fails' 'beacon.exe';Invoke-EmotetQuantumDecoy $beacon 'SMB copy sc_https_x64.exe to LAB-WS02 ProgramData; WMI process create' 'beacon.exe'
foreach($n in @('find.bat','p.bat','AdFind.exe')){Write-EmotetQuantumFile(Join-Path $p.Payloads $n)"INERT DISCOVERY CANARY $n. No directory or network query."'domain discovery canary'};foreach($c in @('AdFind -f objectcategory=computer','AdFind -f objectcategory=organizationalUnit','AdFind -subnets -f objectCategory=subnet','AdFind -f objectcategory=group','AdFind -gcb -sc trustdmp','p.bat ping sweep')){Invoke-EmotetQuantumDecoy $beacon $c 'cmd.exe'}
Write-EmotetQuantumFile(Join-Path $p.Evidence 'remote-zerologon-negative-record.json')(@{PowerShellRemoteBeaconConnections=0;SMBCopies=0;WMIExecutions=0;remoteServicesCreated=0;remoteHostsTouched=0;NetlogonChallengesSent=0;ZeroLogonExploited=$false;domainControllerAccessed=$false}|ConvertTo-Json)'remote safety record';foreach($port in @(135,445)){Invoke-EmotetQuantumLoopback $port "LAB-WS02 and LAB-DC01 WMI/SMB marker" 'lateral marker'}
Add-EmotetQuantumTimeline 48 execution 'Day 3 Emotet drops first Cobalt Strike executable beacon' @{beaconExecuted=$false};Add-EmotetQuantumTimeline 49 discovery 'Cobalt net/nltest/tasklist/ping and ShareFinder activity represented' @{realQueriesExecuted=0;sharesAccessed=0;techniques=@('T1087.002','T1069.002','T1135')};Add-EmotetQuantumTimeline 50 lateral-movement 'Failed remote PowerShell then SMB-transferred WMI beacon on workstation represented' @{remoteHostsTouched=0;techniques=@('T1021.002','T1047','T1570')};Add-EmotetQuantumTimeline 51 credential-access 'Injected beacon LSASS access 0x1010/0x0040 represented' @{LSASSAccessed=$false};Add-EmotetQuantumTimeline 72 privilege-escalation 'Day 4 Netlogon flight suggesting failed ZeroLogon attempt represented' @{exploitAttempted=$false;technique='T1210'};Add-EmotetQuantumTimeline 74 discovery 'DC find.bat AdFind and p.bat ping sweep represented' @{directoryQueries=0;packetsSent=0}
