#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\EmotetQuantumSim-utilities.ps1";Assert-EmotetQuantumSafety -LabConfirmed:$LabConfirmed;$p=Initialize-EmotetQuantumEnvironment
Write-EmotetQuantumFile(Join-Path $p.Lure 'K-1 06.13.2022.lnk')'INERT LNK-NAME CANARY. No shell-link or encoded PowerShell content. Source metadata: black-dog / 08:00:27:c6:74:5d.''malspam LNK canary'
$ps=Join-Path $p.Beach 'powershell.exe';New-EmotetQuantumDecoy $ps 'LNK-embedded PowerShell stand-in';Invoke-EmotetQuantumDecoy $ps 'LNK -> powershell.exe -c decode split Base64 variables; IWR one of six URLs; regsvr32 downloaded DLL' 'explorer.exe'
Write-EmotetQuantumFile(Join-Path $p.Payloads 'jxKPIrMFxJ.OOf')'INERT EMOTET DLL-NAME CANARY. Not a PE file.''Emotet payload canary';$regsvr=Join-Path $p.Payloads 'regsvr32.exe';New-EmotetQuantumDecoy $regsvr 'Emotet regsvr32 stand-in';Invoke-EmotetQuantumDecoy $regsvr 'regsvr32.exe %TEMP%\nfWFQ\jxKPIrMFxJ.OOf' 'powershell.exe'
Write-EmotetQuantumFile(Join-Path $p.Evidence 'run-key-negative-record.json')(@{malware='Emotet';registryRunKeyCreated=$false;registryValuesWritten=0;randomTempCopies=0}|ConvertTo-Json)'persistence safety record'
$cmd=Join-Path $p.Beach 'cmd.exe';New-EmotetQuantumDecoy $cmd 'Emotet daily discovery stand-in';foreach($day in 0..3){foreach($c in @('systeminfo','ipconfig /all','nltest /dclist:LAB.DOMAIN')){Invoke-EmotetQuantumDecoy $cmd $c 'Emotet.dll'};Add-EmotetQuantumTimeline($day*24+.5)'discovery'"Day $($day+1) automated Emotet discovery represented"@{realQueriesExecuted=0;techniques=@('T1082','T1018')}}
Write-EmotetQuantumFile(Join-Path $p.Lure 'outbound-spam-example.eml')"From: generated@invalid.example`nTo: generated@invalid.example`nSubject: Training canary`nAttachment: inert.xls`nNo SMTP connection occurred."'generated spam canary';Write-EmotetQuantumFile(Join-Path $p.Evidence 'spam-negative-record.json')(@{SMTPConnections=0;emailsSent=0;realRecipients=0;attachment='generated inert.xls'}|ConvertTo-Json)'spam safety record'
foreach($t in @('descontador.com.br','www.elaboro.pl','el-energiaki.gr','drechslerstammtisch.de','dhnconstrucciones.com.ar','dilsrl.com')){Invoke-EmotetQuantumLoopback 80 $t 'Emotet payload marker'}
Add-EmotetQuantumTimeline 0 initial-access 'Malspam LNK user execution and obfuscated PowerShell loader represented' @{downloads=0;techniques=@('T1566.001','T1204.002','T1059.001')};Add-EmotetQuantumTimeline .1 execution 'Emotet DLL regsvr32 execution and random temp copy represented' @{malwareExecuted=$false;technique='T1218.010'};Add-EmotetQuantumTimeline 1 persistence 'Emotet Registry Run key represented' @{registryChanged=$false};Add-EmotetQuantumTimeline 1.5 impact 'Outbound Emotet spam begins roughly 90 minutes after infection' @{emailsSent=0}
