#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:EmotetQuantumId='041-Emotet_CobaltStrike_RMM_Rclone_Quantum_154h';$script:EmotetQuantumUrl='https://thedfirreport.com/2022/11/28/emotet-strikes-again-lnk-file-leads-to-domain-wide-ransomware/';$script:EmotetQuantumAnchor=(Get-Date).ToUniversalTime().AddHours(-154)
function Get-EmotetQuantumPaths{$r=Join-Path $env:PUBLIC 'EmotetQuantumSim';[ordered]@{Root=$r;Lure=Join-Path $r 'malspam-lure';Beach=Join-Path $r 'BEACHHEAD';Hosts=Join-Path $r 'generated-hosts';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Evidence=Join-Path $r 'evidence';Impact=Join-Path $r 'impact-canaries';Logs=Join-Path $r 'generated-event-logs';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.EmotetQuantumSim.owner'}}
function Assert-EmotetQuantumSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-EmotetQuantumManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-EmotetQuantumPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:EmotetQuantumId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-EmotetQuantumEnvironment{$p=Get-EmotetQuantumPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:EmotetQuantumId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beach,$p.Hosts,$p.Payloads,$p.Staging,$p.Evidence,$p.Impact,$p.Logs)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:EmotetQuantumId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-EmotetQuantumManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-EmotetQuantumFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-EmotetQuantumManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Add-EmotetQuantumJsonLine{param([string]$Path,[hashtable]$Record,[string]$Purpose='generated event');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};$Record|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $Path -Encoding UTF8;Add-EmotetQuantumManifest generated-event $Path appended @{purpose=$Purpose;synthetic=$true}}
function New-EmotetQuantumDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-EmotetQuantumManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-EmotetQuantumDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='explorer.exe');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','EMOTET-QUANTUM-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-EmotetQuantumManifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-EmotetQuantumLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-EmotetQuantumManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-EmotetQuantumTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-EmotetQuantumPaths;[ordered]@{timestampUtc=$script:EmotetQuantumAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-EmotetQuantumSummary{param($Paths);Write-EmotetQuantumFile $Paths.Summary "EmotetQuantumSim complete.`nSource: $script:EmotetQuantumUrl`nObserved time to ransomware: 154 hours across eight days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malware, spam, registry/service change, exploit, credential access, remote action, RMM install, real collection/exfiltration, security impairment, or encryption occurred." 'operator summary'}
