#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
$config=[pscustomobject]@{
 Id='003-Buzzing on Christmas Eve Trigona Ransomware in 3 Hours';RootName='TrigonaSim';Source='https://thedfirreport.com/2024/01/29/buzzing-on-christmas-eve-trigona-ransomware-in-3-hours/';Title='Buzzing on Christmas Eve: Trigona Ransomware in 3 Hours';DurationMinutes=180;TimelineNote='Generated three-hour axis preserves the report sequence and 2h49m time to ransomware.'
 IOCs=[ordered]@{rdpSources=@('77.83.36.6','193.106.31.98');operatorHosts=@('WIN-L1MS2GT1R2G','6CU548W0BH');exfil='Mega.io';reportedAccount='Support (published password retained only in source report, not this scenario)'}
 Files=@(
  [pscustomobject]@{path='payload-canaries\cmd.exe';role='reported-command stand-in';publishedHash='none'},[pscustomobject]@{path='payload-canaries\build_redacted.exe';role='Trigona stand-in';publishedHash='SHA256 d743daa22fdf4313a10da027b034c603eda255be037cb45b28faea23114d3b8a'},[pscustomobject]@{path='payload-canaries\netscan.exe';role='SoftPerfect NetScan stand-in';publishedHash='SHA256 18f0898d595ec054d13b02915fb7d3636f65b8e53c0c66b3c7ee3b6fc37d3566'},[pscustomobject]@{path='payload-canaries\rdp.exe';role='Remote Desktop Plus stand-in';publishedHash='SHA256 8cf27e05e639fcc273d3cceadf68e69573b58e74b4bfce8460a418366a782fbd'},[pscustomobject]@{path='payload-canaries\sd.exe';role='Snap2HTML bundle stand-in';publishedHash='SHA256 8834c84cfd7e086f74a2ffa5b14ced2c039d78feda4bad610aba1c6bb4a6ce7f'},[pscustomobject]@{path='payload-canaries\rclone.exe';role='exfiltration stand-in';publishedHash='see source report'})
 Artifacts=@(
  [pscustomobject]@{path='payload-canaries\DefenderOFF.bat';content='GENERATED INERT SECURITY-IMPAIRMENT SCRIPT CANARY; never interpreted.';purpose='toolkit artifact'},[pscustomobject]@{path='payload-canaries\DefenderON.bat';content='GENERATED INERT RESTORE SCRIPT CANARY; never interpreted.';purpose='toolkit artifact'},[pscustomobject]@{path='payload-canaries\newnewuser.bat';content='GENERATED INERT ACCOUNT SCRIPT CANARY; published password deliberately omitted.';purpose='account metadata'},[pscustomobject]@{path='payload-canaries\openrdp.bat';content='GENERATED INERT FIREWALL/RDP SCRIPT CANARY; never interpreted.';purpose='lateral metadata'},[pscustomobject]@{path='payload-canaries\start — копия.bat';content='GENERATED INERT RCLONE SCRIPT CANARY; never interpreted.';purpose='exfil artifact'},[pscustomobject]@{path='payload-canaries\start — копия — копия.bat';content='GENERATED INERT RCLONE SCRIPT CANARY; never interpreted.';purpose='exfil artifact'},[pscustomobject]@{path='evidence\отчёты со сканера\netscan.xml';content='<generated-scan targets="0" priorVictimData="false" />';purpose='scanner-history canary'},[pscustomobject]@{path='generated-hosts\FILE-CANARY\Shares\delete.me';content='Generated NetScan write-access-check artifact.';purpose='share-enumeration marker'},[pscustomobject]@{path='generated-hosts\FILE-CANARY\Shares\payroll.xlsx';content='GENERATED USER-DATA CANARY; remains intact.';purpose='impact canary'},[pscustomobject]@{path='generated-hosts\FILE-CANARY\Shares\payroll.xlsx.trigona-marker';content='Sidecar only; original unchanged.';purpose='impact marker'},[pscustomobject]@{path='generated-hosts\FILE-CANARY\Shares\how_to_decrypt.hta';content='<html>TRIGONA NOTE-SHAPED CANARY. No data was encrypted.</html>';purpose='ransom-note canary'})
 Commands=@(
  [pscustomobject]@{file='payload-canaries\cmd.exe';reported='RDP login using legitimate Administrator credentials from 77.83.36.6';parent='external RDP session'},[pscustomobject]@{file='payload-canaries\netscan.exe';reported='custom NetScan applications enumerate shares and write delete.me';parent='RDP session'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='DefenderOFF commands, Set-MpPreference, registry changes, and service stops';parent='RDP session'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='newnewuser.bat creates hidden Support admin/RDP user';parent='NetScan application'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='openrdp.bat enables firewall, WMI, and RDP';parent='toolkit (not observed executed)'},[pscustomobject]@{file='payload-canaries\rclone.exe';reported='rclone copy file shares MEGA:domain with 12 streams/transfers';parent='start — копия.bat'},[pscustomobject]@{file='payload-canaries\build_redacted.exe';reported='Trigona executes locally and over network-accessible SMB, then creates Run value';parent='RDP session'})
 Network=@(
  [pscustomobject]@{port=3389;target='77.83.36.6 / WIN-L1MS2GT1R2G';role='initial RDP'},[pscustomobject]@{port=3389;target='193.106.31.98 / 6CU548W0BH';role='second RDP session'},[pscustomobject]@{port=3389;target='generated file/backup hosts';role='lateral RDP marker'},[pscustomobject]@{port=443;target='Mega.io';role='Rclone exfil'},[pscustomobject]@{port=445;target='generated network hosts';role='Trigona SMB marker'})
 Timeline=@(
  [pscustomobject]@{offset=0;phase='initial-access';event='external RDP with legitimate Administrator credential represented';details=@{authenticationAttempts=0;rdpSessions=0}},[pscustomobject]@{offset=10;phase='discovery';event='custom NetScan and share enumeration';details=@{addressesProbed=0}},[pscustomobject]@{offset=20;phase='lateral-movement';event='RDP pivot and toolkit copy to file server';details=@{remoteActions=0}},[pscustomobject]@{offset=50;phase='defense-evasion-exfiltration';event='Defender commands and Rclone/Mega sequence';details=@{securityChanges=0;bytesTransferred=0}},[pscustomobject]@{offset=150;phase='second-session';event='source IP/hostname changes and ransomware staged';details=@{remoteActions=0}},[pscustomobject]@{offset=169;phase='impact';event='Trigona at 2h49m, SMB propagation, and note represented';details=@{filesEncrypted=0;shadowCopiesDeleted=0}},[pscustomobject]@{offset=180;phase='outcome';event='three-hour incident window complete';details=@{filesEncrypted=0}})
}
. (Join-Path $PSScriptRoot '..\LabSafeScenarioCore.ps1');Invoke-DFIRLabScenario -Config $config -LabConfirmed:$LabConfirmed
