#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:GootRdpId='050-Gootloader_Cobalt_SharpHound_LaZagne_RDP_2Day';$script:GootRdpUrl='https://thedfirreport.com/2022/05/09/seo-poisoning-a-gootloader-story/';$script:GootRdpAnchor=(Get-Date).ToUniversalTime().AddHours(-48)
function Get-GootRdpPaths{$r=Join-Path $env:PUBLIC 'GootRdpSim';[ordered]@{Root=$r;Lure=Join-Path $r 'seo-lure';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Shares=Join-Path $r 'generated-shares';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.GootRdpSim.owner'}}
function Assert-GootRdpSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-GootRdpManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-GootRdpPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:GootRdpId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-GootRdpEnvironment{$p=Get-GootRdpPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:GootRdpId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Payloads,$p.Staging,$p.Shares,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:GootRdpId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-GootRdpManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-GootRdpFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-GootRdpManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-GootRdpDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-GootRdpManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-GootRdpDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='explorer.exe');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','GOOT-RDP-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-GootRdpManifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-GootRdpLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-GootRdpManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-GootRdpTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-GootRdpPaths;[ordered]@{timestampUtc=$script:GootRdpAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-GootRdpSummary{param($Paths);Write-GootRdpFile $Paths.Summary "GootRdpSim complete.`nSource: $script:GootRdpUrl`nTwo-day chronology preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo web search/download, JavaScript/malware, registry/task change, in-memory load, injection, credential access, Defender impairment, directory/network query, remote action, restricted-admin change, real share/document access, IOC contact, or impact occurred." 'operator summary'}
