function Invoke-CobaltSocksCredentialLateral{param($Paths);$t=Get-CobaltSocksTimeline
foreach($cmd in @('nltest /dclist:LAB.INVALID','Get-ADDomain','Get-ADUser -Filter *','Get-ADGroupMember "Domain Admins"','Get-Process','Get-GPResultantSetOfPolicy')){Invoke-CobaltSocksDecoy (Join-Path $env:SystemRoot 'System32\cmd.exe') $cmd}
Write-CobaltSocksFile (Join-Path $Paths.Evidence 'process-injection-lsass.json') (@(@{source='setup_wm.exe';target='WUAUCLT.exe';api='CreateRemoteThread';actualInjection=$false},@{source='WUAUCLT.exe';target='lsass.exe';hosts=@('BEACHHEAD','FILE01','BACKUP01');GrantedAccess=@('0x1010','0x1fffff');actualAccess=$false},@{modules=@('Seatbelt','SharpView');clrLoaded=$false})|ConvertTo-Json -Depth 6) 'process injection and LSASS canaries' $t.Discovery
Write-CobaltSocksFile (Join-Path $Paths.DC 'Users\Public\Music\ntdsutil-attempt.json') (@{command='ntdsutil.exe ac in ntds ifm cr fu C:\Users\Public\Music\1';blockedBy='Windows Defender';executed=$false;ntdsAccessed=$false}|ConvertTo-Json) 'blocked NTDS attempt metadata' $t.Lateral
Write-CobaltSocksFile (Join-Path $Paths.Backup 'Users\Public\Music\Veeam-Get-Creds.ps1') "# CANARY: no Veeam database, DPAPI, registry, service, or credentials accessed.`nWrite-Output 'CANARY / Generated-Not-A-Real-Password'" 'inert Veeam credential script' $t.Day2
Write-CobaltSocksFile (Join-Path $Paths.FileServer 'Shares\shared-accounts.txt') 'LAB.INVALID\CANARY-SHARED : Generated-Not-A-Real-Password' 'generated credential-file canary' $t.Lateral
$check=Join-Path $Paths.FileServer 'Users\Public\Music\check.exe';New-CobaltSocksDecoy $check 'check.exe discovery GUI name canary' '3f97e112f0c5ddf0255ef461746a223208dc0846bde2a6dca9c825d9c706a4e9';Invoke-CobaltSocksDecoy $check 'check.exe 127.0.0.1 --availability --disk-usage --installed-programs'
Write-CobaltSocksFile (Join-Path $Paths.Evidence 'lateral-movement-events.json') (@(@{method='SMB/remote service';targets=@('DC01','FILE01','BACKUP01');remote=$false},@{method='WinRM';source='FILE01';target='DC01';eventIds=@(4103,4104);remote=$false},@{method='RDP';eventId=21;targets=@('FILE01','BACKUP01');remote=$false},@{method='Cobalt Strike psexec_psh';namedPipe='\\.\pipe\fullduplex_84';pipeCreated=$false},@{method='WMI';target='BACKUP01';remote=$false})|ConvertTo-Json -Depth 6) 'lateral movement and named-pipe canaries' $t.Lateral
Write-CobaltSocksFile (Join-Path $Paths.Evidence 'defender-policy-canaries.json') (@{gpeditReviewed=$true;defenderPolicyChanged=$false;remoteWmiDisableCommandRecorded=$true;realTimeMonitoringChanged=$false}|ConvertTo-Json) 'defense evasion metadata only' $t.Lateral
foreach($port in @(445,3389,5985)){Invoke-CobaltSocksLoopback $port 'synthetic internal host'}
Add-CobaltSocksTimeline $t.Discovery 'Credential Access/Discovery' 'WUAUCLT injection, Seatbelt/SharpView, LSASS access, and domain discovery were recorded as non-executed canaries.' @{lsassOpened=$false;domainQueried=$false};Add-CobaltSocksTimeline $t.Lateral 'Lateral Movement' 'SMB services, psexec_psh pipe, RDP, WinRM, WMI, and check.exe were represented locally.' @{remoteSystemsContacted=$false;defenderModified=$false}}
