Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$script:CobaltSocksId='018-Cobalt_Strike_Pair_of_SOCKS_LockBit';$script:CobaltSocksUrl='https://thedfirreport.com/2025/01/27/cobalt-strike-and-a-pair-of-socks-lead-to-lockbit-ransomware/';$script:CobaltSocksAnchor=(Get-Date).ToUniversalTime()
function Get-CobaltSocksPaths{$r=Join-Path $env:PUBLIC 'CobaltSocksLockBitSim';[ordered]@{Root=$r;Evidence=Join-Path $r 'evidence';Beachhead=Join-Path $r 'hosts\BEACHHEAD';FileServer=Join-Path $r 'hosts\FILE01';Backup=Join-Path $r 'hosts\BACKUP01';DC=Join-Path $r 'hosts\DC01';Music=Join-Path $r 'hosts\BEACHHEAD\Users\Public\Music';SyntheticHosts=Join-Path $r 'synthetic-targets';Collection=Join-Path $r 'collection-canary';Impact=Join-Path $r 'impact-canary';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\eleven-day-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.CobaltSocksLockBitSim.owner'}}
function Get-CobaltSocksTimeline{$i=$script:CobaltSocksAnchor.AddHours(-239);[ordered]@{Initial=$i;Discovery=$i.AddMinutes(30);Lateral=$i.AddHours(1);ExfilStart=$i.AddHours(4);FTPFailed=$i.AddHours(4).AddMinutes(20);Mega=$i.AddHours(6).AddMinutes(20);Day2=$i.AddHours(24);FTPSecond=$i.AddHours(25);Impact=$i.AddHours(237);Complete=$i.AddHours(239)}}
function Assert-CobaltSocksSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only.'};if(-not$LabConfirmed){throw 'Lab gate refused.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal.'}}
function Add-CobaltSocksManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-CobaltSocksPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:CobaltSocksId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 8 -Compress|Add-Content $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-CobaltSocksEnvironment{$p=Get-CobaltSocksPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:CobaltSocksId){throw 'Refusing unowned root.'}};foreach($d in @($p.Root,$p.Evidence,$p.Beachhead,$p.FileServer,$p.Backup,$p.DC,$p.Music,$p.SyntheticHosts,$p.Collection,$p.Impact)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:CobaltSocksId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-CobaltSocksManifest directory $p.Root created-or-reused @{cleanup='separate ownership-checked script'};return$p}
function Write-CobaltSocksFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact',[datetime]$Timestamp=$script:CobaltSocksAnchor);$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;$i=Get-Item $Path -Force;$i.CreationTimeUtc=$Timestamp.ToUniversalTime();$i.LastWriteTimeUtc=$Timestamp.ToUniversalTime().AddMinutes(1);Add-CobaltSocksManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-CobaltSocksDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-CobaltSocksManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;hashMatchExpected=$false}}
function Invoke-CobaltSocksDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','COBALTSOCKS-CANARY',$safe);$p=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$p.ExitCode;Add-CobaltSocksManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');metacharactersEscaped=$true}}
function Invoke-CobaltSocksLoopback{param([int]$Port,[string]$ReportedTarget);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-CobaltSocksManifest network "127.0.0.1:$Port" loopback-only-attempt @{reportedTarget=$ReportedTarget;remoteContact=$false;proxyUsed=$false}}
function Add-CobaltSocksTimeline{param([datetime]$Timestamp,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-CobaltSocksPaths;[ordered]@{timestampUtc=$Timestamp.ToUniversalTime().ToString('o');phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 7 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-CobaltSocksSummary{param($Paths);Write-CobaltSocksFile $Paths.Summary "CobaltSocksLockBitSim complete.`nSource: $script:CobaltSocksUrl`nRoot: $($Paths.Root)`nArtifacts remain for investigation; cleanup is separate.`nNo live malware, IOC, credential source, LSASS/NTDS, remote host, proxy, service, task, policy, registry, or user file was touched." 'operator summary'}
