#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:ContiBazarId='059-Bazar_Cobalt_Rclone_AnyDesk_Conti_5Day';$script:ContiBazarUrl='https://thedfirreport.com/2021/11/29/continuing-the-bazar-ransomware-story/';$script:ContiBazarAnchor=(Get-Date).ToUniversalTime().AddHours(-120)
function Get-ContiBazarPaths{$r=Join-Path $env:PUBLIC 'ContiBazarSim';[ordered]@{Root=$r;Lure=Join-Path $r 'lure-canaries';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-non-dc-hosts';Staging=Join-Path $r 'staging';Impact=Join-Path $r 'impact-canaries';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.ContiBazarSim.owner'}}
function Assert-ContiBazarSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-ContiBazarManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-ContiBazarPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:ContiBazarId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-ContiBazarEnvironment{$p=Get-ContiBazarPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:ContiBazarId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Payloads,$p.Hosts,$p.Staging,$p.Impact,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:ContiBazarId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-ContiBazarManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';domainControllerLanes=0};$p}
function Write-ContiBazarFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-ContiBazarManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-ContiBazarDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-ContiBazarManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-ContiBazarDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='rundll32.exe');$args=@('/d','/v:off','/c','echo','CONTI-BAZAR-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-ContiBazarManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-ContiBazarLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-ContiBazarManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-ContiBazarTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-ContiBazarPaths;[ordered]@{timestampUtc=$script:ContiBazarAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-ContiBazarSummary{param($Paths);Write-ContiBazarFile $Paths.Summary "ContiBazarSim complete.`nSource: $script:ContiBazarUrl`nThe five-day chronology, two exfiltration windows, and no-DC observation are preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malspam/macro/HTA/download, malware, injection, discovery/share query, WMI/RDP/remote action, AnyDesk, credential/LSASS access, collection/exfiltration, admin-share mount, ransomware execution, or encryption occurred." 'operator summary'}
