#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:BNId='077-Bazar_Cobalt_GetDataInfo_NoRyuk_4Day'
$script:BNUrl='https://thedfirreport.com/2021/01/31/bazar-no-ryuk/'
$script:BNAnchor=(Get-Date).ToUniversalTime().AddDays(-4)
function Get-BNPaths{$r=Join-Path $env:PUBLIC 'BazarNoRyukSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Profile=Join-Path $r 'generated-profile';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.BazarNoRyukSim.owner'}}
function Assert-BNSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-BNManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-BNPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:BNId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-BNEnvironment{$p=Get-BNPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:BNId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Profile,$p.Hosts,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:BNId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-BNManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-BNFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-BNManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-BNDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-BNManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-BNDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','BAZAR-NO-RYUK-CANARY');$q=Start-Process -FilePath $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$q.ExitCode;Add-BNManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-BNLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-BNManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-BNTimeline{param([double]$Hours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-BNPaths;[ordered]@{timestampUtc=$script:BNAnchor.AddHours($Hours).ToString('o');offsetHours=$Hours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-BNSummary{param($p);Write-BNFile $p.Summary "BazarNoRyukSim complete.`nSource: $script:BNUrl`nInternal case: 1013`nThe four-day axis preserves report day ordering; exact sub-day timestamps are illustrative where the report is approximate.`nArtifacts remain; cleanup is separate.`nNo malware, macro, external IOC/DNS request, registry, pipe/token change, injection, discovery, credential/LSASS access, remote movement, collection, exfiltration, or ransomware impact occurred." summary}
