#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\AdFindReconSim-utilities.ps1";Assert-ARSafety -LabConfirmed:$LabConfirmed;$p=Initialize-AREnvironment;$adfind=Join-Path $p.Payloads 'AdFind.exe';New-ARDecoy $adfind 'AdFind stand-in';Invoke-ARDecoy $adfind 'whoami /upn' 'cmd.exe';$queries=@(
 [ordered]@{name='person';selector='objectcategory=person';description='all person objects';file='person.txt';sample="dn: CN=Alex Morgan,OU=Users,DC=LAB,DC=LOCAL`nobjectClass: user`nuserPrincipalName: alex.morgan@lab.local"},
 [ordered]@{name='computer';selector='objectcategory=computer';description='all computer objects';file='computer.txt';sample="dn: CN=WKSTN-23,OU=Workstations,DC=LAB,DC=LOCAL`ndNSHostName: WKSTN-23.lab.local"},
 [ordered]@{name='trustdmp';selector='trustdmp';description='trust objects';file='trustdmp.txt';sample="source: LAB.LOCAL`ntarget: RESEARCH.LAB.LOCAL`ntrustDirection: Bidirectional (generated canary)"},
 [ordered]@{name='subnet';selector='objectcategory=subnet';description='subnets';file='subnet.txt';sample="dn: CN=10.77.20.0/24,CN=Subnets,CN=Sites,CN=Configuration,DC=LAB,DC=LOCAL"},
 [ordered]@{name='domainlist';selector='domainlist';description='all Domain NCs in forest sorted in DNS format';file='domainlist.txt';sample="lab.local`nresearch.lab.local"},
 [ordered]@{name='dcmodes';selector='dcmodes';description='modes of all DCs from configuration';file='dcmodes.txt';sample="DC01.lab.local Windows2016Domain (generated canary)"},
 [ordered]@{name='adinfo';selector='adinfo';description='AD information with whoami information';file='adinfo.txt';sample="Domain: lab.local`nForest: lab.local`nWhoAmI: LAB\analyst-canary"},
 [ordered]@{name='dclist';selector='dclist';description='DC FQDNs';file='dclist.txt';sample="DC01.lab.local`nDC02.lab.local"},
 [ordered]@{name='computers_pwdnotreqd';selector='computers_pwdnotreqd';description='users with password not required (wording preserved from report)';file='computers_pwdnotreqd.txt';sample="CN=Legacy Service,OU=Canary Accounts,DC=LAB,DC=LOCAL`nUAC: PASSWD_NOTREQD (generated canary)"}
);$batch=Join-Path $p.Payloads 'adfind-recon.bat';Write-ARFile $batch ("@echo off`r`nREM Inert forensic canary. It does not invoke AdFind or query a directory.`r`necho ADFIND-RECON-CANARY`r`n") 'inert batch stand-in';foreach($q in $queries){$reported="AdFind.exe [report-described selector: $($q.selector)] > $($q.file)";Invoke-ARDecoy $adfind $reported 'adfind-recon.bat';Write-ARFile(Join-Path $p.Outputs $q.file)("# GENERATED SYNTHETIC DIRECTORY OUTPUT - NO DIRECTORY WAS QUERIED`n# Report description: $($q.description)`n$($q.sample)`n") 'synthetic AdFind output'};Write-ARJson(Join-Path $p.Evidence 'adfind-query-map.json')([ordered]@{reportedWhoami='whoami /upn';reportedExecution='a batch file ran AdFind commands and redirected output to text files';batchFilenamePublished=$false;exactCommandSyntaxPublished=$false;queries=$queries;directoryQueries=0;generatedRecords=$true}) discovery;Add-ARTimeline 17 discovery 'whoami /upn represented' @{systemIdentityQueried=$false};Add-ARTimeline 18 discovery 'AdFind batch query set represented with synthetic text outputs' @{directoryQueries=0;queryCount=$queries.Count;outputRoot=$p.Outputs}
