#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\FollinaQbotSim-utilities.ps1";Assert-FollinaQbotSafety -LabConfirmed:$LabConfirmed;$p=Initialize-FollinaQbotEnvironment
Write-FollinaQbotFile(Join-Path $p.Lure 'doc532.docx')'INERT DOCX-NAME CANARY. Not OOXML; no external relationship or exploit.''Follina lure';Write-FollinaQbotFile(Join-Path $p.Lure 'document.xml.rels')'<Relationships><Relationship Target="http://104.36.229.139/generated.html" simulated="true"/></Relationships>''external relationship canary';Write-FollinaQbotFile(Join-Path $p.Lure 'payload.html')'<html><body>INERT Follina HTML canary. No ms-msdt handler or JavaScript.</body></html>''HTML canary'
$msdt=Join-Path $p.Payloads 'msdt.exe';New-FollinaQbotDecoy $msdt 'Follina msdt stand-in';Invoke-FollinaQbotDecoy $msdt 'WINWORD.EXE -> msdt.exe ms-msdt:/id PCWDiagnostic -> sdiagnhost.exe -> Base64 PowerShell' 'WINWORD.EXE';Write-FollinaQbotFile(Join-Path $p.Evidence 'PCW.debugreport.xml')'<Diagnostic simulated="true"><TargetPath>INERT recursive Follina target path and decoded PowerShell marker</TargetPath></Diagnostic>''Follina diagnostic canary'
foreach($n in @('t.A','t1.A','t2.A','liidfxngjotktx.dll')){Write-FollinaQbotFile(Join-Path $p.Payloads $n)"INERT QBOT DLL-NAME CANARY $n. Not a PE file."'Qbot payload canary'};$regsvr=Join-Path $p.Payloads 'regsvr32.exe';New-FollinaQbotDecoy $regsvr 'Qbot regsvr32 stand-in';foreach($n in @('t.A','t1.A','t2.A')){Invoke-FollinaQbotDecoy $regsvr "regsvr32.exe %TEMP%\$n" 'sdiagnhost.exe'};foreach($t in @('104.36.229.139 random.dat','85.239.55.228 random.dat','185.234.247.119 random.dat')){Invoke-FollinaQbotLoopback 80 $t 'Follina Qbot download marker'}
$persist=@{task='{E9ADEA37-C329-4967-9CF5-2682DA7D97BE}';registryPath='HKCU:\SOFTWARE\Benfouqcgq';value='rxftejkhydnwmpt';taskCreated=$false;registryKeysCreated=0;encodedC2Executed=$false};Write-FollinaQbotFile(Join-Path $p.Evidence 'task-registry-negative-record.json')($persist|ConvertTo-Json)'persistence safety record'
$cmd=Join-Path $p.Beach 'explorer.exe';New-FollinaQbotDecoy $cmd 'Injected Qbot explorer stand-in';foreach($c in @('whoami /all','cmd /c set','net view /all','ipconfig /all','net share','nslookup -querytype=ALL -timeout=12 _ldap._tcp.dc._msdcs.LAB.DOMAIN','net localgroup','netstat -nao','route print','net group /domain','net group "Domain Computers" /domain','nltest.exe /domain_trusts /all_trusts')){Invoke-FollinaQbotDecoy $cmd $c 'SysWOW64\explorer.exe'}
Write-FollinaQbotFile(Join-Path $p.Evidence 'injection-discovery-negative-record.json')(@{processHollowing=$false;processesInjected=0;discoveryCommandsRepresented=12;realQueriesExecuted=0;networkResultsCollected=$false}|ConvertTo-Json)'execution safety record';Add-FollinaQbotTimeline 0 initial-access 'Thread-hijacked Word document retrieves HTML and invokes Follina ms-msdt chain' @{exploitAttempted=$false;techniques=@('T1203','T1059.001')};Add-FollinaQbotTimeline .05 execution 'sdiagnhost starts three regsvr32 Qbot DLL loaders and PCW debug report represented' @{downloads=0;malwareExecuted=$false;technique='T1218.010'};Add-FollinaQbotTimeline .2 persistence 'Random task and HKCU Base64 C2 registry value represented' @{taskCreated=$false;registryChanged=$false};Add-FollinaQbotTimeline .3 discovery 'Injected explorer Qbot discovery command set represented' @{realQueriesExecuted=0}
