#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:FollinaQbotId='043-Follina_Qbot_Cobalt_RMM_Domain_2Day';$script:FollinaQbotUrl='https://thedfirreport.com/2022/10/31/follina-exploit-leads-to-domain-compromise/';$script:FollinaQbotAnchor=(Get-Date).ToUniversalTime().AddHours(-48)
function Get-FollinaQbotPaths{$r=Join-Path $env:PUBLIC 'FollinaQbotSim';[ordered]@{Root=$r;Lure=Join-Path $r 'thread-hijack-lure';Beach=Join-Path $r 'BEACHHEAD';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Logs=Join-Path $r 'generated-event-logs';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.FollinaQbotSim.owner'}}
function Assert-FollinaQbotSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-FollinaQbotManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-FollinaQbotPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:FollinaQbotId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-FollinaQbotEnvironment{$p=Get-FollinaQbotPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:FollinaQbotId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beach,$p.Payloads,$p.Staging,$p.Hosts,$p.Evidence,$p.Logs)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:FollinaQbotId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-FollinaQbotManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-FollinaQbotFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-FollinaQbotManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-FollinaQbotDecoy{param([string]$Path,[string]$Role);New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-FollinaQbotManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Invoke-FollinaQbotDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='WINWORD.EXE');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','FOLLINA-QBOT-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-FollinaQbotManifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-FollinaQbotLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-FollinaQbotManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-FollinaQbotTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-FollinaQbotPaths;[ordered]@{timestampUtc=$script:FollinaQbotAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-FollinaQbotSummary{param($Paths);Write-FollinaQbotFile $Paths.Summary "FollinaQbotSim complete.`nSource: $script:FollinaQbotUrl`nObserved window represented: two days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo exploit, download, malware, task/registry/Defender change, injection, credential/browser access, directory/share/remote action, RMM install, port scan, real document access, IOC contact, or exfiltration occurred." 'operator summary'}
