#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\FollinaQbotSim-utilities.ps1";Assert-FollinaQbotSafety -LabConfirmed:$LabConfirmed;$p=Initialize-FollinaQbotEnvironment
$beacon=Join-Path $p.Payloads 'cobalt-explorer.exe';New-FollinaQbotDecoy $beacon 'Injected Cobalt explorer stand-in';Invoke-FollinaQbotDecoy $beacon 'explorer.exe injected Cobalt HTTPS /maximum.png /dividend postex_4c14' 'Qbot explorer.exe';Invoke-FollinaQbotLoopback 443 '190.123.44.126 / mssfr.icu Cobalt Strike' 'HTTPS marker'
Write-FollinaQbotFile(Join-Path $p.Payloads 'AdFind.exe')'INERT ADFIND-NAME CANARY. Not a PE file.''AdFind canary';foreach($c in @('nltest /domain_trusts /all_trusts','net group "domain controllers" /dom','net group "domain admins" /dom','AdFind -f objectcategory=computer','ping -n 1 LAB-DC01')){Invoke-FollinaQbotDecoy $beacon $c 'explorer.exe'}
$cred=@{QbotCredentialManagerAccess=$false;LSASSHandlesOpened=0;reportedAccessMasks=@('0x1410','0x1FFFFF');LSASSBytesRead=0;credentialsCollected=0;browserWebCacheRead=$false;esentutlExecuted=$false;OutlookDataRead=$false};Write-FollinaQbotFile(Join-Path $p.Evidence 'credential-browser-negative-record.json')($cred|ConvertTo-Json)'credential safety record';Write-FollinaQbotFile(Join-Path $p.Staging 'WebCacheV01.dat.canary')'GENERATED BROWSER-DATA CANARY. No browser database was read.''browser collection canary'
$remote=@{QbotDLLsCreatedRemotely=0;SMBCopies=0;remoteServicesCreated=0;remoteHostsTouched=0;DefenderExclusionsAdded=0;securityControlsChanged=$false;RDPSessions=0};Write-FollinaQbotFile(Join-Path $p.Evidence 'remote-defender-negative-record.json')($remote|ConvertTo-Json)'remote safety record';foreach($port in @(445,135,3389)){Invoke-FollinaQbotLoopback $port "Qbot SMB/service and RDP movement marker port $port" 'lateral marker'}
foreach($n in @('client32.exe','setup_undefined.msi','AgentPackageHeartbeat.exe','SplashtopStreamer3500.exe')){if($n-like'*.msi'){Write-FollinaQbotFile(Join-Path $p.Payloads $n)"INERT MSI-NAME CANARY $n. Not an installer."'RMM canary'}else{New-FollinaQbotDecoy(Join-Path $p.Payloads $n)"Signed cmd.exe stand-in for $n"}};Write-FollinaQbotFile(Join-Path $p.Evidence 'rmm-negative-record.json')(@{NetSupportInstalled=$false;AteraInstalled=$false;SplashtopInstalled=$false;servicesCreated=0;softwareRegistryValuesWritten=0;domainControllerAccessed=$false}|ConvertTo-Json)'RMM safety record'
Add-FollinaQbotTimeline 1 collection 'esentutl browser extraction and possible Outlook collection represented' @{realDataRead=$false;techniques=@('T1555.003','T1555.004')};Add-FollinaQbotTimeline 2 lateral-movement 'Qbot DLL SMB copies, Defender exclusions, and remote service execution represented' @{remoteHostsTouched=0;securityControlsChanged=$false;techniques=@('T1570','T1569.002')};Add-FollinaQbotTimeline 3 execution 'Injected Cobalt beacon begins discovery and LSASS access evidence' @{processesInjected=0;LSASSAccessed=$false};Add-FollinaQbotTimeline 10 persistence 'NetSupport on workstation then RDP to DC and Atera/Splashtop deployment represented' @{RDPSessions=0;softwareInstalled=0;technique='T1219'}
