#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\MacroNokoSim-utilities.ps1";Assert-MacroNokoSafety -LabConfirmed:$LabConfirmed;$p=Initialize-MacroNokoEnvironment
$cmd=Join-Path $p.Beach 'cmd.exe';New-MacroNokoDecoy $cmd 'IcedID/Cobalt discovery command stand-in';foreach($c in @('PowerShell beacon from aicsoftware.com:757/coin','rundll32 c:\windows\temp\1.dll,DllRegisterServer','GetSystem named pipe impersonation','arp -a','chcp 65001','ipconfig /all','net config workstation','net group Domain Admins /domain','net group Domain Computers /domain','net group enterprise admins /dom','net view /all /domain','nltest /domain_trusts /all_trusts','systeminfo','whoami /upn','scan TCP 1433','AdFind users groups computers OUs subnets trusts','adget Active Directory discovery','wmic remote OS caption and licensing','nslookup generated hostnames','scan RDP','WinRM lateral movement','RDP to compromised server')){Invoke-MacroNokoDecoy $cmd $c}
foreach($n in @('p1.dll','1.dll','1.bat','adfind.exe','adget.exe','7.exe','adfind.bat','ns.bat','ad.7z')){Write-MacroNokoFile(Join-Path $p.Payloads $n)"INERT TOOL-NAME CANARY: $n"'tool canary'}
$negative=[ordered]@{CreateRemoteThread=$false;processesInjected=0;GetSystemPerformed=$false;lsassAccessed=$false;grantedAccessReported='0x1010';credentialsRead=0;directoryQueries=0;portScans=0;shareOrPasswordFilesRead=0;WmiCommands=0;WinRMSessions=0;RdpSessions=0;remoteHostsTouched=0};Write-MacroNokoFile(Join-Path $p.Evidence 'cobalt-discovery-lateral-negative-record.json')($negative|ConvertTo-Json)'negative evidence'
foreach($h in @('DC-01','FILE-01','APP-01','WKSTN-01')){New-Item -Path(Join-Path $p.Hosts $h)-ItemType Directory -Force|Out-Null};Write-MacroNokoFile(Join-Path $p.Staging 'ad.7z')'INERT ARCHIVE-NAME CANARY. No AD data and not an archive.''collection canary';Write-MacroNokoFile(Join-Path $p.Staging 'passwords-canary.docx')'GENERATED PASSWORD-DOCUMENT NAME CANARY. Contains no credentials and was not opened off-host.''credential file canary'
foreach($t in @(@(8080,'137.74.104.108 IcedID BackConnect VNC'),@(757,'23.29.115.152 aicsoftware.com Cobalt Strike'),@(8080,'23.29.115.152 aicsoftware.com Cobalt Strike'),@(8081,'50.3.132.232 iconnectgs.com Cobalt Strike'),@(443,'5.8.18.242 Cobalt Strike'),@(443,'dropmefiles.com Edge/VNC web-service marker'),@(443,'45.61.139.126 off-network canary-open source'))){Invoke-MacroNokoLoopback $t[0] $t[1] 'reported network marker'}
Add-MacroNokoTimeline 2 command-and-control 'IcedID loaded PowerShell and DLL Cobalt Strike beacons' @{downloads=0;beaconsExecuted=$false};Add-MacroNokoTimeline 2.1 credential-access 'GetSystem and LSASS access on beachhead represented' @{credentialsAccessed=$false;techniques=@('T1134.001','T1003.001')};Add-MacroNokoTimeline 3 discovery 'Port 1433 scan, shares, and password-file interest represented' @{scans=0;filesRead=0};Add-MacroNokoTimeline 72 discovery 'Day-four DC computer and privileged-group enumeration represented' @{directoryQueries=0};Add-MacroNokoTimeline 120 command-and-control 'Day-six IcedID VNC launched Edge and visited file-transfer service' @{browserDownload=$false;remoteControl=$false;techniques=@('T1219','T1102')};Add-MacroNokoTimeline 128 discovery 'Adget, AdFind, WMI, nslookup, RDP scan, and continued pivoting represented' @{realQueries=0;remoteHostsTouched=0;techniques=@('T1047','T1021.006','T1021.001')}
