#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\MacroNokoSim-utilities.ps1";Assert-MacroNokoSafety -LabConfirmed:$LabConfirmed;$p=Initialize-MacroNokoEnvironment
foreach($n in @('1.bat','2.bat','3.bat','4.bat','5.bat','6.bat','p.bat')){Write-MacroNokoFile(Join-Path $p.Payloads $n)"@REM INERT NOKOYAWA DEPLOYMENT CANARY $n"'batch canary'}
$mstdc=Join-Path $p.Payloads 'mstdc.exe';New-MacroNokoDecoy $mstdc 'renamed PsExec service binary stand-in' '3c19fee379b4882971834a3d38f3f8b86de560114274375560433778cd505748';$k=Join-Path $p.Payloads 'k.exe';New-MacroNokoDecoy $k 'Nokoyawa ransomware stand-in' '7095beafff5837070a89407c1bf3c6acf8221ed786e0697f6c578d4c3de0efd6';Invoke-MacroNokoDecoy $mstdc 'PsExec -r mstdc -s -d -h c:\windows\temp\p.bat';Invoke-MacroNokoDecoy $k 'k.exe --config AWAYOKON network/hidden-drive/shadow-delete configuration'
foreach($hostName in @('DC-01','FILE-01','APP-01','WKSTN-01')){foreach($n in @('Finance.xlsx','Operations.docx','Database.bak')){$o=Join-Path $p.Impact "$hostName\$n";Write-MacroNokoFile $o "GENERATED ORIGINAL $hostName/$n remains intact."'impact original';Write-MacroNokoFile "$o.AWAYOKON.marker"'AWAYOKON MARKER ONLY. Original not encrypted.''impact marker'};Write-MacroNokoFile(Join-Path $p.Impact "$hostName\AWAYOKON-readme.txt")'Nokoyawa ransom-note canary. No live support or payment link.''note canary'}
$impact=[ordered]@{WmiCopies=0;PsexecServicesCreated=0;mstdcExecutedRemotely=$false;remoteHostsTouched=0;filesEncrypted=0;networkOrHiddenDrivesAccessed=$false;shadowCopiesDeleted=$false;extension='AWAYOKON';skipDirs=@('windows','program files','program files (x86)','appdata','programdata','system volume information');skipExts=@('.exe','.dll','.ini','.lnk','.url');ransomPaid=$false;reportedDemandUsd=200000};Write-MacroNokoFile(Join-Path $p.Evidence 'nokoyawa-impact-negative-record.json')($impact|ConvertTo-Json -Depth 6)'impact evidence';Invoke-MacroNokoLoopback 445 'WMI/SMB/PsExec domain-wide Nokoyawa deployment' 'SMB marker'
Add-MacroNokoTimeline 147 lateral-movement 'RDP staging server, k.exe, PsExec, and batch cluster represented' @{rdpSessions=0;remoteTransfers=0;servicesCreated=0};Add-MacroNokoTimeline 148 impact 'WMI/PsExec AWAYOKON Nokoyawa deployment represented with intact canaries' @{filesEncrypted=0;shadowCopiesChanged=$false;remoteHostsTouched=0;techniques=@('T1047','T1021.002','T1486')}
