#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:DiavolSimId='058-Bazar_Cobalt_AnyDesk_FileZilla_Diavol_42h';$script:DiavolSimUrl='https://thedfirreport.com/2021/12/13/diavol-ransomware/';$script:DiavolSimAnchor=(Get-Date).ToUniversalTime().AddHours(-42)
function Get-DiavolSimPaths{$r=Join-Path $env:PUBLIC 'DiavolSim';[ordered]@{Root=$r;Lure=Join-Path $r 'lure-canaries';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Staging=Join-Path $r 'staging';Impact=Join-Path $r 'impact-canaries';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.DiavolSim.owner'}}
function Assert-DiavolSimSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-DiavolSimManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-DiavolSimPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:DiavolSimId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-DiavolSimEnvironment{$p=Get-DiavolSimPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:DiavolSimId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Payloads,$p.Hosts,$p.Staging,$p.Impact,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:DiavolSimId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-DiavolSimManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-DiavolSimFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-DiavolSimManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-DiavolSimDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-DiavolSimManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-DiavolSimDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='rundll32.exe');$args=@('/d','/v:off','/c','echo','DIAVOL-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-DiavolSimManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-DiavolSimLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-DiavolSimManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-DiavolSimTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-DiavolSimPaths;[ordered]@{timestampUtc=$script:DiavolSimAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-DiavolSimSummary{param($Paths);Write-DiavolSimFile $Paths.Summary "DiavolSim complete.`nSource: $script:DiavolSimUrl`nThe 42-hour chronology and one-hour final deployment window are preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo download/ISO mount, malware, BITS/RMM install, injection, credential/LSASS/hive/Kerberos/Veeam access, scan/query, RDP/remote action, real collection/exfiltration, shadow/boot/service change, ransomware execution, or encryption occurred." 'operator summary'}
