#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:BazarContiId='067-BazarCall_Trickbot_Cobalt_Conti_2Day';$script:BazarContiUrl='https://thedfirreport.com/2021/08/01/bazarcall-to-conti-ransomware-via-trickbot-and-cobalt-strike/';$script:BazarContiAnchor=(Get-Date).ToUniversalTime().AddHours(-48.5)
function Get-BazarContiPaths{$r=Join-Path $env:PUBLIC 'BazarContiSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Dc=Join-Path $r 'generated-hosts\DC-CANARY-01';Evidence=Join-Path $r 'evidence';Pipes=Join-Path $r 'named-pipe-markers';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.BazarContiSim.owner'}}
function Assert-BazarContiSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-BazarContiManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-BazarContiPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:BazarContiId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-BazarContiEnvironment{$p=Get-BazarContiPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:BazarContiId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Hosts,$p.Dc,$p.Evidence,$p.Pipes)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:BazarContiId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-BazarContiManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedDcCanaryOnly=$true};$p}
function Write-BazarContiFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-BazarContiManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-BazarContiDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-BazarContiManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-BazarContiDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='wermgr.exe');$args=@('/d','/v:off','/c','echo','BAZAR-CONTI-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-BazarContiManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-BazarContiLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-BazarContiManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-BazarContiTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-BazarContiPaths;[ordered]@{timestampUtc=$script:BazarContiAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-BazarContiSummary{param($Paths);Write-BazarContiFile $Paths.Summary "BazarContiSim complete.`nSource: $script:BazarContiUrl`nInternal case: 4641`nThe two-day chronology and report-relative timing are preserved on a generated exercise axis.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malware, macro, injection, security change, credentials, LSASS/NTDS access, AD/WMI query, remote action, external C2, real exfiltration, user-data encryption, or ransomware deployment occurred." 'operator summary'}
