#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:UrsnifGiftId='040-Ursnif_ISO_CobaltStrike_WMI_RDP_5Day'
$script:UrsnifGiftUrl='https://thedfirreport.com/2023/01/09/unwrapping-ursnifs-gifts/'
$script:UrsnifGiftAnchor=(Get-Date).ToUniversalTime().AddHours(-120)
function Get-UrsnifGiftPaths{$r=Join-Path $env:PUBLIC 'UrsnifGiftSim';[ordered]@{Root=$r;ISO=Join-Path $r '3488164-mounted-canary';Beach=Join-Path $r 'BEACHHEAD';Hosts=Join-Path $r 'generated-hosts';Payloads=Join-Path $r 'payload-canaries';Staging=Join-Path $r 'staging';Evidence=Join-Path $r 'evidence';Logs=Join-Path $r 'generated-event-logs';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.UrsnifGiftSim.owner'}}
function Assert-UrsnifGiftSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-UrsnifGiftManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-UrsnifGiftPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:UrsnifGiftId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-UrsnifGiftEnvironment{$p=Get-UrsnifGiftPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:UrsnifGiftId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.ISO,$p.Beach,$p.Hosts,$p.Payloads,$p.Staging,$p.Evidence,$p.Logs)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:UrsnifGiftId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-UrsnifGiftManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-UrsnifGiftFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-UrsnifGiftManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Add-UrsnifGiftJsonLine{param([string]$Path,[hashtable]$Record,[string]$Purpose='generated event');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};$Record|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $Path -Encoding UTF8;Add-UrsnifGiftManifest generated-event $Path appended @{purpose=$Purpose;synthetic=$true}}
function New-UrsnifGiftDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-UrsnifGiftManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-UrsnifGiftDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$Parent='explorer.exe');$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','URSNIF-GIFT-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-UrsnifGiftManifest process $FilePath executed-signed-decoy @{reportedParent=$Parent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-UrsnifGiftLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-UrsnifGiftManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-UrsnifGiftTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-UrsnifGiftPaths;[ordered]@{timestampUtc=$script:UrsnifGiftAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-UrsnifGiftSummary{param($Paths);Write-UrsnifGiftFile $Paths.Summary "UrsnifGiftSim complete.`nSource: $script:UrsnifGiftUrl`nObserved window represented: about five days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo ISO mount, malware, registry change, injection, credential access, BITS download, remote action, software install, backup access, real collection, IOC contact, or exfiltration occurred." 'operator summary'}
