#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\UrsnifGiftSim-utilities.ps1";Assert-UrsnifGiftSafety -LabConfirmed:$LabConfirmed;$p=Initialize-UrsnifGiftEnvironment
$remote=Join-Path $p.Payloads 'wmiexec.exe';New-UrsnifGiftDecoy $remote 'Impacket wmiexec/WMI stand-in';Invoke-UrsnifGiftDecoy $remote 'wmiexec.py SUPPORT-ADMIN@LAB-DC01 -> cmd.exe /Q /c command 1> \\127.0.0.1\ADMIN$\output 2>&1' 'powershell.exe';foreach($port in @(135,445,49152)){Invoke-UrsnifGiftLoopback $port "LAB-DC01 WMI/DCERPC/SMB port $port" 'lateral-movement marker'}
foreach($name in @('AteraAgent.msi','SplashtopStreamer.msi')){Write-UrsnifGiftFile(Join-Path $p.Payloads $name)"INERT INSTALLER-NAME CANARY $name. Not an MSI and never installed."'RMM canary'}
$firefox=Join-Path $p.Payloads 'firefox.exe';New-UrsnifGiftDecoy $firefox 'DC Cobalt Strike executable beacon stand-in' '6c5338d84c208b37a4ec5e13baf6e1906bd9669e18006530bf541e1d466ba819';Invoke-UrsnifGiftDecoy $firefox 'firefox.exe Cobalt beacon on LAB-DC01; reported >150K connections total' 'WmiPrvSE.exe';Invoke-UrsnifGiftLoopback 443 '193.201.9.199:443 high-volume Cobalt marker (one marker, not 150K)' 'HTTPS marker'
Write-UrsnifGiftFile(Join-Path $p.Evidence 'lateral-rmm-negative-record.json')(@{credentialsUsed=$false;remoteHostsTouched=0;WMIRequests=0;SMBCopies=0;remoteProcesses=0;AteraInstalled=$false;SplashtopInstalled=$false;domainControllerAccessed=$false}|ConvertTo-Json)'lateral movement safety record'
foreach($target in @('LAB-DC01','LAB-WS01','LAB-BACKUP01')){Invoke-UrsnifGiftLoopback 3389 "$target proxied RDP through Cobalt beacon" 'RDP marker'}
$taskmgr=Join-Path $p.Payloads 'taskmgr.exe';New-UrsnifGiftDecoy $taskmgr 'Interactive RDP Task Manager stand-in';Invoke-UrsnifGiftDecoy $taskmgr 'C:\Windows\system32\taskmgr.exe /4' 'explorer.exe';$notepad=Join-Path $p.Payloads 'notepad.exe';New-UrsnifGiftDecoy $notepad 'Interactive Notepad stand-in';Invoke-UrsnifGiftDecoy $notepad 'NOTEPAD.EXE C:\Users\USER\Desktop\New Text Document.txt' 'explorer.exe'
$sessionLog=Join-Path $p.Logs 'RDP-and-Security.jsonl';Add-UrsnifGiftJsonLine $sessionLog @{eventId=4624;logonType=3;workstationName='WIN-RRRU9REOK18';authenticationPackage='NTLM V2';target='LAB-BACKUP01';logonOccurred=$false;synthetic=$true}'logon canary';Add-UrsnifGiftJsonLine $sessionLog @{provider='TerminalServices-LocalSessionManager';target='LAB-BACKUP01';durationMinutes=10;sessionOccurred=$false;synthetic=$true}'RDP session canary';Add-UrsnifGiftJsonLine $sessionLog @{provider='Sysmon';eventId=24;clipboardText='user: LAB\USER ip: 127.0.0.1 hostname: WIN-RRRU9REOK18';clipboardRead=$false;synthetic=$true}'clipboard event canary'
Write-UrsnifGiftFile(Join-Path $p.Staging '775E.bin')'GENERATED EXFILTRATION CANARY. Contains no organizational or captured data.''Ursnif upload canary';foreach($t in @('denterdrigx.com image upload','superliner.top image upload','5.42.199.83 image upload')){Invoke-UrsnifGiftLoopback 80 $t 'HTTP POST marker'}
Write-UrsnifGiftFile(Join-Path $p.Evidence 'outcome-negative-record.json')(@{backupConsoleOpened=$false;backupStateQueried=$false;backupChanges=0;processesReviewedOnRemoteHosts=0;clipboardRead=$false;realDataCollected=$false;bytesExfiltrated=0;reported775EDeletionExecuted=$false;artifactsRemoved=0}|ConvertTo-Json)'outcome safety record'
Add-UrsnifGiftTimeline 97 lateral-movement 'Impacket wmiexec pivot, SMB transfers, Atera/Splashtop MSI installs, and DC beacon represented' @{remoteHostsTouched=0;softwareInstalled=0;techniques=@('T1047','T1570','T1219')};Add-UrsnifGiftTimeline 112 exfiltration 'Ursnif image-masqueraded 775E.bin HTTP POST represented on loopback' @{realDataRead=$false;bytesTransferred=0;technique='T1041'};Add-UrsnifGiftTimeline 120 lateral-movement 'Proxied RDP to DC, hosts, and backup server with ten-minute review represented' @{RDPSessions=0;backupChanges=0;technique='T1021.001'}
