#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\UrsnifGiftSim-utilities.ps1";Assert-UrsnifGiftSafety -LabConfirmed:$LabConfirmed;$p=Initialize-UrsnifGiftEnvironment
Write-UrsnifGiftFile(Join-Path $p.ISO '3488164.iso')'INERT ISO-NAME CANARY. Not a disk image and never mounted.''ISO lure'
Write-UrsnifGiftFile(Join-Path $p.ISO '6570872.lnk')'INERT LNK-NAME CANARY. No shell-link data.''LNK lure'
foreach($n in @('me\by\.empty','me\here\.empty')){Write-UrsnifGiftFile(Join-Path $p.ISO $n)'EMPTY-DIRECTORY MARKER''ISO layout'}
Write-UrsnifGiftFile(Join-Path $p.ISO 'me\alsoOne.bat')'@REM INERT. Reported strings: hello cexe lldnur revreSretsigeRllD.''batch canary'
Write-UrsnifGiftFile(Join-Path $p.ISO 'me\canWell.js')'// INERT reverse-string loader canary; no WScript objects or execution.''JavaScript canary'
Write-UrsnifGiftFile(Join-Path $p.ISO 'me\itsIt.db')'INERT URSNIF DLL-NAME CANARY. Not a PE file.''Ursnif payload canary'
Write-UrsnifGiftFile(Join-Path $p.ISO 'or.jpg')'INERT JPEG-NAME CANARY. Not an image.''unused image canary'
$loader=Join-Path $p.ISO 'me\123.com';New-UrsnifGiftDecoy $loader 'Renamed legitimate rundll32 stand-in';Invoke-UrsnifGiftDecoy $loader '6570872.lnk -> alsoOne.bat -> wscript.exe canWell.js -> me\123.com me\itsIt.db,DllRegisterServer' 'explorer.exe'
$mshta=Join-Path $p.Payloads 'mshta.exe';New-UrsnifGiftDecoy $mshta 'Registry-resident Ursnif mshta stand-in';Invoke-UrsnifGiftDecoy $mshta 'mshta.exe about:<hta:application> read ActiveDevice then PowerShell aliases read MemoryJunk' 'explorer.exe'
Write-UrsnifGiftFile(Join-Path $p.Evidence 'registry-persistence-negative-record.json')(@{path='HKCU\Software\AppDataLow\Software\Microsoft\472A62F9-FA62-1196-3C6B-CED530CFE2D9';values=@('ActiveDevice','MemoryJunk');runValue='ManagerText';registryKeysCreated=0;registryValuesWritten=0;runKeyCreated=$false}|ConvertTo-Json -Depth 5)'registry safety record'
Write-UrsnifGiftFile(Join-Path $p.Evidence 'compile-injection-negative-record.json')(@{reportedApis=@('QueueUserAPC','GetCurrentThreadId','OpenThread','VirtualAlloc');AddTypeExecuted=$false;cscExecuted=$false;shellcodePresent=$false;processesInjected=0}|ConvertTo-Json)'injection safety record'
$cmd=Join-Path $p.Beach 'cmd.exe';New-UrsnifGiftDecoy $cmd 'Ursnif discovery process stand-in';$discover=@('wmic computersystem get domain','systeminfo.exe','net view','nslookup 127.0.0.1','tasklist.exe /SVC','driverquery.exe','reg.exe query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall /s','nltest /domain_trusts','net config workstation','nltest /domain_trusts /all_trusts','net view /all /domain','net view /all');foreach($c in $discover){Invoke-UrsnifGiftDecoy $cmd "cmd /C $c >> %TEMP%\BD2C.bin1" 'itsIt.db';Add-UrsnifGiftManifest discovery-command 'generated-commandline-only' represented @{reportedCommandLine=$c;executedDiscovery=$false}}
Write-UrsnifGiftFile(Join-Path $p.Staging 'BD2C.bin1')"GENERATED URSNIF DISCOVERY OUTPUT`nLAB-DOMAIN`nLAB-WS01`nNo system or domain query was run."'generated discovery canary'
foreach($t in @('superliner.top / 5.42.199.83','internetlines.in / 31.41.44.97','superlinez.top / 31.41.44.27','denterdrigx.com')){Invoke-UrsnifGiftLoopback 80 $t 'Ursnif HTTP marker'}
Add-UrsnifGiftTimeline 0 initial-access '3488164.iso mount and 6570872.lnk user execution represented' @{isoMounted=$false;techniques=@('T1553.005','T1204.002')};Add-UrsnifGiftTimeline .05 execution 'alsoOne.bat, canWell.js, renamed rundll32 123.com, and itsIt.db chain represented' @{malwareExecuted=$false;techniques=@('T1059.005','T1218.011')};Add-UrsnifGiftTimeline .2 persistence 'Registry-resident ActiveDevice/MemoryJunk payload and ManagerText Run key represented' @{registryChanged=$false;technique='T1547.001'};Add-UrsnifGiftTimeline .5 discovery 'Automated Ursnif discovery and BD2C.bin1 staging represented' @{realQueriesExecuted=0;techniques=@('T1082','T1057','T1482','T1018')}
