#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
$config=[pscustomobject]@{
 Id='009-Blurring_Lines_Play_RansomHub_DragonForce';RootName='BlurringLinesSim';Source='https://thedfirreport.com/2025/09/08/blurring-the-lines-intrusion-shows-connection-with-three-major-ransomware-gangs/';Title='Blurring the Lines: Intrusion Shows Connection With Three Major Ransomware Gangs';DurationMinutes=8640;TimelineNote='Generated six-day axis preserves day-one, day-two, and day-six ordering. Ransomware was not deployed in the report or this scenario.'
 IOCs=[ordered]@{sectopRat='45.141.87.55:9000,15647';systemBC='149.28.101.219:443';betruger=@('80.78.28.149:80,443','504e1c95.host.njalla.net');exfil='144.202.61.209';staging='C:\Users\Public\Music';reportedAccount='Admon (credential retained only in source report metadata)';rdpHosts=@('DESCTOP-QPITRY','DESKTOP-A1HRTMJ','DESKTOP-PGD76HT','WIN-FLGU1CC210K')}
 Files=@('cmd.exe','EarthTime.exe','MSBuild.exe','WakeWordEngine.dll','conhost.dll','ccs.exe','GT_NET.exe','GRB_NET.exe','SharpHound.exe','AdFind.exe','WinRAR.exe','PsExec.exe','WinSCP.exe','FS64.exe')|ForEach-Object{[pscustomobject]@{path="payload-canaries\$_";role='report-named stand-in';publishedHash='see source report'}}
 Artifacts=@(
  [pscustomobject]@{path='generated-persistence\QuickAgent2-BITS.json';content='{"reportedJob":"QuickAgent2","reportedFile":"ChromeAlt_dbg.exe","created":false}';purpose='BITS metadata'},[pscustomobject]@{path='generated-persistence\Admon-account.json';content='{"reportedAccount":"Admon","credentialStored":false,"created":false}';purpose='account metadata'},[pscustomobject]@{path='generated-hosts\DC-CANARY\Windows\NTDS\DCSync-marker.json';content='{"reportedTechnique":"DCSync","directoryAccess":false,"credentialsAccessed":0}';purpose='credential marker'},[pscustomobject]@{path='evidence\ExportData.db';content='GENERATED VEEAM-DATA CANARY; no credentials.';purpose='credential canary'},[pscustomobject]@{path='evidence\data.zip.marker';content='Generated archive marker; no host data collected.';purpose='collection marker'},[pscustomobject]@{path='evidence\prior-victim-netscan.xml';content='<generated-canary attribution="DragonForce" realVictimData="false" />';purpose='attribution artifact'},[pscustomobject]@{path='evidence\outcome.txt';content='Detection prevented ransomware. Realized impact represented: persistent access and exfiltration; bytes transferred: 0.';purpose='outcome'})
 Commands=@(
  [pscustomobject]@{file='payload-canaries\EarthTime.exe';reported='explorer.exe -> EarthTime.exe -> cmd.exe -> MSBuild.exe';parent='explorer.exe'},[pscustomobject]@{file='payload-canaries\MSBuild.exe';reported='MSBuild retrieves SectopRAT config from Pastebin';parent='cmd.exe'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='rundll32 WakeWordEngine.dll,Reset (SystemBC)';parent='MSBuild.exe'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='BITS QuickAgent2, Startup link, Admon account, PsExec -s, and DCSync';parent='operator'},[pscustomobject]@{file='payload-canaries\GT_NET.exe';reported='Grixba scanning with NetScan, SharpHound, and AdFind';parent='RDP session'},[pscustomobject]@{file='payload-canaries\WinRAR.exe';reported='WinRAR archives file-share data';parent='RDP session'},[pscustomobject]@{file='payload-canaries\WinSCP.exe';reported='WinSCP clear-text FTP to 144.202.61.209 for about 15 minutes';parent='RDP session'},[pscustomobject]@{file='payload-canaries\ccs.exe';reported='Betruger injects into 172 processes';parent='MSBuild.exe'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='Impacket wmiexec: WmiPrvSE.exe -> cmd.exe DC enumeration';parent='WmiPrvSE.exe'})
 Network=@(
  [pscustomobject]@{port=9000;target='45.141.87.55';role='SectopRAT'},[pscustomobject]@{port=15647;target='45.141.87.55';role='SectopRAT'},[pscustomobject]@{port=443;target='149.28.101.219';role='SystemBC'},[pscustomobject]@{port=443;target='80.78.28.149 / 504e1c95.host.njalla.net';role='Betruger'},[pscustomobject]@{port=21;target='144.202.61.209';role='FTP exfil'},[pscustomobject]@{port=3389;target='reported internal hosts via SystemBC';role='RDP marker'})
 Timeline=@(
  [pscustomobject]@{offset=0;phase='day-1-initial-access';event='EarthTime, MSBuild, SectopRAT, and SystemBC';details=@{downloads=0;injection=$false}},[pscustomobject]@{offset=360;phase='day-1-persistence-credential';event='BITS, Startup, Admon, PsExec, and DCSync metadata';details=@{systemChanges=0;credentialsAccessed=0}},[pscustomobject]@{offset=1440;phase='day-2-lateral-discovery';event='RDP, Grixba, NetScan, Veeam, SharpHound, and AdFind';details=@{remoteActions=0}},[pscustomobject]@{offset=1800;phase='day-2-exfiltration';event='WinRAR and 15-minute WinSCP FTP sequence';details=@{bytesTransferred=0}},[pscustomobject]@{offset=7200;phase='day-6-c2';event='Betruger and wmiexec sequence';details=@{processesInjected=0;remoteActions=0}},[pscustomobject]@{offset=8640;phase='outcome';event='three-gang attribution; ransomware prevented';details=@{filesEncrypted=0}})
}
. (Join-Path $PSScriptRoot '..\LabSafeScenarioCore.ps1');Invoke-DFIRLabScenario -Config $config -LabConfirmed:$LabConfirmed
