#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\SmuggleNokoSim-utilities.ps1";Assert-SmuggleNokoSafety -LabConfirmed:$LabConfirmed;$p=Initialize-SmuggleNokoEnvironment
Write-SmuggleNokoFile(Join-Path $p.Lure 'redacted-invoice-10.31.22.html')'INERT HTML SMUGGLING CANARY. No script, data blob, or download.''HTML lure';Write-SmuggleNokoFile(Join-Path $p.Lure '8c11812d-65fd-48ee-b650-296122a21067.zip')'INERT PASSWORD-PROTECTED ZIP-NAME CANARY. Not an archive.''ZIP canary';Write-SmuggleNokoFile(Join-Path $p.Lure 'invoice.iso')'INERT ISO-NAME CANARY. Not a disk image.''ISO canary'
Write-SmuggleNokoFile(Join-Path $p.Iso 'documents-9771.lnk')'INERT LNK-NAME CANARY. No shell link data.''LNK canary';Write-SmuggleNokoFile(Join-Path $p.Iso 'demurest.cmd')'@REM INERT command canary. No xcopy, execution, or file operation.''batch canary';Write-SmuggleNokoFile(Join-Path $p.Iso 'pimpliest_kufic.png')'INERT finance-document image canary.''lure image';Write-SmuggleNokoFile(Join-Path $p.Iso 'templates544.png')'INERT ICEDID DLL-NAME CANARY. Not an image or PE file.''IcedID canary'
$entails=Join-Path $p.Beach 'entails.exe';New-SmuggleNokoDecoy $entails 'renamed rundll32 filename stand-in';Invoke-SmuggleNokoDecoy $entails 'Explorer -> documents-9771.lnk -> demurest.cmd -> xcopy rundll32 entails.exe -> entails.exe templates544.png'
$task=[ordered]@{name='{E5C1C7DB-E36E-5B16-8E3A-6226D7E53A67}';interval='PT1H';logonTrigger=$true;runLevel='HighestAvailable';command='rundll32 Izjeubaw64.dll,#1 --oyxo=EdgeDecrease\license.dat';created=$false};Write-SmuggleNokoFile(Join-Path $p.Evidence 'icedid-task-negative-record.json')($task|ConvertTo-Json)'task evidence';foreach($t in @('trentonkaizerfak.com 159.89.12.125:80','questdisar.com 5.255.103.16:443','pikchayola.pics 5.255.103.16:443')){Invoke-SmuggleNokoLoopback 443 $t 'IcedID marker'}
Add-SmuggleNokoTimeline 0 initial-access 'Thread-hijacked HTML, password ZIP, ISO, visible LNK, and hidden files represented' @{downloads=0;techniques=@('T1566.001','T1027.006','T1204.002')};Add-SmuggleNokoTimeline .05 execution 'Renamed rundll32/IcedID ancestry and lure image represented' @{malwareExecuted=$false;techniques=@('T1036.005','T1218.011','T1059.003')};Add-SmuggleNokoTimeline .1 persistence 'Hourly/logon IcedID task represented without registration' @{taskCreated=$false;technique='T1053.005'}
