#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:SmuggleNokoId='033-HTMLSmuggling_IcedID_CobaltStrike_Nokoyawa_12h';$script:SmuggleNokoUrl='https://thedfirreport.com/2023/08/28/html-smuggling-leads-to-domain-wide-ransomware/';$script:SmuggleNokoAnchor=(Get-Date).ToUniversalTime().AddHours(-12)
function Get-SmuggleNokoPaths{$r=Join-Path $env:PUBLIC 'SmuggleNokoSim';[ordered]@{Root=$r;Lure=Join-Path $r 'html-smuggling-lure';Iso=Join-Path $r 'mounted-iso-replica';Beach=Join-Path $r 'BEACHHOST';Hosts=Join-Path $r 'generated-hosts';Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Impact=Join-Path $r 'impact-canaries';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.SmuggleNokoSim.owner'}}
function Assert-SmuggleNokoSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-SmuggleNokoManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-SmuggleNokoPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:SmuggleNokoId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-SmuggleNokoEnvironment{$p=Get-SmuggleNokoPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:SmuggleNokoId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Iso,$p.Beach,$p.Hosts,$p.Payloads,$p.Evidence,$p.Impact)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:SmuggleNokoId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-SmuggleNokoManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return $p}
function Write-SmuggleNokoFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-SmuggleNokoManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-SmuggleNokoDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-SmuggleNokoManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;hashMatch=$false}}
function Invoke-SmuggleNokoDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','SMUGGLE-NOKO-CANARY',$safe);$proc=Start-Process $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-SmuggleNokoManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-SmuggleNokoLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-SmuggleNokoManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-SmuggleNokoTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-SmuggleNokoPaths;[ordered]@{timestampUtc=$script:SmuggleNokoAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-SmuggleNokoSummary{param($Paths);Write-SmuggleNokoFile $Paths.Summary "SmuggleNokoSim complete.`nSource: $script:SmuggleNokoUrl`nTime to ransomware: just over 12 hours.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malware, task, injection, LSASS/session credential access, directory query, RDP, WMI/PsExec, remote service, shadow deletion, or encryption occurred." 'operator summary'}
