#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:H20Id='069-Hancitor_Cobalt_SMB_Service_20m';$script:H20Url='https://thedfirreport.com/2021/06/28/hancitor-continues-to-push-cobalt-strike/';$script:H20Anchor=(Get-Date).ToUniversalTime().AddMinutes(-25)
function Get-H20Paths{$r=Join-Path $env:PUBLIC 'Hancitor20Sim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Pipes=Join-Path $r 'named-pipe-markers';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.Hancitor20Sim.owner'}}
function Assert-H20Safety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw 'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-H20Manifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-H20Paths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:H20Id;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-H20Environment{$p=Get-H20Paths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:H20Id){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Hosts,$p.Evidence,$p.Pipes)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:H20Id -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-H20Manifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedHostsOnly=$true};$p}
function Write-H20File{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-H20Manifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-H20Decoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-H20Manifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-H20Decoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','HANCITOR-20-CANARY');$q=Start-Process -FilePath $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$q.ExitCode;Add-H20Manifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-H20Loopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-H20Manifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-H20Timeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-H20Paths;[ordered]@{timestampUtc=$script:H20Anchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Write-H20Summary{param($p);Write-H20File $p.Summary "Hancitor20Sim complete.`nSource: $script:H20Url`nInternal case: 4301`nThe report's approximately twenty-minute movement timing is preserved.`nArtifacts remain; cleanup is separate.`nNo malware, macro, injection, scan, share, service, LSASS access, remote action, self-deletion, external C2, or impact occurred." summary}
