#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:SxId='098-Settra_MeshAgent_BYOVD_Ransomware';$script:SxUrl='https://www.huntress.com/blog/new-settra-ransomware-variant';$script:SxAnchor=(Get-Date).ToUniversalTime().AddMinutes(-90)
function Get-SxPaths{$r=Join-Path $env:PUBLIC 'SettraSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Hosts=Join-Path $r 'generated-hosts';Registry=Join-Path $r 'generated-registry';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.SettraSim.owner'}}
function Assert-SxSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated, disposable lab VM.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-SxManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-SxPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:SxId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-SxEnvironment{$p=Get-SxPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:SxId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Evidence,$p.Hosts,$p.Registry)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:SxId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};Add-SxManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-SxFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-SxManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Write-SxJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-SxFile $Path ($Object|ConvertTo-Json -Depth 15) $Purpose}
function New-SxDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='none');New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-SxManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256}}
function Invoke-SxDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','SETTRA-LAB-CANARY');$q=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -NoNewWindow;$null=$q.ExitCode;Add-SxManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-SxLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-SxManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-SxTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-SxPaths;[ordered]@{timestampUtc=$script:SxAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-SxSummary{param($p);Write-SxFile $p.Summary "SettraSim complete.`nSource: $script:SxUrl`nRepresents the two Huntress-investigated Settra incidents (July retail/consumer-services and September manufacturing), including MeshAgent RMM persistence, September BYOVD (gdrv.sys), the domain-named <domain>_win64.exe ransomware, RESTORE_FILES.txt notes, the exact cleared/attempted event-log list (including the misspelled Defender log that failed to clear), reagentc/diskpart/cipher recovery-inhibition, and the WIN-LIVFRVQFMKO attribution artifact.`nNo RMM was installed, no driver was loaded, no security tool was impaired, no log was cleared, no recovery option was disabled, no free space was wiped, and no file was encrypted. Report IOC addresses were never contacted; only 127.0.0.1 was touched with zero bytes.`nArtifacts remain for investigation; cleanup is separate." summary}
