#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:CSGuide1Id='065-CobaltStrike_DefendersGuide1_Endpoint_Lateral';$script:CSGuide1Url='https://thedfirreport.com/2021/08/29/cobalt-strike-a-defenders-guide/';$script:CSGuide1Anchor=(Get-Date).ToUniversalTime().AddHours(-3)
function Get-CSGuide1Paths{$r=Join-Path $env:PUBLIC 'CSGuide1Sim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Pipes=Join-Path $r 'named-pipe-markers';Events=Join-Path $r 'event-markers';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.CSGuide1Sim.owner'}}
function Assert-CSGuide1Safety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw 'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-CSGuide1Manifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-CSGuide1Paths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:CSGuide1Id;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-CSGuide1Environment{$p=Get-CSGuide1Paths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:CSGuide1Id){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Hosts,$p.Pipes,$p.Events,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:CSGuide1Id -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-CSGuide1Manifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';guideComposite=$true;generatedDcCanaryOnly=$true};$p}
function Write-CSGuide1File{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-CSGuide1Manifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-CSGuide1Decoy{param([string]$Path,[string]$Role);New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-CSGuide1Manifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedHash='none in guide'}}
function Invoke-CSGuide1Decoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='initial-malware.exe');$args=@('/d','/v:off','/c','echo','CS-GUIDE1-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-CSGuide1Manifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-CSGuide1Loopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-CSGuide1Manifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-CSGuide1Timeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-CSGuide1Paths;[ordered]@{timestampUtc=$script:CSGuide1Anchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8}
function Add-CSGuide1EventMarker{param([int]$EventId,[string]$Provider,[string]$Context);$p=Get-CSGuide1Paths;Write-CSGuide1File(Join-Path $p.Events "$Provider-$EventId-$([guid]::NewGuid().ToString('N').Substring(0,8)).json")(@{eventId=$EventId;provider=$Provider;reportedContext=$Context;actualEventWritten=$false;syntheticMarker=$true}|ConvertTo-Json)'event marker'}
function Write-CSGuide1Summary{param($Paths);Write-CSGuide1File $Paths.Summary "CSGuide1Sim complete.`nSource: $script:CSGuide1Url`nThis is an ordered composite exercise from a defender guide, not a reconstruction of one intrusion.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo Cobalt Strike, shellcode, named pipe, injection/hollowing, discovery/AD query, token/service/registry action, LSASS/browser/DCSync credential access, authentication, remote SMB/WMI/WinRM/RDP/SOCKS action, Zerologon, or external C2 occurred." 'operator summary'}
