#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:IcedAlphvId='024-IcedID_ScreenConnect_CSharpStreamer_ALPHV';$script:IcedAlphvUrl='https://thedfirreport.com/2024/06/10/icedid-brings-screenconnect-and-csharp-streamer-to-alphv-ransomware-deployment/';$script:IcedAlphvAnchor=(Get-Date).ToUniversalTime().AddHours(-180)
function Get-IcedAlphvPaths{$r=Join-Path $env:PUBLIC 'IcedIDScreenConnectALPHVSim';[ordered]@{Root=$r;Beachhead=Join-Path $r 'beachhead';Email=Join-Path $r 'email-lure';Evidence=Join-Path $r 'evidence';Hosts=Join-Path $r 'generated-hosts';Shares=Join-Path $r 'generated-file-server\Shares';Staging=Join-Path $r 'collection-staging';Impact=Join-Path $r 'impact-canary';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.IcedIDScreenConnectALPHVSim.owner'}}
function Assert-IcedAlphvSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-IcedAlphvManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-IcedAlphvPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:IcedAlphvId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8}
function Initialize-IcedAlphvEnvironment{$p=Get-IcedAlphvPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:IcedAlphvId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Beachhead,$p.Email,$p.Evidence,$p.Hosts,$p.Shares,$p.Staging,$p.Impact)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:IcedAlphvId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-IcedAlphvManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-IcedAlphvFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-IcedAlphvManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-IcedAlphvDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-IcedAlphvManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;match=$false}}
function Invoke-IcedAlphvDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$s=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','ICEDID-ALPHV-CANARY',$s);$x=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$x.ExitCode;Add-IcedAlphvManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');escaped=$true}}
function Invoke-IcedAlphvLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-IcedAlphvManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-IcedAlphvTimeline{param([int]$OffsetMinutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-IcedAlphvPaths;[ordered]@{timestampUtc=$script:IcedAlphvAnchor.AddMinutes($OffsetMinutes).ToString('o');offsetMinutes=$OffsetMinutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-IcedAlphvSummary{param($Paths);Write-IcedAlphvFile $Paths.Summary "IcedIDScreenConnectALPHVSim complete.`nSource: $script:IcedAlphvUrl`nSimulated dwell: about 180 hours across eight days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo live malware, real IOC connection, credential/LSASS/DCSync access, directory/share collection, remote execution, RMM installation, service/task change, backup deletion, or encryption occurred." 'operator summary'}
