#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
$config=[pscustomobject]@{
 Id='002-Fake Zoom Ends in BlackSuit Ransomware';RootName='BlackSuitZoomSim';Source='https://thedfirreport.com/2025/03/31/fake-zoom-ends-in-blacksuit-ransomware/';Title='Fake Zoom Ends in BlackSuit Ransomware';DurationMinutes=11640;TimelineNote='Generated 194-hour axis preserves the report nine-calendar-day ordering and little-over-194-hour time to ransomware.'
 IOCs=[ordered]@{lure='zoommanager.com';secondStage='78.47.105.28';sectopRat='45.141.87.218:9000,15647';bruteRatel=@('megupdate.com / 5.181.159.31','administrative-manufacturer-gw.aws-usw2.cloud-ara.tyk.io');cobalt='provincial-gaiters-gw.aws-use1.cloud-ara.tyk.io / 44.196.9.9';qdoor=@('88.119.167.239','143.244.146.183');exfil='mystuff.bublup.com'}
 Files=@(
  [pscustomobject]@{path='payload-canaries\cmd.exe';role='reported-command stand-in';publishedHash='none'},[pscustomobject]@{path='payload-canaries\Zoom_v_2.00.4.exe';role='d3f@ckloader stand-in';publishedHash='SHA256 3967b38f763b2e58b0679bc0178247b855c68d761187c71c2f1760b6882e473a'},[pscustomobject]@{path='payload-canaries\152.exe';role='IDAT loader host stand-in';publishedHash='SHA256 a05b592a971fe5011554013bcfe9a4aaf9cfc633bdd1fe3a8197f213d557b8d3'},[pscustomobject]@{path='payload-canaries\2905.dll';role='Brute Ratel stand-in';publishedHash='SHA256 b676dbc3e20fa7acb92c1cc0a90132798c482dbf43211793abb937bd43295d42'},[pscustomobject]@{path='payload-canaries\3004.dll';role='unexecuted Brute Ratel stand-in';publishedHash='SHA256 63dcff4bad9576794c3a412cf8dae83b807a138cc09c4de64485bb8ec991cd4b'},[pscustomobject]@{path='payload-canaries\run32.exe';role='Cobalt Strike stand-in';publishedHash='SHA256 58dde623e36fefe8038aa2d579d3d1f5394b96ea3623b3125876137b4ee08d80'},[pscustomobject]@{path='payload-canaries\svhost.exe';role='QDoor stand-in';publishedHash='SHA256 e6cfae572f777def856878e36bbacfaa82cb5662fc97c1492e2367a105dddbc9'},[pscustomobject]@{path='payload-canaries\PsExec.exe';role='deployment stand-in';publishedHash='SHA256 3337e3875b05e0bfba69ab926532e3f179e8cfbf162ebb60ce58a0281437a7ef'},[pscustomobject]@{path='payload-canaries\123.exe';role='BlackSuit stand-in';publishedHash='SHA256 ecb0b3057163cd25c989a66683cfb47c19f122407cbbb49b1043e908c4f07ad1'},[pscustomobject]@{path='payload-canaries\WinRAR.exe';role='archive-tool stand-in';publishedHash='none'})
 Artifacts=@(
  [pscustomobject]@{path='payload-canaries\21.cmd';content='GENERATED INERT DEFENDER/ATTRIB SCRIPT CANARY; never interpreted.';purpose='initial loader script'},[pscustomobject]@{path='payload-canaries\4554.cmd';content='GENERATED INERT EXTRACTION SCRIPT CANARY; never interpreted.';purpose='loader script'},[pscustomobject]@{path='payload-canaries\artillery.mdb';content='GENERATED ENCRYPTED-PAYLOAD-SHAPED CANARY.';purpose='IDAT payload'},[pscustomobject]@{path='payload-canaries\COPY.bat';content='GENERATED INERT REMOTE-COPY SCRIPT CANARY; never interpreted.';purpose='deployment artifact'},[pscustomobject]@{path='payload-canaries\EXE.bat';content='GENERATED INERT REMOTE-EXECUTION SCRIPT CANARY; never interpreted.';purpose='deployment artifact'},[pscustomobject]@{path='payload-canaries\comps1.txt';content='WKSTN-01`r`nWKSTN-02`r`nFILE-CANARY';purpose='generated target list'},[pscustomobject]@{path='evidence\collection.rar.marker';content='Generated archive marker only; no real file-share data.';purpose='collection marker'},[pscustomobject]@{path='generated-hosts\FILE-CANARY\Shares\finance.xlsx';content='GENERATED USER-DATA CANARY; remains intact.';purpose='impact canary'},[pscustomobject]@{path='generated-hosts\FILE-CANARY\Shares\finance.xlsx.blacksuit-marker';content='Sidecar only; original unchanged.';purpose='impact marker'},[pscustomobject]@{path='generated-hosts\FILE-CANARY\README.BlackSuit.txt';content='BLACKSUIT NOTE-SHAPED CANARY. No data was encrypted.';purpose='ransom-note canary'})
 Commands=@(
  [pscustomobject]@{file='payload-canaries\Zoom_v_2.00.4.exe';reported='Zoom_v_2.00.4.exe -> 21.cmd -> 4554.cmd';parent='explorer.exe'},[pscustomobject]@{file='payload-canaries\152.exe';reported='152.exe / IDAT injects SectopRAT into MSBuild.exe';parent='4554.cmd'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='regsvr32.exe 2905.dll (Brute Ratel)';parent='SectopRAT'},[pscustomobject]@{file='payload-canaries\run32.exe';reported='Cobalt Strike beacon injects into dllhost.exe and accesses LSASS';parent='Brute Ratel'},[pscustomobject]@{file='payload-canaries\cmd.exe';reported='Cobalt Strike psexec_psh remote services plus nltest/net/systeminfo discovery';parent='dllhost.exe'},[pscustomobject]@{file='payload-canaries\svhost.exe';reported='wmic /node:<host> process call create svhost.exe 143.244.146.183';parent='cmd.exe'},[pscustomobject]@{file='payload-canaries\WinRAR.exe';reported='WinRAR.exe a -ep1 -scul -r0 -iext -imon1 -- . G:\REDACTED';parent='RDP session'},[pscustomobject]@{file='payload-canaries\PsExec.exe';reported='COPY.bat and EXE.bat use comps[1-4].txt to deploy and execute 123.exe';parent='DC staging session'},[pscustomobject]@{file='payload-canaries\123.exe';reported='BlackSuit executes and vssadmin deletes shadow copies';parent='PsExec/WMIC'})
 Network=@(
  [pscustomobject]@{port=443;target='zoommanager.com / Steam profile / Pastebin';role='lure/config'},[pscustomobject]@{port=80;target='78.47.105.28';role='second-stage ZIPs'},[pscustomobject]@{port=9000;target='45.141.87.218';role='SectopRAT'},[pscustomobject]@{port=443;target='Brute Ratel and Cobalt Strike domains/IPs';role='C2'},[pscustomobject]@{port=443;target='88.119.167.239 / 143.244.146.183';role='QDoor'},[pscustomobject]@{port=443;target='mystuff.bublup.com';role='934.38 MB reported exfiltration marker'},[pscustomobject]@{port=3389;target='reported internal file server and DC';role='QDoor-proxied RDP marker'})
 Timeline=@(
  [pscustomobject]@{offset=0;phase='initial-access';event='fake Zoom and d3f@ckloader chain';details=@{downloads=0;defenderChanges=0}},[pscustomobject]@{offset=30;phase='execution-c2';event='IDAT/SectopRAT in MSBuild';details=@{injection=$false}},[pscustomobject]@{offset=11520;phase='day-9-execution';event='Brute Ratel and Cobalt Strike deployment';details=@{lsassAccessed=$false}},[pscustomobject]@{offset=11560;phase='lateral-movement';event='remote-service, QDoor, and RDP patterns';details=@{remoteActions=0}},[pscustomobject]@{offset=11600;phase='collection-exfiltration';event='WinRAR and Bublup sequence';details=@{reportedMegabytes=934.38;bytesTransferred=0}},[pscustomobject]@{offset=11640;phase='impact';event='PsExec/WMIC BlackSuit deployment represented';details=@{filesEncrypted=0;shadowCopiesDeleted=0}})
}
. (Join-Path $PSScriptRoot '..\LabSafeScenarioCore.ps1');Invoke-DFIRLabScenario -Config $config -LabConfirmed:$LabConfirmed
