#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:YearReviewId='037-2022_YearInReview_Composite_Trends';$script:YearReviewUrl='https://thedfirreport.com/2023/03/06/2022-year-in-review/';$script:YearReviewAnchor=(Get-Date).ToUniversalTime().AddHours(-24)
function Get-YearReviewPaths{$r=Join-Path $env:PUBLIC 'YearReview2022Sim';[ordered]@{Root=$r;Access=Join-Path $r 'chain-1-access-execution';Middle=Join-Path $r 'chain-2-persistence-credential-discovery';Outcome=Join-Path $r 'chain-3-movement-exfil-impact';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Impact=Join-Path $r 'impact-canaries';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\composite-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.YearReview2022Sim.owner'}}
function Assert-YearReviewSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-YearReviewManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-YearReviewPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:YearReviewId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-YearReviewEnvironment{$p=Get-YearReviewPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:YearReviewId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Access,$p.Middle,$p.Outcome,$p.Hosts,$p.Evidence,$p.Impact)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:YearReviewId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-YearReviewManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';aggregateComposite=$true};$p}
function Write-YearReviewFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-YearReviewManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-YearReviewDecoy{param([string]$Path,[string]$Role);New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-YearReviewManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Invoke-YearReviewDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','YEAR-REVIEW-CANARY',$safe);$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-YearReviewManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-YearReviewLoopback{param([int]$Port,[string]$ReportedTarget);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-YearReviewManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-YearReviewTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-YearReviewPaths;[ordered]@{timestampUtc=$script:YearReviewAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;aggregateComposite=$true;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-YearReviewSummary{param($Paths);Write-YearReviewFile $Paths.Summary "YearReview2022Sim complete.`nSource: $script:YearReviewUrl`nThis is a synthetic aggregate composite, not one observed intrusion.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malware, exploit, persistence, credential access, remote action, real collection, exfiltration, or encryption occurred." 'operator summary'}
