#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:TAId='079-Trickbot_Cobalt_NTDS_Overpass_NoRyuk';$script:TAUrl='https://thedfirreport.com/2021/01/11/trickbot-still-alive-and-well/';$script:TAAnchor=(Get-Date).ToUniversalTime().AddHours(-2)
function Get-TAPaths{$r=Join-Path $env:PUBLIC 'TrickAliveSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.TrickAliveSim.owner'}}
function Assert-TASafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-TAManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-TAPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:TAId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-TAEnvironment{$p=Get-TAPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:TAId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Hosts,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:TAId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-TAManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-TAFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-TAManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-TADecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-TAManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-TADecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','TRICK-ALIVE-CANARY');$q=Start-Process -FilePath $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$q.ExitCode;Add-TAManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-TALoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-TAManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-TATimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-TAPaths;[ordered]@{timestampUtc=$script:TAAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-TASummary{param($p);Write-TAFile $p.Summary "TrickAliveSim complete.`nSource: $script:TAUrl`nInternal case: 1012`nThe two-hour axis is generated ordering because the report publishes sequence but no duration.`nArtifacts remain; cleanup is separate.`nNo malware, injection, named pipe/token change, LDAP/domain discovery, LSASS/NTDS/credential access, WMI/SMB/service/PowerShell movement, ticket/hash use, exfiltration, or ransomware impact occurred." summary}
