#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\DagonSim-utilities.ps1";Assert-DagonSafety -LabConfirmed:$LabConfirmed;$p=Initialize-DagonEnvironment;if(-not(Test-Path(Join-Path $p.Evidence 'cobalt-execution.json'))){throw'Run phase 1 first'}
foreach($h in @('BEACHHEAD','DC1','FILE-SRV','VIRT-MGR','BACKUP-SRV','APP-SRV')){$d=Join-Path $p.Hosts $h;New-Item $d -ItemType Directory -Force|Out-Null;Write-DagonFile(Join-Path $d 'host-record.json')(([ordered]@{host=$h;synthetic=$true;SMB=$false;WMI=$false;WinRM=$false;AnyDesk=$false;domainControllerTouched=$false}|ConvertTo-Json))'synthetic host'}
foreach($n in @('Finance\budget.xlsx','Virtualization\hosts.docx','IT\password-inventory.canary.txt','Security\audit.pdf')){Write-DagonFile(Join-Path $p.Shares $n)"Generated canary $n. Contains no credential or user data." 'generated share canary'}
$aws=Join-Path $p.Exfil 'AWSCollector.ps1';Write-DagonFile $aws '# INERT AWSCollector name-only canary. No discovery, SMB, WMI, AWS, Telegram, service, shadow, or locker functions.' 'AWSCollector canary';$rclone=Join-Path $p.Exfil 'rclone.exe';New-DagonDecoy $rclone 'Rclone exfiltration decoy';$tools=@('Netscan.exe','Nbtscan.exe','Seatbelt.exe','Sharefinder.exe','AdFind.exe','speedtest.exe');foreach($n in $tools){New-DagonDecoy(Join-Path $p.Exfil $n)"$n discovery decoy"}
$collector=[ordered]@{modules=@('systeminfo','share discovery','remote WMI/WinRM','Rclone','AWS S3 upload','locker','Telegram status');reportedExfil=@('Rclone','AWS S3 bucket');generatedFilesOnly=$true;remoteCommands=0;directoryQueries=0;sharesRead=0;credentialsRead=0;bytesTransferred=0;awsRequests=0;telegramMessages=0;dryRunSupported=$true};Write-DagonFile(Join-Path $p.Evidence 'awscollector-capabilities.json')($collector|ConvertTo-Json -Depth 8)'AWSCollector negative record';Invoke-DagonDecoy $rclone 'rclone copy generated-staging remote: [ZERO-BYTE CANARY]';Invoke-DagonLoopback 443 'AWS S3 endpoint redacted' 'AWS HTTPS';Add-DagonTimeline 2100 collection-exfiltration 'Rclone then AWSCollector discovery and cloud exfiltration represented' @{bytes=0;awsRequests=0;techniques=@('T1020','T1567.002','T1039','T1135')};Add-DagonTimeline 4320 discovery 'Day-three Seatbelt and SoftPerfect Netscan represented' @{externalScan=$false};Add-DagonTimeline 5760 collection 'Day-four virtualization discovery and document ZIP represented' @{realDocuments=0;credentialsInFiles='none'};Add-DagonTimeline 7200 discovery 'Day-five event-log export and WMI discovery represented' @{eventLogsRead=0;remoteWMI=0}
$anydesk=Join-Path $p.Exfil 'AnyDesk.exe';New-DagonDecoy $anydesk 'AnyDesk remote-access decoy';Write-DagonFile(Join-Path $p.Exfil 'anydesk.ps1')'# INERT AnyDesk installation, password, account, group, and hide-account evidence only.' 'AnyDesk script canary';$persistence=[ordered]@{anyDesk=@{clientId=150937834;reportedVPNIPs=@('82.102.18.244','194.33.40.113');installed=$false;serviceCreated=$false;passwordSet=$false;connections=0};account=@{name='oldadministrator';created=$false;localAdmin=$false;domainGroup=$false;hiddenRegistryValue=$false};gpo=@{reportedLogonScript='C:\Windows\System32\GroupPolicy\User\Scripts\Logon\test.bat';beaconHost='51.89.133.3';target='specific privileged group';realGpoTouched=$false;sysvolTouched=$false;localReplica=$p.GpoReplica}}
Write-DagonFile(Join-Path $p.Evidence 'anydesk-account-gpo.json')($persistence|ConvertTo-Json -Depth 8)'persistence negative record';Write-DagonFile(Join-Path $p.GpoReplica 'GroupPolicy\User\Scripts\Logon\test.bat')'@echo off`r`nREM LOCAL REPLICA ONLY - NO GPO OR SYSVOL`r`necho ICEDID-DAGON-CANARY''GPO logon script replica';Write-DagonFile(Join-Path $p.GpoReplica 'SYSVOL-policy-record.json')(([ordered]@{replicaOnly=$true;realPathAccessed=$false;targetGroup='REDACTED privileged group';taskFilesCreated=0}|ConvertTo-Json))'SYSVOL evidence replica';Add-DagonTimeline 11520 persistence 'Day-eight AnyDesk, account, and administrative-console activity represented' @{installed=$false;accountCreated=$false;GPOChanges=0;techniques=@('T1219','T1136.002','T1053.005')};Add-DagonTimeline 15840 persistence 'Day-eleven GPO modification and expanded AnyDesk/Cobalt access represented' @{GPOChanges=0;remoteAccess=0}
$portproxy=[ordered]@{day=28;reported='netsh interface portproxy add v4tov4 listenport=3390 connectport=3389';failedInReport=$true;configured=$false;removed=$false;firewallChanged=$false};Write-DagonFile(Join-Path $p.Evidence 'day28-portproxy.json')($portproxy|ConvertTo-Json)'failed portproxy record';Invoke-DagonLoopback 3390 'failed local portproxy toward remote RDP 3389' 'loopback-only failure canary';Add-DagonTimeline 38880 defense-evasion 'Day-28 failed RDP portproxy and SPN discovery represented' @{portproxy=$false;setspnQueries=0;technique='T1562.004'}
