#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:DagonId='025-IcedID_AWSCollector_DagonLocker_29Day';$script:DagonUrl='https://thedfirreport.com/2024/04/29/from-icedid-to-dagon-locker-ransomware-in-29-days/';$script:DagonAnchor=(Get-Date).ToUniversalTime().AddHours(-684)
function Get-DagonPaths{$r=Join-Path $env:PUBLIC 'IcedIDAWSDagonSim';[ordered]@{Root=$r;Lure=Join-Path $r 'prometheus-tds-lure';Beachhead=Join-Path $r 'beachhead';Evidence=Join-Path $r 'evidence';GpoReplica=Join-Path $r 'evidence\gpo-sysvol-replica';Hosts=Join-Path $r 'generated-hosts';Shares=Join-Path $r 'generated-shares';Exfil=Join-Path $r 'generated-exfil-staging';Impact=Join-Path $r 'impact-canary';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.IcedIDAWSDagonSim.owner'}}
function Assert-DagonSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-DagonManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-DagonPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:DagonId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8}
function Initialize-DagonEnvironment{$p=Get-DagonPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:DagonId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lure,$p.Beachhead,$p.Evidence,$p.GpoReplica,$p.Hosts,$p.Shares,$p.Exfil,$p.Impact)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:DagonId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-DagonManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-DagonFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-DagonManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-DagonDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-DagonManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;match=$false}}
function Invoke-DagonDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$s=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','ICEDID-DAGON-CANARY',$s);$x=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$x.ExitCode;Add-DagonManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');escaped=$true}}
function Invoke-DagonLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-DagonManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-DagonTimeline{param([int]$OffsetMinutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-DagonPaths;[ordered]@{timestampUtc=$script:DagonAnchor.AddMinutes($OffsetMinutes).ToString('o');offsetMinutes=$OffsetMinutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-DagonSummary{param($Paths);Write-DagonFile $Paths.Summary "IcedIDAWSDagonSim complete.`nSource: $script:DagonUrl`nSimulated dwell: 684 hours over 29 days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo live malware, IOC connection, credential access, remote propagation, domain/GPO/SYSVOL change, account/RMM installation, security or backup impairment, shadow deletion, or encryption occurred." 'operator summary'}
