#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:LeakBazarId='063-Bazar_Cobalt_AnyDesk_IFM_Rclone_3Day';$script:LeakBazarUrl='https://thedfirreport.com/2021/10/04/bazarloader-and-the-conti-leaks/';$script:LeakBazarAnchor=(Get-Date).ToUniversalTime().AddHours(-72)
function Get-LeakBazarPaths{$r=Join-Path $env:PUBLIC 'LeakBazarSim';[ordered]@{Root=$r;Lures=Join-Path $r 'lure-canaries';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Discovery=Join-Path $r 'generated-discovery';Staging=Join-Path $r 'generated-staging';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.LeakBazarSim.owner'}}
function Assert-LeakBazarSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-LeakBazarManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-LeakBazarPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:LeakBazarId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-LeakBazarEnvironment{$p=Get-LeakBazarPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:LeakBazarId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lures,$p.Payloads,$p.Hosts,$p.Discovery,$p.Staging,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:LeakBazarId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-LeakBazarManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedDcCanaryOnly=$true};$p}
function Write-LeakBazarFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-LeakBazarManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-LeakBazarDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-LeakBazarManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-LeakBazarDecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='rundll32.exe');$args=@('/d','/v:off','/c','echo','LEAK-BAZAR-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -NoNewWindow;$null=$proc.ExitCode;Add-LeakBazarManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-LeakBazarLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-LeakBazarManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-LeakBazarTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-LeakBazarPaths;[ordered]@{timestampUtc=$script:LeakBazarAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-LeakBazarSummary{param($Paths);Write-LeakBazarFile $Paths.Summary "LeakBazarSim complete.`nSource: $script:LeakBazarUrl`nThe three-day Bazar/Conti-manual/GUI/IFM/Rclone chronology and pre-ransomware eviction are preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo phishing/macro, malware, injection, discovery/AD/share query, LSASS/NTDS/credential access, account/group change, RDP/remote action, AnyDesk install/session, scan, collection, archive, cloud access/exfiltration, or ransomware occurred." 'operator summary'}
