#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$script:QbotMoveSimId = '056-Qbot_Msra_Service_Spread_EmailBrowser'
$script:QbotMoveSimUrl = 'https://thedfirreport.com/2022/02/07/qbot-likes-to-move-it-move-it/'
$script:QbotMoveSimAnchor = (Get-Date).ToUniversalTime().AddHours(-2)

function Get-QbotMoveSimPaths {
    $root = Join-Path $env:PUBLIC 'QbotMoveSim'
    [ordered]@{ Root = $root; Lure = Join-Path $root 'lure-canaries'; Payloads = Join-Path $root 'payload-canaries'; Workstations = Join-Path $root 'generated-workstations'; Collection = Join-Path $root 'collection-canaries'; Evidence = Join-Path $root 'evidence'; Manifest = Join-Path $root 'artifact-manifest.jsonl'; Timeline = Join-Path $root 'evidence\intrusion-timeline.jsonl'; Summary = Join-Path $root 'operator-summary.txt'; Owner = Join-Path $root '.QbotMoveSim.owner' }
}
function Assert-QbotMoveSimSafety { param([switch]$LabConfirmed); if ($env:OS -ne 'Windows_NT') { throw 'Windows only' }; if (-not $LabConfirmed) { throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.' }; $system = Get-CimInstance Win32_ComputerSystem -ErrorAction Stop; if ([int]$system.DomainRole -in 4,5 -or (Get-Service NTDS -ErrorAction SilentlyContinue)) { throw 'Domain-controller refusal' } }
function Add-QbotMoveSimManifest { param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{}); $paths=Get-QbotMoveSimPaths; [ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:QbotMoveSimId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $paths.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray }
function Initialize-QbotMoveSimEnvironment { $paths=Get-QbotMoveSimPaths; if(Test-Path -LiteralPath $paths.Root){if(-not(Test-Path -LiteralPath $paths.Owner)-or(Get-Content -LiteralPath $paths.Owner -Raw).Trim()-ne$script:QbotMoveSimId){throw 'Refusing unowned root'}}; foreach($directory in @($paths.Root,$paths.Lure,$paths.Payloads,$paths.Workstations,$paths.Collection,$paths.Evidence)){New-Item -Path $directory -ItemType Directory -Force|Out-Null}; Set-Content -LiteralPath $paths.Owner -Value $script:QbotMoveSimId -Encoding ASCII; if(-not(Test-Path -LiteralPath $paths.Manifest)){New-Item -Path $paths.Manifest -ItemType File -Force|Out-Null}; Add-QbotMoveSimManifest directory $paths.Root created-or-reused @{cleanup='separate owned-root cleanup'}; $paths }
function Write-QbotMoveSimFile { param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact'); $directory=Split-Path -Parent $Path; if(-not(Test-Path -LiteralPath $directory)){New-Item -Path $directory -ItemType Directory -Force|Out-Null}; Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8; Add-QbotMoveSimManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash} }
function New-QbotMoveSimDecoy { param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED'); New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null; Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force; Add-QbotMoveSimManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false} }
function Invoke-QbotMoveSimDecoy { param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='msra.exe'); $arguments=@('/d','/v:off','/c','echo','QBOT-MOVE-CANARY'); $process=Start-Process -FilePath $FilePath -ArgumentList $arguments -PassThru -Wait -WindowStyle Hidden; $null=$process.ExitCode; Add-QbotMoveSimManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($arguments-join' ');reportedOnly=$true} }
function Invoke-QbotMoveSimLoopback { param([int]$Port,[string]$ReportedTarget); $client=New-Object Net.Sockets.TcpClient; try{$async=$client.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$async.AsyncWaitHandle.WaitOne(500)}catch{}finally{$client.Dispose()}; Add-QbotMoveSimManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;remote=$false;proxy=$false;bytesTransferred=0} }
function Add-QbotMoveSimTimeline { param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{}); $paths=Get-QbotMoveSimPaths; [ordered]@{timestampUtc=$script:QbotMoveSimAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $paths.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan }
function Write-QbotMoveSimSummary { param($Paths); Write-QbotMoveSimFile $Paths.Summary "QbotMoveSim complete.`nSource: $script:QbotMoveSimUrl`nMinute-30 collection and minute-50 rapid workstation-only spread are preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo malspam, macro, download, malware, task, Defender change, injection, LSASS/browser/email access, directory/network query, deletion, remote copy/service action, server access, IOC contact, or exfiltration occurred." 'operator summary' }
