#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\QbotMoveSim-utilities.ps1"; Assert-QbotMoveSimSafety -LabConfirmed:$LabConfirmed; $paths=Initialize-QbotMoveSimEnvironment
Write-QbotMoveSimFile(Join-Path $paths.Lure 'assessed-malspam.xls')'INERT XLS/MACRO-NAME CANARY. Initial access was not observed and is assessed medium-high confidence; no macro exists.''assessed lure'
Write-QbotMoveSimFile(Join-Path $paths.Payloads 'ocrafh.html.dll')'INERT HTML-DISGUISED QBOT DLL-NAME CANARY. Not a PE file.''Qbot payload canary'
$msra=Join-Path $paths.Payloads 'msra.exe'; New-QbotMoveSimDecoy $msra 'Qbot injected-process stand-in' '956ecb4afa437eafe56f958b34b6a78303ad626baee004715dc6634b7546bf85'; Invoke-QbotMoveSimDecoy $msra 'Qbot DLL executed, then injected into msra.exe' 'regsvr32.exe'
Write-QbotMoveSimFile(Join-Path $paths.Evidence 'scheduled-task.json')(@{name='juqpxmakfk';runAs='NT AUTHORITY\SYSTEM';trigger='once';reportedAction='regsvr32.exe -s C:\Users\REDACTED\ocrafh.html';taskCreated=$false}|ConvertTo-Json)'task telemetry'
foreach($command in @('reg ADD HKLM\SOFTWARE\Microsoft\Microsoft Antimalware\Exclusions\Paths /v C:\ProgramData\Microsoft\Oweboiqnb /d 0','reg ADD HKLM\SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths /v C:\ProgramData\Microsoft\Oweboiqnb /d 0','process injection into msra.exe on multiple systems','LSASS process access GrantedAccess 0x1410')){Invoke-QbotMoveSimDecoy $msra $command 'Qbot'}
Write-QbotMoveSimFile(Join-Path $paths.Evidence 'access-persistence-negative-record.json')(@{malspamSent=0;macrosExecuted=0;downloads=0;malwareExecuted=$false;tasksCreated=0;securityControlsChanged=0;processesInjected=0;LSASSAccessed=$false;credentialsCollected=0}|ConvertTo-Json)'phase safety record'
Add-QbotMoveSimTimeline 0 initial-access 'Assessed XLS 4.0 macro delivery and HTML-disguised Qbot DLL represented' @{initialAccessObserved=$false;downloads=0}; Add-QbotMoveSimTimeline .05 persistence 'One-time SYSTEM task juqpxmakfk and regsvr32 execution represented' @{tasksCreated=0}; Add-QbotMoveSimTimeline .08 defense-evasion 'msra.exe injection, Defender exclusions, and post-injection DLL deletion represented' @{processesInjected=0;systemChanges=0;filesDeleted=0}; Add-QbotMoveSimTimeline .1 credential-access 'Qbot LSASS access with reported GrantedAccess 0x1410 represented' @{LSASSAccessed=$false}
