#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\QbotMoveSim-utilities.ps1"; Assert-QbotMoveSimSafety -LabConfirmed:$LabConfirmed; $paths=Initialize-QbotMoveSimEnvironment
$serviceTool=Join-Path $paths.Payloads 'regsvr32.exe'; New-QbotMoveSimDecoy $serviceTool 'remote Qbot service stand-in'
foreach($hostName in @('BEACHHEAD-01','WORKSTATION-02','WORKSTATION-03','WORKSTATION-04','WORKSTATION-05','WORKSTATION-06')){$hostRoot=Join-Path $paths.Workstations $hostName; New-Item -Path $hostRoot -ItemType Directory -Force|Out-Null; Write-QbotMoveSimFile(Join-Path $hostRoot 'qbbwlwjmlmnaggd.dll')'INERT QBOT DLL-NAME CANARY. Not remotely copied and not a PE file.''workstation payload canary'; Write-QbotMoveSimFile(Join-Path $hostRoot 'event-7045.json')(@{reportedImagePath='regsvr32.exe -s C$\<Qbot DLL>';deleteFlag=$true;serviceCreated=$false;remoteCopy=$false}|ConvertTo-Json)'service telemetry'; Invoke-QbotMoveSimDecoy $serviceTool "Qbot service execution on generated $hostName with DeleteFlag" 'remote Service Control Manager'}
foreach($target in @('representative port 443 from 88 configured endpoints','representative port 995 from 25 configured endpoints','representative port 2222 from 17 configured endpoints','representative port 2078','representative port 1194')){Invoke-QbotMoveSimLoopback 443 $target}
Write-QbotMoveSimFile(Join-Path $paths.Evidence 'spread-negative-record.json')(@{generatedWorkstationLanes=6;reportedScope='all workstations';serversAccessed=0;adminSharesAccessed=0;remoteCopies=0;servicesCreated=0;remoteHostsTouched=0;remoteConnections=0;bytesTransferred=0;furtherActionsObserved=$false}|ConvertTo-Json)'phase safety record'
Add-QbotMoveSimTimeline .8333 lateral-movement 'First adjacent-workstation DLL copy/service sequence represented at minute 50' @{remoteCopies=0;servicesCreated=0}; Add-QbotMoveSimTimeline .9 lateral-movement 'Rapid repetition across all generated workstation lanes represented; no server lanes exist' @{workstationLanes=6;remoteHostsTouched=0;serversAccessed=0}; Add-QbotMoveSimTimeline 1 command-and-control 'Tiered Qbot SSL beaconing across reported port families represented through loopback markers' @{remoteConnections=0;bytesTransferred=0}; Add-QbotMoveSimTimeline 2 impact 'No further actions on objectives observed; stolen-data misuse remained possible future impact' @{impactObserved=$false}
