#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BlackSuitSim-utilities.ps1";Assert-BlackSuitSafety -LabConfirmed:$LabConfirmed;$p=Initialize-BlackSuitEnvironment
$beacon=Join-Path $p.Beachhead 'RtWin64.exe';New-BlackSuitDecoy $beacon 'initial oversized Cobalt Strike beacon' '55cde638e9bcc335c79c605a564419819abf5d569c128b95b005b2f48ccc43c1';Invoke-BlackSuitDecoy $beacon 'RtWin64.exe'
Add-BlackSuitTimeline 0 initial-access 'Initial Cobalt Strike beacon executed; delivery method unknown' @{size='large beacon represented by signed decoy';technique='T1204.002'}
$initialProfile=[ordered]@{server='svchorst.com';historicalIPs=@('104.21.76.140','172.67.196.25','15.197.130.221');port=443;get='/shiatzu/v2.41';post='/unobservedly/v10.78';sleepMs=50408;jitter=30;maxGet=4103260;licenseId=674054486;spawntoX86='%windir%\syswow64\SyncHost.exe';spawntoX64='%windir%\sysnative\mstsc.exe';cloudflareProxyReported=$true;actual='127.0.0.1, proxy disabled'}
Write-BlackSuitFile(Join-Path $p.Evidence 'initial-cobalt-profile.json')($initialProfile|ConvertTo-Json -Depth 8)'Cobalt Strike profile metadata';Invoke-BlackSuitLoopback 443 'svchorst.com:443' 'Cobalt Strike HTTPS'
$cmd=Join-Path $p.Beachhead 'operator.exe';New-BlackSuitDecoy $cmd 'operator command decoy';foreach($c in @('systeminfo','nltest /dclist:REDACTED','net group "domain admins" /domain','nltest /domain_trusts /all_trusts','net group "enterprise admins" /domain','route print')){Invoke-BlackSuitDecoy $cmd $c}
$credential=[ordered]@{mode='negative-execution records';rubeus=@{asrepRoast=$false;kerberoast=$false;ticketsRequested=0;outputs=@('asrep-output.canary','kerberoast-output.canary');reportedEvents=@(4768,4769);reportedRc4Type='0x17'};lsass=@{target='lsass.exe';source='injected mstsc.exe';reportedAccess='0x1010';handlesOpened=0;memoryRead=$false};secretsCaptured=0}
Write-BlackSuitFile(Join-Path $p.Evidence 'credential-access.json')($credential|ConvertTo-Json -Depth 8)'credential-access negative record';Write-BlackSuitFile(Join-Path $p.Evidence 'asrep-output.canary')'No ticket data. AS-REP roasting was not executed.''Rubeus output canary';Write-BlackSuitFile(Join-Path $p.Evidence 'kerberoast-output.canary')'No ticket data. Kerberoasting was not executed.''Rubeus output canary'
$sharp=Join-Path $p.Dogi 'SharpHound.exe';New-BlackSuitDecoy $sharp 'SharpHound decoy' '3b873bc8c7ee12fe879ab175d439b5968c8803fbb92e414de39176e2371896b2';Invoke-BlackSuitDecoy $sharp 'SharpHound.exe -c Default --outputdirectory C:\Windows\Temp\Dogi'
Write-BlackSuitFile(Join-Path $p.Dogi '20231221_BloodHound.zip.canary')'No LDAP, SAMR, SRVSVC, IPC$, or domain data. Local canary only.''SharpHound output canary'
$injection=[ordered]@{parent='RtWin64.exe';reportedTarget='mstsc.exe';CLRModules=@('Rubeus','SharpHound');processInjectionPerformed=$false;namedPipe='\\.\pipe\WkSvcPipeMgr_JORW2e';pipeCreated=$false;remoteService=@{eventId=7045;child='rundll32.exe';created=$false}}
Write-BlackSuitFile(Join-Path $p.Evidence 'injection-service-evidence.json')($injection|ConvertTo-Json -Depth 7)'injection and service metadata';Add-BlackSuitTimeline 360 credential-discovery 'Rubeus, LSASS, SharpHound, and Windows discovery represented' @{credentials='none';directoryQueries=0;remoteServices=0;techniques=@('T1558.004','T1558.003','T1003.001','T1055','T1082')}
