#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BlackSuitSim-utilities.ps1";Assert-BlackSuitSafety -LabConfirmed:$LabConfirmed;$p=Initialize-BlackSuitEnvironment;if(-not(Test-Path(Join-Path $p.Evidence 'systembc.json'))){throw'Run phase 2 first'}
$adf=Join-Path $p.Collection 'ADFind.exe';$getData=Join-Path $p.Collection 'Get-DataInfo.ps1';$seven=Join-Path $p.Collection '7z.exe';New-BlackSuitDecoy $adf 'ADFind decoy' 'b1102ed4bca6dae6f2f498ade2f73f76af527fa803f0e0b46e100d4cf5150682';New-BlackSuitDecoy $seven '7-Zip collection decoy';Write-BlackSuitFile $getData '# INERT Get-DataInfo.ps1 name-only canary. No functions or collection code.' 'discovery script canary';Write-BlackSuitFile(Join-Path $p.Collection 'adf.bat')'@echo off`r`nREM INERT ADFind invocation record`r`necho BLACKSUIT-CANARY''ADFind batch canary';Write-BlackSuitFile(Join-Path $p.Collection 'start.bat')'@echo off`r`nREM INERT Get-DataInfo method bug record`r`necho BLACKSUIT-CANARY''collection batch canary'
Invoke-BlackSuitDecoy $adf 'C:\Perflogs\adf\adf.bat (successful final-day run after prior wrong-directory failures)';Invoke-BlackSuitDecoy $seven '7z.exe a DataInfo.7z generated-results-canary';Write-BlackSuitFile(Join-Path $p.Collection 'DataInfo.7z.canary')'No collected system, software, disk, credential, financial, or user data.''collection archive canary'
$collection=[ordered]@{adfind=@{attempts='multiple failures then success in report';executed=$false;LDAPQueries=0};getDataInfo=@{reportedFunctions=@('Test-LHost','Get-DiskInfo','Get-Software','Compress-Result');methodParameterBug=$true;executed=$false};interestingFiles=@{notepadWordpadBrowsingReported=$true;userFilesOpened=0};archive=@{reportedTool='7z.exe';actual='signed decoy echo';dataBytes=0};adminConsoles=@('dsa.msc','gpedit.msc');consolesOpened=0;GPOChanges=0}
Write-BlackSuitFile(Join-Path $p.Evidence 'final-discovery-collection.json')($collection|ConvertTo-Json -Depth 8)'collection negative record';Add-BlackSuitTimeline 19560 discovery-collection 'Final-day ADFind, Get-DataInfo, 7z, DNS and Group Policy console activity represented' @{directoryQueries=0;userFilesOpened=0;GPOChanges=0;techniques=@('T1560','T1518','T1518.001')}
$qwe=Join-Path $p.Impact 'qwe.exe';New-BlackSuitDecoy $qwe 'BlackSuit ransomware decoy' '60dcbfb30802e7f4c37c9cdfc04ddb411060918d19e5b309a5be6b4a73c8b18a';Write-BlackSuitFile(Join-Path $p.Impact '123.txt')'qwe.exe -id REDACTED`r`nINERT REFERENCE ONLY - the signed decoy is never launched as ransomware.''operator helper canary'
$impact=[ordered]@{reported=@('SMB C$ copy of qwe.exe and 123.txt','RDP from DC-X','Notepad opens 123.txt','manual qwe.exe execution','vssadmin shadow deletion','file encryption','readme.blacksuit.txt notes');adminShareCopies=0;rdpSessions=0;shadowCopiesDeleted=0;encryptionPerformed=$false;realFilesRead=0;reportedTTRHours=328}
Write-BlackSuitFile(Join-Path $p.Evidence 'impact-negative-record.json')($impact|ConvertTo-Json -Depth 8)'BlackSuit impact metadata'
foreach($h in @('WORKSTATION2','FILE-SRV01','BACKUP-SRV01','DC-X')){$d=Join-Path $p.Impact $h;New-Item $d -ItemType Directory -Force|Out-Null;foreach($n in @('budget.xlsx','contracts.docx','backup.bak')){$o=Join-Path $d $n;Write-BlackSuitFile $o "Generated intact canary $h/$n. Not encrypted." 'intact canary';Write-BlackSuitFile "$o.BLACKSUIT-CANARY" "Marker only for $n; original intact." 'ransomware marker'};Write-BlackSuitFile(Join-Path $d 'readme.blacksuit.txt')'INERT BLACKSUIT CANARY NOTE. No encryption, contact, payment, or recovery action.''ransom note canary'}
Add-BlackSuitTimeline 19680 impact 'BlackSuit marker artifacts created at just under 328 hours' @{remoteHostsTouched=0;shadowDeletion=$false;encryption=$false;intactOriginals=12;markers=12;techniques=@('T1021.002','T1021.001','T1490','T1486')}
