#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:BlackSuitId='022-BlackSuit_CobaltStrike_SystemBC_15Day'
$script:BlackSuitUrl='https://thedfirreport.com/2024/08/26/blacksuit-ransomware/'
$script:BlackSuitAnchor=(Get-Date).ToUniversalTime().AddHours(-328)
function Get-BlackSuitPaths{$r=Join-Path $env:PUBLIC 'BlackSuit15DaySim';[ordered]@{Root=$r;Beachhead=Join-Path $r 'beachhead';Evidence=Join-Path $r 'evidence';Dogi=Join-Path $r 'beachhead\Windows\Temp\Dogi';Hosts=Join-Path $r 'generated-hosts';FileServer=Join-Path $r 'generated-file-server';Collection=Join-Path $r 'collection-canary';Impact=Join-Path $r 'impact-canary';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.BlackSuit15DaySim.owner'}}
function Assert-BlackSuitSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-BlackSuitManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-BlackSuitPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:BlackSuitId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-BlackSuitEnvironment{$p=Get-BlackSuitPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:BlackSuitId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Beachhead,$p.Evidence,$p.Dogi,$p.Hosts,$p.FileServer,$p.Collection,$p.Impact)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:BlackSuitId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-BlackSuitManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-BlackSuitFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-BlackSuitManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-BlackSuitDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-BlackSuitManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;match=$false}}
function Invoke-BlackSuitDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$s=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$a=@('/d','/v:off','/c','echo','BLACKSUIT-CANARY',$s);$x=Start-Process $FilePath -ArgumentList $a -PassThru -Wait -WindowStyle Hidden;$null=$x.ExitCode;Add-BlackSuitManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($a-join' ');escaped=$true}}
function Invoke-BlackSuitLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-BlackSuitManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-BlackSuitTimeline{param([int]$OffsetMinutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-BlackSuitPaths;[ordered]@{timestampUtc=$script:BlackSuitAnchor.AddMinutes($OffsetMinutes).ToString('o');offsetMinutes=$OffsetMinutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-BlackSuitSummary{param($Paths);Write-BlackSuitFile $Paths.Summary "BlackSuit15DaySim complete.`nSource: $script:BlackSuitUrl`nSimulated dwell: just under 328 hours across 15 calendar days.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo live malware, credential access, Kerberos abuse, directory query, remote execution, tunnel, registry/task/service change, shadow deletion, encryption, or real IOC connection occurred." 'operator summary'}
