#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\BlackSuitSim-utilities.ps1";Assert-BlackSuitSafety -LabConfirmed:$LabConfirmed;$p=Initialize-BlackSuitEnvironment;if(-not(Test-Path(Join-Path $p.Beachhead 'RtWin64.exe'))){throw'Run phase 1 first'}
$cmd=Join-Path $p.Beachhead 'operator.exe';foreach($h in @('BEACHHEAD','WORKSTATION2','FILE-SRV01','BACKUP-SRV01','DC-X','DC-Y')){$d=Join-Path $p.Hosts $h;New-Item $d -ItemType Directory -Force|Out-Null;Write-BlackSuitFile(Join-Path $d 'host-record.json')(([ordered]@{syntheticHost=$h;SMB=$false;RDP=$false;WMI=$false;domainControllerTouched=$false}|ConvertTo-Json))'synthetic host'}
$lateral=[ordered]@{mode='local folders and evidence only';reported=@('Cobalt Strike psexec','psexec_psh','SMB ADMIN$ beacon transfer','RDP','pass-the-hash logon type 9/seclogo');servicesCreated=0;adminSharesAccessed=0;rdpSessions=0;hashesUsed=0;remoteSystemsTouched=0;events=@(7045,5145,4624,4778,4779)}
Write-BlackSuitFile(Join-Path $p.Evidence 'lateral-movement.json')($lateral|ConvertTo-Json -Depth 7)'lateral movement negative record';Invoke-BlackSuitDecoy $cmd '%COMSPEC% /b /c start /b /min powershell -nop -w hidden -encodedcommand REDACTED';Add-BlackSuitTimeline 370 lateral-movement 'First Cobalt Strike service/SMB pivot represented' @{remoteExecution=$false;techniques=@('T1569.002','T1021.002')};Add-BlackSuitTimeline 1440 lateral-movement 'Day-two beacon distribution and RDP movement represented' @{sessions=0;passTheHash=$false;techniques=@('T1021.001','T1550.002')}
$sc=Join-Path $p.FileServer 'SC.exe';$socks=Join-Path $p.FileServer 'socks32.exe';New-BlackSuitDecoy $sc 'SystemBC first implant decoy';New-BlackSuitDecoy $socks 'SystemBC persistence/proxy decoy' '9493b512d7d15510ebee5b300c55b67f9f2ff1dda64bddc99ba8ba5024113300';Invoke-BlackSuitDecoy $sc 'SC.exe';Invoke-BlackSuitDecoy $socks 'socks32.exe'
$systemBC=[ordered]@{reportedC2='137.220.61.94';reportedFiles=@('SC.exe','socks32.exe');runKey=@{path='HKCU\Software\Microsoft\Windows\CurrentVersion\Run';name='socks5';data='powershell.exe windowstyle -hidden Command socks32.exe';created=$false};scheduledTaskCapability='not observed in case and not simulated';proxyTunnelCreated=$false;actualDestination='127.0.0.1';proxy=$false}
Write-BlackSuitFile(Join-Path $p.Evidence 'systembc.json')($systemBC|ConvertTo-Json -Depth 8)'SystemBC metadata';Invoke-BlackSuitLoopback 443 '137.220.61.94:reported-port-unspecified' 'SystemBC canary';Add-BlackSuitTimeline 1800 persistence-c2 'SystemBC manual execution and socks5 Run key represented' @{registryWrites=0;tunnel=$false;techniques=@('T1547.001','T1090')}
$profiles=[ordered]@{smb=@{port=4444;sleepMs=10000;maxGet=2048576;jitter=0;pipe='\\.\pipe\WkSvcPipeMgr_JORW2e';licenseId=674054486;spawnto=@('SyncHost.exe','mstsc.exe')};https=@{domains=@('qw.regsvcast.com','as.regsvcast.com','zx.regsvcast.com');historicalIP='147.78.47.178';port=443;sleepMs=63612;jitter=39;maxGet=2796542;get='/hr';post=@('/ch','/rw');licenseId=1580103824;spawnto='runonce.exe';xorKey='0x23 PowerShell stager';actual='127.0.0.1, no proxy'}}
Write-BlackSuitFile(Join-Path $p.Evidence 'later-cobalt-profiles.json')($profiles|ConvertTo-Json -Depth 9)'Cobalt Strike profiles';foreach($target in @('qw.regsvcast.com:443','as.regsvcast.com:443','zx.regsvcast.com:443','147.78.47.178:443')){Invoke-BlackSuitLoopback 443 $target 'Cobalt Strike HTTPS'};Invoke-BlackSuitLoopback 80 'PowerShell Cobalt Strike stager C2 redacted:80' 'clear-text HTTP rewritten to loopback'
Add-BlackSuitTimeline 8640 c2 'Day-seven svchorst.com moved from Cloudflare to AWS address' @{DNS='metadata only';queries=0};Add-BlackSuitTimeline 10080 c2 'Day-eight PowerShell Cobalt Strike beacon on a domain controller represented' @{domainControllerTouched=$false;downloaded=$false;decoded=$false};Add-BlackSuitTimeline 12960 lateral-movement 'Day-ten beacons and RDP activity resumed' @{remoteSystemsTouched=0}
