#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:IMId='070-IcedID_Cobalt_SMB_RDP_1h';$script:IMUrl='https://thedfirreport.com/2021/06/20/from-word-to-lateral-movement-in-1-hour/';$script:IMAnchor=(Get-Date).ToUniversalTime().AddMinutes(-105)
function Get-IMPaths{$r=Join-Path $env:PUBLIC 'IcedMoveSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Evidence=Join-Path $r 'evidence';Pipes=Join-Path $r 'named-pipe-markers';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.IcedMoveSim.owner'}}
function Assert-IMSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-IMManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-IMPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:IMId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-IMEnvironment{$p=Get-IMPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:IMId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Hosts,$p.Evidence,$p.Pipes)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:IMId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-IMManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedDcCanaryOnly=$true};$p}
function Write-IMFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-IMManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-IMDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-IMManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatchExpected=$false}}
function Invoke-IMDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','ICED-MOVE-CANARY');$q=Start-Process -FilePath $FilePath -ArgumentList $a -PassThru -Wait -NoNewWindow;$null=$q.ExitCode;Add-IMManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-IMLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-IMManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-IMTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-IMPaths;[ordered]@{timestampUtc=$script:IMAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-IMSummary{param($p);Write-IMFile $p.Summary "IcedMoveSim complete.`nSource: $script:IMUrl`nInternal case: 3930`nCobalt at minute 35, movement five minutes later, and hour-plus RDP browsing are preserved.`nArtifacts remain; cleanup is separate.`nNo malware, macro, task, injection, LSASS/credentials, AD query, SMB/service/RDP, external C2, exfiltration, impact, or actor cleanup occurred." summary}
