#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$script:OpenDirId='029-OpenDir_Persistent_Actor_Sliver_Metasploit'
$script:OpenDirUrl='https://thedfirreport.com/2023/12/18/lets-opendir-some-presents-an-analysis-of-a-persistent-actors-activity/'
$script:OpenDirAnchor=[datetime]'2022-08-12T06:21:02Z'
function Get-OpenDirPaths{$r=Join-Path $env:PUBLIC 'OpenDirActorSim';[ordered]@{Root=$r;Actor=Join-Path $r 'actor-host';History=Join-Path $r 'actor-host\root\history';Targets=Join-Path $r 'actor-host\root\targets';Outputs=Join-Path $r 'actor-host\root\scan-outputs';Frameworks=Join-Path $r 'actor-host\root\frameworks';Victims=Join-Path $r 'generated-victims';Samples=Join-Path $r 'sample-canaries';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\activity-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.OpenDirActorSim.owner'}}
function Assert-OpenDirSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw'Windows only'};if(-not$LabConfirmed){throw'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw'Domain-controller refusal'}}
function Add-OpenDirManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-OpenDirPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:OpenDirId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Manifest -Encoding UTF8}
function Initialize-OpenDirEnvironment{$p=Get-OpenDirPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:OpenDirId){throw'Refusing unowned root'}};foreach($d in @($p.Root,$p.Actor,$p.History,$p.Targets,$p.Outputs,$p.Frameworks,$p.Victims,$p.Samples,$p.Evidence)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:OpenDirId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File -Force|Out-Null};Add-OpenDirManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};return$p}
function Write-OpenDirFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-OpenDirManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function New-OpenDirDecoy{param([string]$Path,[string]$Role,[string]$ReportedSha256='NOT-PUBLISHED');New-Item(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-OpenDirManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;reportedSha256=$ReportedSha256;hashMatch=$false}}
function Invoke-OpenDirDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$safe=$ReportedCommandLine.Replace('^','^^').Replace('&','^&').Replace('|','^|').Replace('<','^<').Replace('>','^>').Replace('(','^(').Replace(')','^)');$args=@('/d','/v:off','/c','echo','OPENDIR-CANARY',$safe);$proc=Start-Process $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-OpenDirManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');escaped=$true}}
function Invoke-OpenDirLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Protocol='tcp');$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-OpenDirManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;protocol=$Protocol;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-OpenDirTimeline{param([int]$OffsetDays,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-OpenDirPaths;[ordered]@{timestampUtc=$script:OpenDirAnchor.AddDays($OffsetDays).ToString('o');offsetDays=$OffsetDays;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 9 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-OpenDirSummary{param($Paths);Write-OpenDirFile $Paths.Summary "OpenDirActorSim complete.`nSource: $script:OpenDirUrl`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo real target was scanned or exploited; no malware, credential access, remote propagation, defense impairment, persistence, mining, or exfiltration occurred." 'operator summary'}
