#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\OpenDirActorSim-utilities.ps1";Assert-OpenDirSafety -LabConfirmed:$LabConfirmed;$p=Initialize-OpenDirEnvironment
$shell=Join-Path $p.Frameworks 'bash.exe';if(-not(Test-Path $shell)){New-OpenDirDecoy $shell 'signed actor-shell stand-in'}
$commands=@('SharPersist create HealthCheck service with encoded PowerShell','sc create winmo displayname=discord binpath=C:\ProgramData\mdsn\svchost.exe start=auto','SharPersist create HealthCheck scheduled task','schtasks schdsWin as SYSTEM every 30 minutes','Meterpreter getsystem','LinPEAS privilege-escalation discovery','Set-MpPreference DisableScriptScanning','Add-MpPreference ExclusionPath C:\Windows\Temp','load kiwi; creds_all; lsa_dump_sam; hashdump','download ntds.dit','dcsync_ntlm domain user','golden_ticket_create','Find-InterestingDomainShareFile passwords','enumerate SSH keys and propagate','append autominionlx.sh to .bashrc and cron','xmrig Monero mining','portfwd reverse 89474 to 4453','torify multi-hop proxy')
foreach($c in $commands){Invoke-OpenDirDecoy $shell $c};Write-OpenDirFile(Join-Path $p.History 'post-exploitation-history.txt')($commands-join"`n")'post-execution history'
Write-OpenDirFile(Join-Path $p.Victims 'lab-linux-01\.bashrc')"# GENERATED CANARY`n# Reported autominionlx.sh persistence string only; no command."'bashrc canary';Write-OpenDirFile(Join-Path $p.Victims 'lab-linux-01\var\spool\cron\root')'# GENERATED CANARY: no executable cron entry.''cron canary'
$unsafe=[ordered]@{servicesOrTasksCreated=$false;systemContextObtained=$false;defenderChanged=$false;samAccess=$false;ntdsAccess=$false;dcsync=$false;goldenTicket=$false;credentialFilesRead=$false;privateKeysRead=$false;sshPropagation=$false;ufwChanged=$false;servicesKilled=$false;minerRun=$false;miningPoolContact=$false;proxyOrPortForward=$false;dataExfiltrated=$false};Write-OpenDirFile(Join-Path $p.Evidence 'post-exploitation-negative-record.json')($unsafe|ConvertTo-Json)'unsafe-action refusal evidence'
$discovery=@('Get-Domain','Get-DomainSID','Get-DomainPolicy','Get-DomainController','Get-DomainUser','Get-DomainComputer','Get-DomainGroup','Get-DomainGPOLocalGroup','Find-DomainShare','Get-ADUser with SPN','Get-DomainGPO','Get-DomainOU','Find-InterestingDomainAcl','ipconfig','net user /domain','hostname','whoami','systeminfo','netstat -ano','Invoke-adPEAS');Write-OpenDirFile(Join-Path $p.Evidence 'directory-discovery-commands.json')([ordered]@{reportedCommands=$discovery;executed=$false;directoryQueried=$false;generatedOutputOnly=$true}|ConvertTo-Json -Depth 5)'discovery evidence'
Add-OpenDirTimeline 425 persistence 'Service, task, bashrc, cron, web-shell, and miner persistence represented without system changes' @{persistenceCreated=$false;techniques=@('T1505.003','T1569.002','T1053.005','T1546.004','T1496')}
Add-OpenDirTimeline 430 credential-access 'SAM, NTDS, DCSync, ticket, files, and private-key actions represented as negative records' @{credentialsAccessed=$false;techniques=@('T1003.002','T1003.003','T1003.006','T1558.001','T1552.001','T1552.004')}
Add-OpenDirTimeline 433 completion 'Open-directory exposure and actor-host evidence collection represented; artifacts remain' @{cleanupRun=$false}
