#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:GGId='097-RDP_CredentialToolkit_GoGoogle_1h';$script:GGUrl='https://thedfirreport.com/2020/04/04/gogoogle-ransomware/';$script:GGAnchor=(Get-Date).ToUniversalTime().AddMinutes(-65)
function Get-GGPaths{$r=Join-Path $env:PUBLIC 'GoGoogleHourSim';[ordered]@{Root=$r;Payloads=Join-Path $r 'payload-canaries';Evidence=Join-Path $r 'evidence';Hosts=Join-Path $r 'generated-hosts';Registry=Join-Path $r 'generated-registry';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\exercise-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.GoGoogleHourSim.owner'}}
function Assert-GGSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed-or$env:DFIR_LAB_CONFIRMATION-ne'I_UNDERSTAND_THIS_IS_A_LAB'){throw 'Lab gate refused'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-GGManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-GGPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:GGId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8}
function Initialize-GGEnvironment{$p=Get-GGPaths;if(Test-Path $p.Root){if(-not(Test-Path $p.Owner)-or(Get-Content $p.Owner -Raw).Trim()-ne$script:GGId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Payloads,$p.Evidence,$p.Hosts,$p.Registry)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $p.Owner $script:GGId -Encoding ASCII;if(-not(Test-Path $p.Manifest)){New-Item $p.Manifest -ItemType File|Out-Null};Add-GGManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup'};$p}
function Write-GGFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path $Path -Parent;if(-not(Test-Path $d)){New-Item $d -ItemType Directory -Force|Out-Null};Set-Content $Path $Content -Encoding UTF8;Add-GGManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash $Path -Algorithm SHA256).Hash}}
function Write-GGJson{param([string]$Path,[object]$Object,[string]$Purpose='evidence');Write-GGFile $Path ($Object|ConvertTo-Json -Depth 15) $Purpose}
function New-GGDecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='none');New-Item(Split-Path $Path -Parent)-ItemType Directory -Force|Out-Null;Copy-Item(Join-Path $env:SystemRoot 'System32\cmd.exe')$Path -Force;Add-GGManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256}}
function Invoke-GGDecoy{param([string]$FilePath,[string]$Reported,[string]$Parent);$a=@('/d','/v:off','/c','echo','GOGOOGLE-HOUR-CANARY');$q=Start-Process $FilePath -ArgumentList $a -Wait -PassThru -WindowStyle Hidden;$null=$q.ExitCode;Add-GGManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$Reported;reportedParent=$Parent;actualArguments=($a-join' ');reportedOnly=$true}}
function Invoke-GGLoopback{param([int]$Port,[string]$Target,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$x=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$x.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-GGManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$Target;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-GGTimeline{param([double]$Minutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-GGPaths;[ordered]@{timestampUtc=$script:GGAnchor.AddMinutes($Minutes).ToString('o');offsetMinutes=$Minutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 12 -Compress|Add-Content $p.Timeline -Encoding UTF8}
function Write-GGSummary{param($p);Write-GGFile $p.Summary "GoGoogleHourSim complete.`nSource: $script:GGUrl`nThe 65-minute generated axis preserves every timestamp in the report's 19:30-20:34 UTC visual timeline and the final disconnect ordering.`nNo authentication, security change, credential or LSASS access, brute force, scan, RDP, remote action, process/service stop, log/shadow deletion, registry/Utilman change, or encryption occurred.`nArtifacts remain; cleanup is separate." summary}
