#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\CSNetGuideSim-utilities.ps1";Assert-CSNetGuideSafety -LabConfirmed:$LabConfirmed;$p=Initialize-CSNetGuideEnvironment
Write-CSNetGuideFile(Join-Path $p.Channels 'socks-rdp.json')(@{reportedSocksPort=8888;attackerTool='proxychains + xfreerdp';reportedLogonEvent=4624;reportedLogonType=3;reportedSourceAddress='127.0.0.1';victimHostnameCaptured=$true;listenerCreated=$false;rdpSessions=0}|ConvertTo-Json)'reverse proxy/RDP canary'
$dnsEvents=for($i=1;$i-le148;$i++){[ordered]@{sequence=$i;timestampUtc=$script:CSNetGuideAnchor.AddMinutes(15).AddMilliseconds($i*34).ToString('o');source='192.168.88.179 (reported lab target)';resolver='192.168.88.2 (reported lab DNS)';domain='infosecppl.store';recordType=@('A','AAAA','TXT')[($i-1)%3];synthetic=$true;sent=$false}};Write-CSNetGuideFile(Join-Path $p.Logs 'dns-148-event-systeminfo.json')($dnsEvents|ConvertTo-Json -Depth 5)'synthetic DNS event series'
Write-CSNetGuideFile(Join-Path $p.Channels 'smb-parent-child.json')(@{child='192.168.38.102 (reported lab SMB Beacon)';parent='192.168.38.104 (reported lab HTTP Beacon)';pipe='my_pipes';defaultPipePattern='msagent_#';port=445;PowerShellLoaderExecuted=$false;namedPipesCreated=0;smbConnections=0}|ConvertTo-Json)'SMB beacon chain canary'
foreach($target in @('SOCKS port 8888 and reverse-proxy RDP','DNS A/AAAA/TXT C2 at infosecppl.store','SMB parent/child chain via my_pipes')){Invoke-CSNetGuideLoopback 445 $target 'channel telemetry marker'}
Write-CSNetGuideFile(Join-Path $p.Evidence 'channel-negative-record.json')(@{socksListeners=0;proxyConnections=0;rdpSessions=0;dnsQueriesSent=0;dnsPacketsSent=0;PowerShellLoadersExecuted=0;namedPipesCreated=0;smbConnections=0;remoteHostsTouched=0;bytesTransferred=0}|ConvertTo-Json)'phase safety record';Add-CSNetGuideTimeline .2 proxy 'SOCKS port 8888, proxychains/xfreerdp, and type-3 4624 loopback-source artifact represented' @{listeners=0;sessions=0};Add-CSNetGuideTimeline .25 dns 'Reported five-second, 148-packet systeminfo DNS task represented as generated events' @{events=148;queriesSent=0};Add-CSNetGuideTimeline .35 smb 'my_pipes SMB child/HTTP parent chain and Sysmon 17/18 concepts represented' @{namedPipes=0;smbConnections=0}
