#Requires -Version 5.1
#Requires -RunAsAdministrator
[CmdletBinding()]param([switch]$LabConfirmed)
. "$PSScriptRoot\CSNetGuideSim-utilities.ps1";Assert-CSNetGuideSafety -LabConfirmed:$LabConfirmed;$p=Initialize-CSNetGuideEnvironment
$profile=[ordered]@{sampleName='whatever.profile';sleepTimeMs=0;jitterPercent=25;userAgent='<custom>';dataJitterBytes=35;headersRemove='<custom>';certificate=@{C='US';CN='whatever.com';L='California';O='whatever LLC.';OU='local.org';ST='CA';validityDays=365};httpConfig=@{trustXForwardedFor='<true OR false>';blockUserAgents='<custom>';allowUserAgents='<custom>'};httpGet=@{uri='/<URI string>';verb='POST';host='whatever.com';metadataTransforms=@('base64url','append .php','parameter file')}};Write-CSNetGuideFile(Join-Path $p.Profiles 'annotated-reference-profile.json')($profile|ConvertTo-Json -Depth 8)'malleable C2 configuration canary'
Write-CSNetGuideFile(Join-Path $p.Profiles 'observed-server-uri-pairs.json')((Get-Content -LiteralPath(Join-Path $PSScriptRoot 'IOC-METADATA.json')-Raw|ConvertFrom-Json).observedServerUriPairs|ConvertTo-Json -Depth 5)'published C2/URI metadata'
Write-CSNetGuideFile(Join-Path $p.Channels 'domain-fronting.json')(@{origin='infosecppl.store';cdnEndpoint='l33th4x0r.cloudfront.net';frontDomain='legitimate same-CDN domain';hostHeader='l33th4x0r.cloudfront.net';requestsSent=0;cdnConfigured=$false}|ConvertTo-Json)'domain-fronting canary'
$beacon=Join-Path $p.Channels 'rundll32.exe';New-CSNetGuideDecoy $beacon 'Cobalt Beacon stand-in';Invoke-CSNetGuideDecoy $beacon 'HTTP GET/POST jquery malleable profile with custom URI, headers, metadata transforms, sleep, jitter, and data jitter';Invoke-CSNetGuideLoopback 443 'published Cobalt endpoints and illustrative CDN/front domains' 'HTTP/HTTPS/domain-fronting marker'
Write-CSNetGuideFile(Join-Path $p.Evidence 'profile-fronting-negative-record.json')(@{payloadsGenerated=0;teamServersCreated=0;certificatesCreated=0;domainsOwned=0;cdnEndpointsConfigured=0;frontedRequests=0;remoteConnections=0;bytesTransferred=0}|ConvertTo-Json)'phase safety record';Add-CSNetGuideTimeline 0 profile 'Malleable HTTP/HTTPS options and published server/URI examples represented' @{realTraffic=$false};Add-CSNetGuideTimeline .1 domain-fronting 'CDN origin/front/Host-header relationship represented without infrastructure or requests' @{cdnChanges=0;requests=0}
