#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:CSNetGuideId='057-CobaltStrike_DefendersGuide2_NetworkTelemetry';$script:CSNetGuideUrl='https://thedfirreport.com/2022/01/24/cobalt-strike-a-defenders-guide-part-2/';$script:CSNetGuideAnchor=(Get-Date).ToUniversalTime().AddHours(-1)
function Get-CSNetGuidePaths{$r=Join-Path $env:PUBLIC 'CSNetGuideSim';[ordered]@{Root=$r;Profiles=Join-Path $r 'malleable-profile-canaries';Channels=Join-Path $r 'channel-canaries';Logs=Join-Path $r 'synthetic-network-logs';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\guide-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.CSNetGuideSim.owner'}}
function Assert-CSNetGuideSafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-CSNetGuideManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-CSNetGuidePaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:CSNetGuideId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-CSNetGuideEnvironment{$p=Get-CSNetGuidePaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:CSNetGuideId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Profiles,$p.Channels,$p.Logs,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:CSNetGuideId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-CSNetGuideManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';scenarioType='defensive synthetic telemetry lab'};$p}
function Write-CSNetGuideFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-CSNetGuideManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-CSNetGuideDecoy{param([string]$Path,[string]$Role);New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-CSNetGuideManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function Invoke-CSNetGuideDecoy{param([string]$FilePath,[string]$ReportedCommandLine);$args=@('/d','/v:off','/c','echo','CS-NET-GUIDE-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-CSNetGuideManifest process $FilePath executed-signed-decoy @{reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-CSNetGuideLoopback{param([int]$Port,[string]$ReportedTarget,[string]$Channel);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-CSNetGuideManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;channel=$Channel;listenerCreated=$false;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-CSNetGuideTimeline{param([double]$OffsetHours,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-CSNetGuidePaths;[ordered]@{timestampUtc=$script:CSNetGuideAnchor.AddHours($OffsetHours).ToString('o');offsetHours=$OffsetHours;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-CSNetGuideSummary{param($Paths);Write-CSNetGuideFile $Paths.Summary "CSNetGuideSim complete.`nSource: $script:CSNetGuideUrl`nThis is a defensive synthetic network-telemetry lab, not one observed intrusion.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo Cobalt Strike payload/team server, domain fronting, CDN, SOCKS listener, RDP session, DNS query, SMB connection/named pipe, remote scan, JARM probe, IOC contact, real PCAP, or data transfer occurred." 'operator summary'}
