#Requires -Version 5.1
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';$script:ZeroDAId='061-Hancitor_Cobalt_Zerologon_ZeroToDA_2h';$script:ZeroDAUrl='https://thedfirreport.com/2021/11/01/from-zero-to-domain-admin/';$script:ZeroDAAnchor=(Get-Date).ToUniversalTime().AddHours(-2)
function Get-ZeroDAPaths{$r=Join-Path $env:PUBLIC 'ZeroDASim';[ordered]@{Root=$r;Lures=Join-Path $r 'lure-canaries';Payloads=Join-Path $r 'payload-canaries';Hosts=Join-Path $r 'generated-hosts';Discovery=Join-Path $r 'generated-discovery';Evidence=Join-Path $r 'evidence';Manifest=Join-Path $r 'artifact-manifest.jsonl';Timeline=Join-Path $r 'evidence\intrusion-timeline.jsonl';Summary=Join-Path $r 'operator-summary.txt';Owner=Join-Path $r '.ZeroDASim.owner'}}
function Assert-ZeroDASafety{param([switch]$LabConfirmed);if($env:OS-ne'Windows_NT'){throw 'Windows only'};if(-not$LabConfirmed){throw 'Lab gate refused. Pass -LabConfirmed to confirm this is a dedicated lab.'};$s=Get-CimInstance Win32_ComputerSystem -ErrorAction Stop;if([int]$s.DomainRole-in 4,5-or(Get-Service NTDS -ErrorAction SilentlyContinue)){throw 'Domain-controller refusal'}}
function Add-ZeroDAManifest{param([string]$Type,[string]$Path,[string]$Action,[hashtable]$Details=@{});$p=Get-ZeroDAPaths;[ordered]@{timestampUtc=(Get-Date).ToUniversalTime().ToString('o');scenarioId=$script:ZeroDAId;type=$Type;path=$Path;action=$Action;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Manifest -Encoding UTF8;Write-Host ("  [{0}] {1}: {2}" -f $Type,$Action,$Path) -ForegroundColor DarkGray}
function Initialize-ZeroDAEnvironment{$p=Get-ZeroDAPaths;if(Test-Path -LiteralPath $p.Root){if(-not(Test-Path -LiteralPath $p.Owner)-or(Get-Content -LiteralPath $p.Owner -Raw).Trim()-ne$script:ZeroDAId){throw 'Refusing unowned root'}};foreach($d in @($p.Root,$p.Lures,$p.Payloads,$p.Hosts,$p.Discovery,$p.Evidence)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $p.Owner -Value $script:ZeroDAId -Encoding ASCII;if(-not(Test-Path -LiteralPath $p.Manifest)){New-Item -Path $p.Manifest -ItemType File -Force|Out-Null};Add-ZeroDAManifest directory $p.Root created-or-reused @{cleanup='separate owned-root cleanup';generatedDcCanaryOnly=$true};$p}
function Write-ZeroDAFile{param([string]$Path,[AllowEmptyString()][string]$Content,[string]$Purpose='artifact');$d=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $d)){New-Item -Path $d -ItemType Directory -Force|Out-Null};Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8;Add-ZeroDAManifest file $Path created @{purpose=$Purpose;sha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}}
function New-ZeroDADecoy{param([string]$Path,[string]$Role,[string]$PublishedSha256='NOT-PUBLISHED');New-Item -Path(Split-Path -Parent $Path)-ItemType Directory -Force|Out-Null;Copy-Item -LiteralPath(Join-Path $env:SystemRoot 'System32\cmd.exe')-Destination $Path -Force;Add-ZeroDAManifest executable-decoy $Path copied-signed-cmd @{role=$Role;actualSha256=(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash;publishedSha256=$PublishedSha256;hashMatch=$false}}
function Invoke-ZeroDADecoy{param([string]$FilePath,[string]$ReportedCommandLine,[string]$ReportedParent='WINWORD.exe');$args=@('/d','/v:off','/c','echo','ZERO-DA-CANARY');$proc=Start-Process -FilePath $FilePath -ArgumentList $args -PassThru -Wait -WindowStyle Hidden;$null=$proc.ExitCode;Add-ZeroDAManifest process $FilePath executed-signed-decoy @{reportedParent=$ReportedParent;reportedCommandLine=$ReportedCommandLine;actualArguments=($args-join' ');reportedOnly=$true}}
function Invoke-ZeroDALoopback{param([int]$Port,[string]$ReportedTarget,[string]$Role);$c=New-Object Net.Sockets.TcpClient;try{$a=$c.BeginConnect('127.0.0.1',$Port,$null,$null);$null=$a.AsyncWaitHandle.WaitOne(500)}catch{}finally{$c.Dispose()};Add-ZeroDAManifest network "127.0.0.1:$Port" loopback-only @{reportedTarget=$ReportedTarget;role=$Role;remote=$false;proxy=$false;bytesTransferred=0}}
function Add-ZeroDATimeline{param([double]$OffsetMinutes,[string]$Phase,[string]$Event,[hashtable]$Details=@{});$p=Get-ZeroDAPaths;[ordered]@{timestampUtc=$script:ZeroDAAnchor.AddMinutes($OffsetMinutes).ToString('o');offsetMinutes=$OffsetMinutes;phase=$Phase;event=$Event;details=$Details}|ConvertTo-Json -Depth 10 -Compress|Add-Content -LiteralPath $p.Timeline -Encoding UTF8;Write-Host ("  [timeline] {0}: {1}" -f $Phase,$Event) -ForegroundColor Cyan}
function Write-ZeroDASummary{param($Paths);Write-ZeroDAFile $Paths.Summary "ZeroDASim complete.`nSource: $script:ZeroDAUrl`nThe two-hour Hancitor-to-key-systems chronology, sub-hour Zerologon privilege escalation, and pre-impact eviction are preserved.`nRoot: $($Paths.Root)`nArtifacts remain; cleanup is separate.`nNo email/link/macro/download, malware, injection, scan/discovery query, C$ access, remote transfer/service, PowerShell shellcode, compilation, Zerologon, machine-password reset, DC authentication, credential/NTLM access, remote action, or impact occurred." 'operator summary'}
